### ISSUE TITLE
Bad cast in StandardChangeLogHistoryService.getRanChangeSets()

### ISSUE THREAD

**Issue by cja-unitb** [liquibase/liquibase#1647] opened 2021-01-22 08:46 UTC
`
<mysql.connector.version>8.0.23</mysql.connector.version>
<liquibase.version>4.2.2</liquibase.version>
`

> class java.time.LocalDateTime cannot be cast to class java.lang.String

`dateExecuted = df.parse((String)tmpDateExecuted);`

We updated the mysql connector. This breaks liquibase.
The type of tmpDateExecuted is LocalDateTime now, not Timestamp.

I suggest adding `else if (tmpDateExecuted instanceof LocalDateTime) {`.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1143) by [Unito](https://www.unito.io/learn-more)

**Comment by adangel** [comment] 2021-01-23 11:54
I can confirm, that his happens when updating from 8.0.22 to 8.0.23. Here's the stacktrace from liquibase-percona:

```
 Caused by: java.lang.ClassCastException: class java.time.LocalDateTime cannot be cast to class java.lang.String (java.time.LocalDateTime and java.lang.String are in module java.base of loader 'bootstrap')
       |            at liquibase.changelog.StandardChangeLogHistoryService.getRanChangeSets (StandardChangeLogHistoryService.java:328)
       |            at liquibase.database.AbstractJdbcDatabase.getRanChangeSetList (AbstractJdbcDatabase.java:1123)
       |            at liquibase.changelog.DatabaseChangeLog.validate (DatabaseChangeLog.java:279)
       |            at liquibase.Liquibase.rollback (Liquibase.java:506)
       |            at liquibase.Liquibase.rollback (Liquibase.java:474)
       |            at org.liquibase.maven.plugins.LiquibaseRollbackSQL.performLiquibaseTask (LiquibaseRollbackSQL.java:98)
       |            at org.liquibase.maven.plugins.AbstractLiquibaseMojo.execute (AbstractLiquibaseMojo.java:401)
```

The change in mysql-connector-java is described here: https://dev.mysql.com/doc/relnotes/connector-j/8.0/en/news-8-0-23.html

> Also, with the implementation of the new mechanism, a getObject(columnIndex) call on a DATETIME column returns a LocalDateTime object now instead of a String. To receive a String like before, use getObject(columnIndex, String.class) instead.

**Comment by psytester** [comment] 2021-01-28 16:25
Same as #1639

**Comment by markkolich** [comment] 2021-01-30 21:01
Definitely a duplicate of https://github.com/liquibase/liquibase/issues/1639.

**Closed** 2021-01-31 07:06 UTC
Labels: StatusDiscovery

**Comment by psytester** [comment] 2021-02-02 14:39
For me, it looks like Liquibase needs to adapt its call.

The MySQL changelog states that the change in Connector/J was as intended.
https://dev.mysql.com/doc/relnotes/connector-j/8.0/en/news-8-0-23.html

Functionality Added or Changed
Important Change:
Also, with the implementation of the new mechanism, a getObject(columnIndex) call on a DATETIME column `returns a LocalDateTime object now` **instead of a** `String`. `To receive a String like before, use getObject(columnIndex, String.class) instead.`
