### ISSUE TITLE
addColumn remarks change table remarks  mysql

### ISSUE THREAD

**Issue by tofdragon** [liquibase/liquibase#1633] opened 2021-01-18 04:01 UTC
## Environment
**Liquibase Version**:  3.8.9  3.10.3  4.2.2

**Liquibase Integration & Version**:  3.8.9  3.10.3  4.2.2

**Liquibase Extension(s) & Version**:  3.8.9  3.10.3  4.2.2

**Database Vendor & Version**:  msyql 5.7.21

**Operating System Type & Version**:  window10

**Spring Boot**: 2.3.4

## Description
```yml
#liquibase-mysql-dev.properties
driver=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://192.168.14.15:3306/my1?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=Asia/Shanghai
username=my1
password=12345678
changeLogFile=database/db-main-changelog.groovy
```

```groovy
databaseChangeLog(logicalFilePath: 'main-feature.groovy') {
    include(file: 'liquibase/table/increase/2.0.0/01-basic-feature.groovy',  relativeToChangelogFile: true)
}

 databaseChangeLog(logicalFilePath: '2.2.0-s_user.groovy') {

    changeSet(author: 'test',id: '20201231-s_user'){
        addColumn(tableName: 's_user'){
            column(name: "login_counter", type: "number(13)",  remarks: "login_counter111",defaultValueNumeric:0)
            column(name: "last_login_time", type: "number(13)",  remarks: "last_login_time222")
        }
    }


}

```

```xml
  <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
            <version>4.2.2</version>
  </dependency>

  <plugin>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-maven-plugin</artifactId>
                <version>4.2.2</version>
                <configuration>
                    <promptOnNonLocalDatabase>false</promptOnNonLocalDatabase>
                    <propertyFile>${propertyFile.location}</propertyFile>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.liquibase</groupId>
                        <artifactId>liquibase-core</artifactId>
                        <version>4.2.2</version>
                    </dependency>
                    <dependency>
                        <groupId>org.liquibase</groupId>
                        <artifactId>liquibase-groovy-dsl</artifactId>
                        <version>3.0.0</version>
                    </dependency>
                </dependencies>
            </plugin>
```

## Steps To Reproduce
mvn liquibase:updateSQL

## Actual Behavior
migrate.sql
```sql
   
ALTER TABLE s_user ADD login_counter numeric(13) DEFAULT 0 NULL COMMENT 'login_counter111' , ADD last_login_time numeric(13) NULL COMMENT 'last_login_time222';

ALTER TABLE s_user COMMENT = 'login_counter111';

ALTER TABLE s_user COMMENT = 'last_login_time222';

## Expected/Desired Behavior
Do not generate scripts to update table comments

## Screenshots (if appropriate)
## Additional Context


┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1121) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment] 2021-01-20 22:13
Hi @tofdragon Thanks for writing up this issue.  This is a duplicate of [https://github.com/liquibase/liquibase/pull/942](https://github.com/liquibase/liquibase/pull/942) which should be released with v4.3 coming out shortly.

**Closed by molivasdat** 2021-01-20 22:13 UTC
Labels: StatusDiscovery
