### ISSUE TITLE
indexExists DOES NOT find index for H2-DB

### ISSUE THREAD

**Issue by SchweigerJul** [liquibase/liquibase#1778] opened 2021-03-29 07:38 UTC
## Environment
springBootVersion = '2.3.8.RELEASE'
kotlinVersion = '1.4.30'
h2database = h2:1.4

**Liquibase Version**:
liquibase-core:3.10.+

**Liquibase Integration & Version**: gradle, spring boot

**Operating System Type & Version**:
Win10

## Description
To update the unique constraint of a db-table, we need to identify wether the old unique constraint does exist.
If so, we delete the old unique constraint to replace it with a new one.
We check for an existing unique constraint, using indexExist. 

This is working as expected for the PostgreSQL.
Not so, for the H2 Test-DB.

indexExist does not recognise the already existing index, thus, in the test db we have then two active unique constraints.

## Steps To Reproduce
Setup:
Configure H2 as a test-db
Add a db table with at least two columns using liquibase.
Add a unique constraint on one of the two columns.

Update Constraint:
look for the existing constraint using indexExists.
Delete existing constraint.
Create new unique constraint with two columns as a unique constraint.

Conclusion:
Two active unique constraints are now in the db, since indexExists does not recognise existing unique constraint

**Comment by molivasdat** [comment] 2021-04-02 12:02
Hi @SchweigerJul Thanks for writing up this issue.  We will add it to the list of issues that we are processing.

**Comment by SchweigerJul** [comment] 2021-04-06 09:56
If there is something unclear or if I can assist you in any manner to solve this issue, please don't hesitate to contact me.
Kind regards,
Julian

**Comment by nvoxland** [comment] 2021-06-03 15:02
@SchweigerJul: You have a changelog sort of like this:

```
    <changeSet id="0" author="nvoxland">
        <createTable tableName="test1">
            <column name="id" type="int"/>
            <column name="name" type="varchar(20)"/>
        </createTable>
        <addUniqueConstraint tableName="test1" columnNames="id" constraintName="test_uq"/>
    </changeSet>

    <changeSet id="1" author="nvoxland">
        <preConditions>
            <indexExists indexName="test_uq"/>
        </preConditions>
    </changeSet>
```
?

I see that failing on H2 because the `<indexExists>` precondition is failing which is what you are seeing.

Going through the reason, **it's not really a bug in h2 that it doesn't work, but a happy coincidence in postgresql that it does.**

The changeset is creating a constraint with a specific name and databases will often implement a constraint by making an index. Some databases will use the same name for the index, some will not. Postgresql happens to use the same name so indexExists works. With h2, it generates a different name (TEST_UQ_INDEX_4 in my test) so there is no index named TEST_UQ.

I created #1881 to add support for a uniqueConstraintExists tag. Until then, you can fall back to a `<sqlCheck>` precondition on h2 (using dbms tag in `preconditions`) with some sort of `select count(*) from ... [constraint metadata tables where name=what you want]...` query. You'll have to figure out the h2 specific query.

Is that analysis and understanding of your issue correct?

**Comment by nvoxland** [comment] 2021-07-16 21:48
Closing this ticket since it's working as designed. #1881 tracks adding the uniqueConstraintExists precondition

**Closed by nvoxland** 2021-07-16 21:48 UTC
Labels: DBH2, ImpactLow, IntegrationGradle, IntegrationSpringboot, Severity3, StatusDiscovery, TypeBug
