### ISSUE TITLE
Sequence not working for Oracle and mariaDb

### ISSUE THREAD

**Issue by reza-sp** [liquibase/liquibase#1168] opened 2020-05-26 14:23 UTC
## Environment
**Liquibase Version**: 3.8.8

**Liquibase Integration & Version**: run as jar File

**Liquibase Extension(s) & Version**:  NO

**Database Vendor & Version**:  10.4.10-MariaDB AND Oracle Database 18c Express Edition 

**Operating System Type & Version**: Windows10

## Description
The following change set produced Exception because the generater sql syntax is invalid.
//it s working for db2 but doesn't work for Oracle and mariadb 
`<changeSet id="db-changelog-sequences-1.0.0" author="RS" dbms="Oracle, mariadb" runOnChange="true">

```
<createSequence 
        sequenceName="ArchiveSequence"
    cycle="true"
        dataType="bigint"
        incrementBy="1"
        minValue="1"
   maxValue="999999999999999999"
        ordered="false"
        startValue="1"/>
		
```

</changeSet>`

## Expected/Desired Behavior
(conn=33) You have an error in your SQL syntax;
ORA-00933: SQL command not properly ended

**Comment by molivasdat** [comment] 2020-05-27 15:07
Hi @reza-sp Thanks for writing this one up.  We will get it added to our list of issues.

**Comment by reza-sp** [comment] 2020-05-28 15:44
error also for MSSQL
Incorrect syntax near the ORDER keyword. [Failed SQL: (156)]

**Comment by reza-sp** [comment] 2020-06-03 12:37
error also for postgresql
 ERROR: syntax error at or near "CACHE"

**Comment by molivasdat** [comment] 2020-06-03 12:50
@reza-sp Thanks for taking the time to identify other databases.

**Comment by ecarneiro01** [comment] 2022-08-24 13:42
Hi @reza-sp, it looks like this was an issue with older versions of liquibase not providing a clear message of what was actually causing the error. If you try to reproduce this behaviour in 4.15.0 you will get a more descriptive error message like this one:

```
Unexpected error running Liquibase: Validation Failed:
     1 changes have validation failures
          ordered is not allowed on postgresql, dbchangelog.xml::createSequence-example::enzo
```

Some of the attributes in the provided changeset are not supported on all databases, i.e. "dataType" is not supported in Oracle. You can see in [this](https://docs.liquibase.com/change-types/create-sequence.html) page the full list of attributes and which DBs they are supported. Once I removed the problematic attributes I could create the sequence correctly on all databases you listed (thanks for that!).

I'll close this issue but feel free to reach out to us in case you run into anything else that's causing you trouble.

**Closed by ecarneiro01** 2022-08-24 13:42 UTC
Labels: TypeBug, Severity3, ImpactMedium, DBOracle, DBPostgres, DBMSSQLServer, DBMariaDB, GStatusDiscovery, hacktoberfest
