### ISSUE TITLE
H2 2.1.210 Table "CONSTRAINTS" not found

### ISSUE THREAD

**Issue by nigelsim** [liquibase/liquibase#2430] opened 2022-01-27 11:56 UTC
## Environment

**Liquibase Version**:

3.10.3

**Liquibase Integration & Version**: Spring boot 2.4.13

**Liquibase Extension(s) & Version**: None

**Database Vendor & Version**: H2 2.1.210

**Operating System Type & Version**: Ubuntu Linux 21.10

## Description

When trying to use H2 2.1.210 Liquibase fails when trying to read the `constraints` table. It appears in recent H2 versions is it now called `table_constraints`.

```
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "CONSTRAINTS" not found; SQL statement:
select CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME from information_schema.constraints where constraint_schema='PUBLIC' and constraint_catalog='74681ECE-17BA-4149-B979-E8C4E193D43F' and constraint_type='UNIQUE' and table_name='DATABASECHANGELOGLOCK' [42102-210]
``` 

This appears to be because there is no specific case for H2 in `JdbcDatabaseSnapshot`.

## Steps To Reproduce

List the steps to reproduce the behavior.
- Update H2 to 2.1.210

**Comment by marcelstoer** [comment] 2022-03-01 13:56
> Update H2 to 2.1.210

From 1.x (e.g. 1.4.200) to 2.x..

> It appears in recent H2 versions is it now called `table_constraints`.

The migration guide is a little terse and does not mention those tables explicitly: http://www.h2database.com/html/migration-to-v2.html

> This appears to be because there is no specific case for H2 in `JdbcDatabaseSnapshot`.

I guess we'll now even need _two_ cases, one for H2 1.x and one for H2 2.x.

**Comment by nvoxland** [comment] 2022-03-02 19:00
This is already be fixed in Liquibase in Liquibase 4.7+

**Closed by nvoxland** 2022-03-02 19:00 UTC
Labels: TypeBug, Severity4, DBH2, IntegrationSpringboot

**Comment by marcelstoer** [comment] 2022-03-02 19:34
Thanks, found the PR #2285

**Comment by nealeu** [comment] 2022-07-31 12:50
@nvoxland Due to https://github.com/liquibase/liquibase/issues/2385, we cannot move to 4.7+.  I can't even validate 4.6.x with H2 2, so it's really getting quite impossible to move beyond H2 1.x and Liquibase 3.x without a massive rewrite to workaround #2385.

**Comment by FrostbittenKing** [comment] 2022-07-31 17:58
@nealeu Hi, what is the problem with 4.6.x? I'm about to wrap up migration from 3.8.7!!! to 4.13.0.
I ran in quite a few nasty, subtle, deep-rooted bugs, not only this one (which is now luckily easy to fix, cause I worked around all precursor bugs).
Had to fix / work around the following bugs:
* https://github.com/liquibase/liquibase/issues/2385 - the lower case problem with columns like, key, value ...)
* https://github.com/liquibase/liquibase/issues/2396 - the massive logging spam
* https://github.com/liquibase/liquibase/issues/2714 - the checksum bug when deleteCascade="true" is used in addForeignKeyConstraint (i discovered the cause after debugging the liquibase code, later I found the bug report)
* https://github.com/liquibase/liquibase/issues/2818 - changelog is found twice in classpath.
**

**Comment by kataggart** [comment] 2022-08-01 13:45
Hey all - thanks for the feedback and a reminder to please open new issues when you are raising concerns. We don't tend to re-process closed issues and we want to make sure your concerns do not get lost! And please check in on the open issue you reference to keep track of them. Several of them are not bugs and have responses, are moving forward as possible enhancements, etc. Thanks!
