### ISSUE TITLE
Liquibase could support `renameColumn` for Sqlite 3.25.0+

### ISSUE THREAD

**Issue by Jerbell** [liquibase/liquibase#2925] opened 2022-06-07 08:32 UTC
## Environment

**Liquibase Version**: 4.11

**Liquibase Integration & Version**: N/A

**Liquibase Extension(s) & Version**: N/A

**Database Vendor & Version**: Sqlite 3.25.0 onwards

**Operating System Type & Version**: N/A

## Description

At present sqlite `renameColumn` isn't supported:
https://docs.liquibase.com/change-types/rename-column.html

However, if you set the minimum sqlite version required to 3.25 then you could use the rename column.
https://www.sqlite.org/releaselog/3_25_1.html

## Steps To Reproduce

Run the rename column command with Sqlite.

## Actual Behavior
Doesn't work.

## Expected/Desired Behavior
Could be implemented if you want.

## Screenshots (if appropriate)
-

## Additional Context
-

EDIT: title originally said `dropColumn` instead of `renameColumn`

**Comment by MalloD12** [comment] 2022-09-12 16:15
I was not able to reproduce this issue on below environment:

```
Liquibase Version: 4.15.0

Liquibase Integration & Version: CLI

Liquibase Extension(s) & Version: N/A

Database Vendor & Version: Sqlite 3.36.0 

Operating System Type & Version: Mac OS (M1)```

I tried using examples (changelogs) provided here and all of the have executed successully.

Closing this issue by now. @Jerbell could you please try again on a recent version and please let me know if you are still able to reproduce it? 

Thanks,
Daniel.

**Closed** 2022-10-11 17:48 UTC
Labels: TypeEnhancement, DBSQLLite, autocandidate, ver4.11.0
