### ISSUE TITLE
Liquibase generatechangelog command is not generating sequences for postgre db

### ISSUE THREAD

**Issue by shilpagupta-axtria** [liquibase/liquibase#2619] opened 2022-03-09 11:03 UTC
## Environment

**Liquibase Version**: 4.8.0

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:postgre

**Operating System Type & Version**:

## Description

Liquibase generatechangelog command is not generating sequences but below generated create table statement is referring to the sequence.
CREATE TABLE "test_liquibase"."test" ("id" INTEGER DEFAULT TEST_ID_SEQ NOT NULL     
## Steps To Reproduce

List the steps to reproduce the behavior.
- Please be precise and ensure private information is redacted
- Include things like
  - Files used - sql scripts, changelog file(s), property file(s), config files, POM Files
  - Exact commands used - CLI, maven, gradle, spring boot, servlet, etc.

## Actual Behavior
A clear and concise description of what happens in the software with the **version used**.
- Include console output if relevant
- Include log files if available.

## Expected/Desired Behavior
Liquibase generatechangelog command should generate sequences.

**Comment by ecarneiro01** [comment] 2022-08-10 18:55
Hi @shilpagupta-axtria, I created a sequence and ran the `generateChangeLog` command on both in Liquibase 4.80 and 4.15.0 and I couldn't reproduce the issue in neither of them. I saw that the sequence was being generated in the output from the `generateChangelog` command. The DB I used was PostgreSQL 14.2.

I will close this issue but if you still have troubles with this feel free to reach out to us again.

**Closed by ecarneiro01** 2022-08-10 18:55 UTC
Labels: TypeBug, DBPostgres, ver4.8.0, featureGenerateChangelog, sprint2022-31
