### ISSUE TITLE
Postgres smallint syntax error

### ISSUE THREAD

**Issue by jong82** [liquibase/liquibase#1015] opened 2020-03-04 16:54 UTC
**Describe the bug**
Creating a `smallint` column in postgres incorrectly specifies the length as `smallint(5)` which generates a syntax error.  It just needs to be `smallint`.

**To Reproduce**
`liquibase generateChangeLog` against a database that has a smallint column.
`liquibase update` against an empty database to recreate the schema.

**Expected behavior**
Create a smallint without error

**Screenshots**
 Unexpected error running Liquibase: ERROR: syntax error at or near "("
Position: 268 [Failed SQL: (0) CREATE TABLE public.xyz (.....SMALLINT(5)....)

**Additional context**
This was run inside the published docker container although that should be irrelevant for this error.

**Comment by jong82** [comment] 2020-03-06 17:36
PR opened, built and tested locally.
https://github.com/liquibase/liquibase/pull/1025

**Comment by jong82** [comment] 2020-03-06 22:27
Built a new PR with a better fix by adding it to the list of unmodifiable types.
https://github.com/liquibase/liquibase/pull/1027

**Comment by MaxAller** [comment] 2020-03-22 16:10
FWIW this changeset doesn't repro the issue:
```xml
<createTable tableName="serial_test">
    <column name="id" type="smallint">
        <constraints nullable="false" primaryKey="true"/>
    </column>
</createTable>
```
produces
```sql
CREATE TABLE public.serial_test (id SMALLINT NOT NULL, CONSTRAINT SERIAL_TEST_PKEY PRIMARY KEY (id));
```
in LiquiBase 3.8.8.

**Comment by molivasdat** [comment] 2020-05-18 16:38
Hi @jong82 Thanks for writing up this issue.  This has been fixed a different way than the pull request 1027.  Is it acceptable to close this issue as having been fixed?

**Comment by StevenMassaro** [comment] 2021-11-18 16:50
I am unable to reproduce this issue with Liquibase 4.6.1.

I created a table in Postgres like this:

```
create table lb1015 (testcol smallint);
```

I ran `liquibase generateChangeLog --changelogfile new.xml` and `liquibase generateChangeLog --changelogfile new.sql`. They generated the following respective changesets:

```
    <changeSet author="Steve (generated)" id="1637253846084-1">
        <createTable tableName="lb1015">
            <column name="testcol" type="SMALLINT"/>
        </createTable>
    </changeSet>
```
```
-- changeset Steve:1637253843165-1
CREATE TABLE "public"."lb1015" ("testcol" SMALLINT);
```

Looks like it was resolved with this PR: https://github.com/liquibase/liquibase/pull/1046

**Closed** 2021-11-18 16:54 UTC
Labels: TypeBug, StatusDiscovery, Severity3, ImpactLow, PRAssociated, DBPostgres, GStatusActive
