### ISSUE TITLE
please provide sha256sum file for the release

### ISSUE THREAD

**Issue by yamb00** [liquibase/liquibase#1742] opened 2021-03-03 16:02 UTC
## Environment
**Liquibase Version**: 4.3.1

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:

**Operating System Type & Version**:

## Description
Please provide a sha256sum file for the release. This would be very helpfull

## Expected/Desired Behavior
example:

add liquibase-checksums_4.3.1.txt

1f44e493ed63e2715594df4a4513fe9700f04ae7afcbce967e61e0a3ad97df8b  liquibase-4.3.1.jar
3de6ac8c764e3b27e8ee4ac9275543531504b8ca572fcf1c376bed59b6b8a46a  liquibase-4.3.1.tar.gz
49820d45aadf40cba3c068ab0afd42434e194418f38ab48b86f2333fe7b3e741  liquibase-4.3.1.zip
df65a96744d80e08f03dda5b1e74af39606c12814ae8f3bccdc9077f6f5a4427  liquibase-macos-installer-4.3.1.dmg
3de6ac8c764e3b27e8ee4ac9275543531504b8ca572fcf1c376bed59b6b8a46a  liquibase-windows-x64-installer-4.3.1.exe

**Comment by molivasdat** [comment] 2021-03-12 01:16
Hi @yamb00 Thanks for writing up this enhancement request.  We will add it to the list of issues that we are processing.

**Comment by lbadam** [comment] 2024-10-16 21:36
Closing this as a duplicate of #6062. PR #6431 will add SHA256 support to Liquibase.

**Closed by lbadam** 2024-10-16 21:36 UTC
Labels: TypeEnhancement, IntegrationCLI, Severity4, DBAll, ImpactLow
