### ISSUE TITLE
migration completes but no entry in databasechangelog when connection closed

### ISSUE THREAD

**Issue by kbfirebreather** [liquibase/liquibase#5074] opened 2023-10-18 15:09 UTC
### Search first

- [X] I searched and no similar issues were found

### Description

Experiencing an issue where a changelog is mid migration. The changelog executes the migration script, loses connection to PostgreSQL. Service restarts as a result, and attempts to run the migration again because there is no entry in the changelog, and fails because the table already exists.

```
Running Changeset: changelog.table.xml::rollback-all::foo
Running Changeset: changelog.table.xml::1627594221430-1::user_id(generated)
Running Changeset: changelog.table.xml::1627594221430-2::user_id(generated)

Unexpected error running Liquibase: This connection has been closed. For more information, please use the --log-level flag
```

Service restarts and is in a crashloop

```
Unexpected error running Liquibase: Migration failed for changeset changelog.table.xml::1627594221430-2::user_id(generated): Reason: liquibase.exception.DatabaseException: ERROR: relation "components" already exists [Failed SQL: (0) CREATE TABLE table.components (id UUID NOT NULL, componenttypeid UUID, metadata JSONB, CONSTRAINT components_pkey PRIMARY KEY (id))]
```

I would expect the migration and the insert into the changelog to happen in a single transaction so that if the connection does get lost, the migration would never be committed. 

### Steps To Reproduce

Take down postgres service in the middle of a migration

### Expected/Desired Behavior

Service restarts, and re-runs migration, which is successful because the migration was never fully committed. 

### Liquibase Version

4.19.0

### Database Vendor & Version

PostgreSQL 14.8.0

### Liquibase Integration

CLI

### Liquibase Extensions

liquibase-sessionlock

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment] 2023-10-27 16:15
Hi @kbfirebreather
Currently the migration and insertion to the `databasechangelog` table aren't wrapped in a transaction because not all databases support them.

I understand the issue you're experiencing, and it is replicable, though I would need some more information in order to guide you to a workaround. Would you be able to provide your changelog? Please make sure that there is no confidential or personal information before sending.

Apart from that, as a good practice, it's better to include only one change per changeset, so that after every migration the change is logged into the `databasechangelog` table. That might be part of the cause of this problem.

Thank you,
Tatiana

**Comment by kbfirebreather** [comment] 2023-11-01 18:12
Here is a snippet of my changelog. There are a lot more changesets in the original changelog after the failing changeset (`1627594221430-2`), but I left them out since it's not getting that far. The changeset contents in this snippet are unmodified. 

```xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:pro="http://www.liquibase.org/xml/ns/pro" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-4.1.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.1.xsd">
    <changeSet author="eXYZ" id="rollback-all">
        <tagDatabase tag="0.0.0"/>
    </changeSet>
    <changeSet author="eXYZ (generated)" id="1627594221430-1">
        <createTable tableName="component_types">
            <column name="id" type="UUID">
                <constraints nullable="false" primaryKey="true" primaryKeyName="component_types_pkey"/>
            </column>
            <column name="metadata" type="JSONB"/>
        </createTable>
    </changeSet>
    <changeSet author="eXYZ (generated)" id="1627594221430-2">
        <createTable tableName="components">
            <column name="id" type="UUID">
                <constraints nullable="false" primaryKey="true" primaryKeyName="components_pkey"/>
            </column>
            <column name="componenttypeid" type="UUID"/>
            <column name="metadata" type="JSONB"/>
        </createTable>
    </changeSet>
</databaseChangeLog>
```

**Comment by tati-qalified** [comment] 2023-11-08 15:29
Hi @kbfirebreather, thank you for sending your code.

Here's what's happening: the connection is being interrupted right in between when a changeset is executed and the next SQL statement, where the data is inserted to the `databasechangelog` table. 
If the connection is closed **while** executing the migration code, there would be a rollback and the issue would not arise.

Most databases don't support transactions for DDL statements, so it wouldn't be possible for Liquibase to wrap both the migration and the insertion into the `databasechangelog` table in one single transaction.

Unfortunately, this isn't something we can control or fix, so I'll be closing this issue. If you happen to find a workaround for this, be sure to let us know, as it would be useful for other users as well.

Thank you
Tatiana

**Closed by tati-qalified** 2023-11-08 15:29 UTC
Labels: TypeBug, DBPostgres

**Comment by zxli** [comment] 2024-05-15 00:15
@tati-qalified, could this bug be reconsidered? Maybe most databases don't support transaction for DDL. But there are a few commonly used databases (e.g. PostgreSQL and SQL Server) which do. Could the transaction for DDL be supported for those databases and keep the current behavior for other databases?

**Comment by tati-qalified** [comment] 2024-05-17 17:11
Hello @zxli, considering that this would imply significant refactoring of the code, and that it's not a frequent problem for our users, this is not a priority for our development team.

However, if you'd be willing to submit a PR, the developers will be available to provide any guidance you might need. This way you'd be ensuring that it gets implemented sooner.

Thank you,
Tatiana

**Comment by zxli** [comment] 2024-05-22 04:43
@tati-qalified, I hit a [similar issue](https://github.com/liquibase/liquibase/issues/3780) while deploying database schema changes with Liquibase.

This is the second time I hit the issue (that Liquibase doesn't use transaction between the actual database deployment and update for Liquibase's metadata) in a production system in just three months. And it's a very complicated process to get access to production system and fix it manually.

Could you shed some lights where to look at in the code? It'd be really helpful that Liquibase team could reconsider this bug and prioritize it.

**Comment by tati-qalified** [comment] 2024-05-23 16:57
@zxli thank you for your feedback. 

Though PostgreSQL and MSSQL allow DDL statements inside transactions, it's not as straightforward as it may seem. [This comment](https://github.com/liquibase/liquibase/issues/3780#issuecomment-1426392368) may explain it more clearly. Specifically this section:

> For most databases, most DDL such as your createTable statement the database auto-commits the transaction and so when the insert into databasechangelog fails due to the constraint, we can't roll it back.
>In specific cases like your example, we can figure out the rollback logic for createTable (do a drop table), but in general we don't always know the correct logic to roll back and we don't even really know what worked and what failed in order to know what to roll back and what to not always.

This isn't something that we're looking to solve, so we won't be implementing a fix.

Apart from that, it's not a frequent problem, as it only happens if the database connection is lost specifically between two statements. It's concerning that you've encountered it twice, and it's probably a symptom of connection issues in the environment. I'd suggest looking into that, as it might help avoiding this problem in the future.

Thank you,
Tatiana
