### ISSUE TITLE
`foreignKeyConstraintExists` not working

### ISSUE THREAD

**Issue by PedDavid** [liquibase/liquibase#2389] opened 2022-01-20 17:17 UTC
## Environment

**Liquibase Version**:
```
 ./bin/liquibase --version
####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ## 
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ## 
##  Free schema change activity reports at        ##
##      https://hub.liquibase.com                 ##
##                                                ##
####################################################
Starting Liquibase at 17:02:20 (version 4.7.0 #1140 built at 2022-01-07 19:26+0000)
Liquibase Version: 4.7.0
Liquibase Community 4.7.0 by Liquibase
Running Java under /usr/java/jdk1.8.0_144/jre (Version 1.8.0_144)
```
**Note:** The same Liquibase changeSet worked in Liquibase Version: 3.10.2

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:
```
> SELECT version();
                                   version                                    
------------------------------------------------------------------------------
 PostgreSQL 10.13 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.9.3, 64-bit
 ```

**Operating System Type & Version**:
```
$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

## Description

`foreignKeyConstraintExists` doesn't seem to be working.
I'm trying to `MARK_RAN` if foreignKey already exists so I just create the FK if it is absent.

This was working with Liquibase 3.10.2. I'm in the process of upgrading it in order to improve performance as a simple migration took multiple hours with the previous version.

## Steps To Reproduce

```xml
<changeSet ...>
  <preConditions onFail="MARK_RAN">
    <not>
      <foreignKeyConstraintExists foreignKeyName="FK_NAME"/>
    </not>
  </preConditions>
  <addForeignKeyConstraint constraintName="FK_NAME"  ... />
</changeSet>
```

## Actual Behavior

changeSet execution fails trying to execute the `addForeignKeyConstraint` (since the constraint with that name already exists).

## Expected/Desired Behavior

The precondition onFail should've been called (adding the changeSet as `MARK_RAN` to liquibase changelog), and, as such, the changeSet shouldn't execute `addForeignKeyContstraint`.

## Additional Context

I was able to implement a temporary workaround specific to the database vendor that confirms that the FK exists.

```
        <preConditions onFail="MARK_RAN">
            <sqlCheck expectedResult="0">
              SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_name='FK_NAME' AND table_schema = '<x>'
            </sqlCheck>
        </preConditions>
```

From my (limited) understanding, Liquibase does some sort of DB snapshot, which it uses to verify some of these pre-conditions (not the `sqlCheck`) and it doesn't seem to be importing the ForeignKey to that snapshot.

**Comment by kataggart** [comment] 2022-01-21 20:21
thanks @PedDavid we are taking a look

**Comment by joserebelo** [comment] 2022-01-28 23:14
Tracked the issue down to #2228.

Easily reproducible against postgres:

```sql
CREATE TABLE table1 (
    id1 INT PRIMARY KEY
);

CREATE TABLE table2 (
    id1 INT,
    CONSTRAINT fk_1
        FOREIGN KEY (id1)
        REFERENCES table1 (id1)
);
```

```xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd"
                   logicalFilePath="liquid-test">

    <changeSet author="joserebelo" id="liquid-test-fk">
        <preConditions onFail="MARK_RAN">
            <not>
                <foreignKeyConstraintExists foreignKeyName="fk_1"/>
            </not>
        </preConditions>
        <addForeignKeyConstraint baseColumnNames="id1" baseTableName="table2" constraintName="fk_1"
                                 referencedColumnNames="id1" referencedTableName="table1" validate="true"/>
    </changeSet>
</databaseChangeLog>
```

The foreign key will be added even though it exists, and it will fail.

In ForeignKeyComparator, line 55, it looks like `otherForeignKey.getForeignKeyTable()` is not `null`, even though `thisForeignKey.getForeignKeyTable().getName()` is (I think it's the example set by `ForeignKeyExistsPrecondition`?)

Checking for `thisForeignKey.getForeignKeyTable().getName() != null` seems to fix this specific issue, but I'm not sure if that's the correct approach.

**Comment by ClaudenirFreitas** [comment] 2022-03-26 21:51
Same behaviour using MySQL 5.7. 
I reproduced using [these steps](https://github.com/liquibase/liquibase/issues/2389#issuecomment-1024733756).

Error:
```
Unexpected error running Liquibase: Can't write; duplicate key in table '#sql-1_4' [Failed SQL: (1022) ALTER TABLE api_manager.table2 ADD CONSTRAINT fk_1 FOREIGN KEY (id1) REFERENCES api_manager.table1 (id1)]
```

**Comment by liam-verta** [comment] 2022-04-05 16:16
@kataggart 
Can we raise the severity on this? While it can be bypassed by setting changes to mark as run if they fail, that results in hard to understand migration breaks.  

What is the workaround for this problem? Does providing the foreign key table name do it? 

Perhaps we could roll back #2228 ? It was submitted and merged without tests, and causes a much larger breakage than the problem it fixes.

**Comment by joserebelo** [comment] 2022-04-05 16:24
@liam-verta I have an open PR that fixes this: #2565

**Comment by kataggart** [comment] 2022-04-05 16:29
@liam-verta sorry for delay here; will raise it with the team again and see what we might be able to do. Thanks @joserebelo for the PR.

**Comment by liam-verta** [comment] 2022-04-07 18:08
@joserebelo 
> I can also confirm that providing the table name serves as a workaround, at least during my tests.

Awesome, thanks. 

@kataggart 
Thanks for taking another look.

**Comment by liam-verta** [comment] 2022-04-07 18:18
Another reasonable fix here would be to log a warning if `foreignKeyTableName` is not provided and maybe make it required parameter in 5.x?

**Comment by 40rn05lyv** [comment] 2022-05-17 08:46
Please, document a **Breaking Change** in Release Notes for version 4.7.0, because attribute `foreignKeyTableName` of tag `<foreignKeyConstraintExists>` became required because of regression.

**Closed as completed** 2022-05-19 13:23 UTC
