### ISSUE TITLE
Periodically can't parse precondition onFail property

### ISSUE THREAD

**Issue by Viacheslav-Tikhonov** [liquibase/liquibase#1047] opened 2020-03-21 20:35 UTC
**Description**

liquibase.precondition.core.PreconditionContainer has two methods:
    public void setOnFail(String onFail) 
    public void setOnFail(FailOption onFail) 

But when there is going changeset parsing it uses reflection for getting write method (in liquibase.util.ObjectUtil). And it doesn't check argument type. As a result it takes method with wrong argument for onFail property. So it generates such error:

`liquibase.parser.core.ParsedNodeException: Error setting property
	at liquibase.serializer.AbstractLiquibaseSerializable.load(AbstractLiquibaseSerializable.java:107)
...
Caused by: liquibase.exception.UnexpectedLiquibaseException: Cannot call public void liquibase.precondition.core.PreconditionContainer.setOnFail(liquibase.precondition.core.PreconditionContainer$FailOption) with value of type java.lang.String
	at liquibase.util.ObjectUtil.setProperty(ObjectUtil.java:177)
	at liquibase.serializer.AbstractLiquibaseSerializable.load(AbstractLiquibaseSerializable.java:68)
	... 37 more`

It doesn't fail application. But it ignores all preconditions.

**To Reproduce**
I don't know exactly how to reproduce it. I just get this error periodically on restart my application. Next restart usually works fine without any changes from me.

**Expected behavior**
Every restart of application doesn't produce such error and handle onFail property for preconditions correctly

**Comment by SteveDonie** [comment] 2020-03-23 16:12
Thanks very much for the bug report! We will take a look and see if we can narrow down a repro case.

**Comment by molivasdat** [comment] 2020-05-14 12:15
Hi @Viacheslav-Tikhonov What version of liquibase are you using when you see these periodic issues?
Are you using this as part of the cli, maven, ant task or some other interface?

**Comment by Viacheslav-Tikhonov** [comment] 2020-05-14 12:38
We use org.liquibase:liquibase-core:3.8.7 as a dependency in our gradle script.

**Comment by ncovercash** [comment] 2021-11-22 07:35
Any update on this?  I just encountered this error, here's my changeset:
```yaml
databaseChangeLog:
  - changeSet:
      id: some-id
      author: itsa-me
      comment: Drop previous schema
      preConditions:
        - onFail: mark_ran
        - tableExists:
            tableName: something
      changes:
        - dropTable:
            tableName: something
        # etc
```

I cannot seem to replicate this error in a normal shell, however, when the following is used in a Git pre-commit hook (I like to validate as many changes here, before it even gets to CI/CD):

```
Starting Liquibase at 01:22:16 (version 4.6.1 #98 built at 2021-11-04 20:16+0000)
Liquibase Version: 4.6.1
Liquibase Community 4.6.1 by Liquibase
liquibase.parser.core.ParsedNodeException: Error setting property
	at liquibase.serializer.AbstractLiquibaseSerializable.load(AbstractLiquibaseSerializable.java:107)
	at liquibase.precondition.PreconditionLogic.load(PreconditionLogic.java:28)
	at liquibase.precondition.core.PreconditionContainer.load(PreconditionContainer.java:278)
	at liquibase.changelog.ChangeSet.handleChildNode(ChangeSet.java:438)
	at liquibase.changelog.ChangeSet.load(ChangeSet.java:373)
	at liquibase.changelog.DatabaseChangeLog.createChangeSet(DatabaseChangeLog.java:627)
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:352)
	at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:320)
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:82)
	at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:586)
	at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:550)
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:411)
	at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:320)
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:82)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:369)
	at liquibase.Liquibase.validate(Liquibase.java:2280)
	at liquibase.integration.commandline.Main.doMigration(Main.java:1847)
	at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:397)
	at liquibase.Scope.lambda$child$0(Scope.java:177)
	at liquibase.Scope.child(Scope.java:186)
	at liquibase.Scope.child(Scope.java:176)
	at liquibase.Scope.child(Scope.java:155)
	at liquibase.integration.commandline.Main$1.run(Main.java:396)
	at liquibase.integration.commandline.Main$1.run(Main.java:220)
	at liquibase.Scope.child(Scope.java:186)
	at liquibase.Scope.child(Scope.java:162)
	at liquibase.integration.commandline.Main.run(Main.java:220)
	at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:32)
	at liquibase.command.CommandScope.execute(CommandScope.java:150)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:45)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:15)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:325)
	at liquibase.Scope.child(Scope.java:186)
	at liquibase.Scope.child(Scope.java:162)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:291)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:80)
Caused by: liquibase.exception.UnexpectedLiquibaseException: Cannot call public void liquibase.precondition.core.PreconditionContainer.setOnFail(liquibase.precondition.core.PreconditionContainer$FailOption) with value of type java.lang.String
	at liquibase.util.ObjectUtil.setProperty(ObjectUtil.java:192)
	at liquibase.serializer.AbstractLiquibaseSerializable.load(AbstractLiquibaseSerializable.java:68)
	... 42 more
No validation errors found.
Liquibase command 'validate' was executed successfully.
```

My call to `liquibase validate` is fairly standard:

```
liquibase validate \
  --driver=org.postgresql.Driver \
  --url="jdbc:postgresql://localhost:5432/redacted" \
  --username=redacted --password=redacted \
  --changelog-file src/main/resources/db/changelog-master.yaml
```

My master changelog is just an `includeAll`, however, the file above is the only one with `onFail` (or any preconditions, for that matter).

This is being ran on a Windows machine with PowerShell:

```
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1237
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1237
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

And as for Liquibase:
```
Starting Liquibase at 01:32:15 (version 4.6.1 #98 built at 2021-11-04 20:16+0000)
Running Java under C:\Program Files\Eclipse Adoptium\jdk-11.0.13.8-hotspot (Version 11.0.13)

Liquibase Version: 4.6.1
Liquibase Community 4.6.1 by Liquibase
```

Not sure what else would be helpful to provide; feel free to let me know!

This is all part of a Spring Boot application, however, Git is running `liquibase` via a bash script, so there should be no interfacing whatsoever with the Spring Boot application.  I'm especially confused by the fact that `validate` succeeds despite this.

**Comment by ncovercash** [comment] 2021-11-22 07:43
The exact same command, when run in the exact same environment (another commit that caused the hook to run), produced different results (no error, worked as expected).  Love this bug.

**Comment by molivasdat** [comment] 2021-11-22 13:47
Hi @ncovercash .  These intermittent issues are really difficult to figure out where the issue is.  I don't have an update at this time on when this will be fixed especially since it's intermittent.

**Comment by ncovercash** [comment] 2021-11-22 19:55
@molivasdat I completely understand!  It's certainly not build-breaking or anything and does not seem to cause any actual issue as far as validation is concerned -- just wanted to try and contribute whatever I could for repro/debugging!

**Comment by molivasdat** [comment] 2021-11-23 13:33
@ncovercash It's all good.  Thanks for the additional information and hopefully we can figure this one out.

**Comment by kataggart** [comment] 2022-07-18 19:30
@ncovercash An oldie but goody... are you still facing this one? How about you @Viacheslav-Tikhonov ?

**Comment by kataggart** [comment] 2022-08-10 19:37
closing this for now; please let us know if you are still facing the issue. Thanks.

**Closed by kataggart** 2022-08-10 19:37 UTC
Labels: TypeBug, Severity3, ImpactMedium, DBAll, IntegrationGradle, IntegrationSpringboot, hacktoberfest
