### ISSUE TITLE
Liquibase 4.3.1 logs not being output to log4j2 specified log file

### ISSUE THREAD

**Issue by JonBetts** [liquibase/liquibase#1770] opened 2021-03-18 14:37 UTC
## Environment
**Liquibase Version**: 4.3.1

**Liquibase Integration & Version**:  Maven

**Liquibase Extension(s) & Version**:  N/A

**Database Vendor & Version**: PostgreSQL 13.1

**Operating System Type & Version**: Mac OSX (Big Sur)

## Description
I raised an issue on the Liquibase forum [here](https://forum.liquibase.org/t/liquibase-logging-with-log4j2/5202/3) and was told that it's likely to be a bug. The issue is found when using Liquibase (v4.3.1) with log4j2 (v2.14.0) - because the log4j-liquibase jar that sorts out the Liquibase logging uses Liquibase 3.5.3 behind the scenes, if I'm using Liquibase 4 myself, the jar file for version 3.5.3 gets excluded by Maven from my project (standard behaviour), and Liquibase log output isn't output to the log file I have set up. If I downgrade the version of Liquibase I use to version 3.5.3, the Liquibase logs are successfully output to my Tomcat 8.5 (catalina) log file with absolutely zero changes. Ideally I don't want to downgrade my Liquibase version to sort this out, but equally I don't know if it's a bug in Liquibase itself, or the log4j-liquibase jar file that automatically does the logging.

## Steps To Reproduce
Add the following entries to the Maven pom file:

```
               <dependency>
                       <groupId>org.apache.logging.log4j</groupId>
                       <artifactId>log4j-api</artifactId>
                       <version>2.14.0</version>
                       <scope>provided</scope>
               </dependency>
               <dependency>
                       <groupId>org.apache.logging.log4j</groupId>
                       <artifactId>log4j-core</artifactId>
                       <version>2.14.0</version>
                       <scope>provided</scope>
               </dependency>
                <dependency>
                       <groupId>org.apache.logging.log4j</groupId>
                       <artifactId>log4j-liquibase</artifactId>
                       <version>2.14.0</version>
                </dependency>
                <dependency>
                       <groupId>org.liquibase</groupId>
                       <artifactId>liquibase-core</artifactId>
                       <version>4.3.1</version>
                </dependency>
```

Ensure that the log4j2 core and API jars are on the Tomcat classpath (either in the the CATALINA_HOME or CATALINA_BASE lib folder).

Set up a basic log4j2.xml configuration file:

```
<Configuration status="WARN">
  <Properties>
    <Property name="logdir">${sys:catalina.base}/logs</Property>
    <Property name="layout">%-5p %d %C{1}:%L %M-&gt; %m%n</Property>
  </Properties>
  <Appenders>
    <Console name="CONSOLE" target="SYSTEM_OUT">
      <PatternLayout pattern="${layout}"/>
    </Console>
    <RollingFile name="CATALINA" fileName="${logdir}/catalina.log" filePattern="${logdir}/catalina.%d{yyyy-MM-dd}.log.gz">
      <PatternLayout pattern="${layout}"/>
      <CronTriggeringPolicy schedule="0 0 0 * * ?"/>
      <DefaultRolloverStrategy>
        <Delete basePath="${logdir}" maxDepth="1">
          <IfFileName glob="catalina.*.log.gz"/>
          <IfAccumulatedFileCount exceeds="31"/>
        </Delete>
      </DefaultRolloverStrategy>
    </RollingFile>
  </Appenders>
  <Loggers>
    <Logger name="liquibase" level="DEBUG"/>
    <Root level="DEBUG">
      <AppenderRef ref="CATALINA"/>
      <AppenderRef ref="CONSOLE"/>
    </Root>
  </Loggers>
</Configuration>
```

With the above log file, Maven setup and jars in place on the Tomcat classpath, you just need to have some kind of Liquibase commands setup in order to test it out.

## Actual Behavior
No Liquibase logs are output to the catalina.log file.

## Expected/Desired Behavior
For any Liquibase logs that match the logging level (in this case 'DEBUG') to be output to catalina.log.

## Screenshots (if appropriate)
I don't think screenshots are useful in this scenario, but can provide some on request.

## Additional Context
Please let me know if you need me to provide anything else regarding this.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1361) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment] 2021-03-19 12:09
Hi @JonBetts Thanks for writing up this issue.  Thanks for the writeup of exactly how the issue occurs.  We will look into see if this is a bug or how to workaround/fix the issue.

**Comment by JonBetts** [comment] 2021-03-19 14:15
> Hi @JonBetts Thanks for writing up this issue. Thanks for the writeup of exactly how the issue occurs. We will look into see if this is a bug or how to workaround/fix the issue.

Thanks very much Mike. Let me know if you need anything else from me at any point.

**Comment by JonBetts** [comment] 2021-03-29 11:06
Just a note to say that the ticket mentioned above was added by one of the Log4j developers regarding this exact same issue, so I'm more than happy for this ticket to be closed as his has more technical detail on what the actual problem is.

**Comment by nvoxland** [comment] 2021-06-02 18:43
Yes, I'll close this issue to keep the tracking and discussion in the other.

**Comment by nvoxland** [comment] 2021-06-02 18:43
Duplicate of #1777

**Closed by nvoxland** 2021-06-02 18:43 UTC
Labels: DBPostgres, ImpactMedium, IntegrationMaven, Severity4, StatusDiscovery, TypeQuestion
