### ISSUE TITLE
setColumnRemarks Mysql  execute sql : ALTER TABLE [tabeName]  COMMENT = 'your comment';

### ISSUE THREAD

**Issue by tofdragon** [liquibase/liquibase#1632] opened 2021-01-18 02:52 UTC
## Environment
**Liquibase Version**:  3.8.9  3.10.3  4.2.2

**Liquibase Integration & Version**:  3.8.9  3.10.3  4.2.2

**Liquibase Extension(s) & Version**:  3.8.9  3.10.3  4.2.2

**Database Vendor & Version**:  msyql 5.7.21

**Operating System Type & Version**:  window10

**Spring Boot**: 2.3.4

## Description
```yml
#liquibase-mysql-dev.properties
driver=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://192.168.14.15:3306/my1?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=Asia/Shanghai
username=my1
password=12345678
changeLogFile=database/db-main-account.xml
```

```xml

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   logicalFilePath="path-independent"
                   xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
    http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.2.xsd">

    <include file="my21.xml" relativeToChangelogFile="true"/>

</databaseChangeLog>

<?xml version="1.0" encoding="UTF-8"?>

<databaseChangeLog
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.2.xsd
        http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd">

<changeSet author="liquibase-docs"  id="setColumnRemarks-example">
    <setColumnRemarks  columnName="login_fail_counter"
                       remarks="login_fail_counter_test11"
                       tableName="s_user"/>

    <setColumnRemarks
        columnName="last_login_fail_time"
        remarks="last_login_fail_time_test22"
        tableName="s_user"/>

</changeSet>


</databaseChangeLog>

```

```xml
  <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
            <version>4.2.2</version>
  </dependency>

  <plugin>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-maven-plugin</artifactId>
                <version>4.2.2</version>
                <configuration>
                    <promptOnNonLocalDatabase>false</promptOnNonLocalDatabase>
                    <propertyFile>${propertyFile.location}</propertyFile>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.liquibase</groupId>
                        <artifactId>liquibase-core</artifactId>
                        <version>4.2.2</version>
                    </dependency>
                    <dependency>
                        <groupId>org.liquibase</groupId>
                        <artifactId>liquibase-groovy-dsl</artifactId>
                        <version>3.0.0</version>
                    </dependency>
                </dependencies>
            </plugin>
```

## Steps To Reproduce
mvn liquibase:updateSQL

## Actual Behavior
migrate.sql

```sql
  --  Lock Database
UPDATE DATABASECHANGELOGLOCK SET `LOCKED` = 1, LOCKEDBY = 'sunjing (192.168.174.1)', LOCKGRANTED = '2021-01-18 10:38:39.712' WHERE ID = 1 AND `LOCKED` = 0;

--  Changeset database/my21.xml::setColumnRemarks-example::liquibase-docs
ALTER TABLE s_user COMMENT = 'login_fail_counter_test11';

ALTER TABLE s_user COMMENT = 'last_login_fail_time_test22';

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, `DESCRIPTION`, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('setColumnRemarks-example', 'liquibase-docs', 'database/my21.xml', NOW(), 4, '8:3d3e9aaf0a0501e810d9f4de0b4ab9c4', 'setColumnRemarks columnName=login_fail_counter, tableName=s_user; setColumnRemarks columnName=last_login_fail_time, tableName=s_user', '', 'EXECUTED', NULL, NULL, '4.2.2', '0937520901');

--  Release Database Lock
UPDATE DATABASECHANGELOGLOCK SET `LOCKED` = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;
```

```sql
  ALTER TABLE s_user COMMENT = 'login_fail_counter_test11';   is error
```

## Expected/Desired Behavior
right sql  can update column coment

**Comment by molivasdat** [comment] 2021-01-28 04:08
Hi @tofdragon Thanks for reporting this issue.  We are fixing this soon.
This is being fixed in the next release and is a duplicate of https://github.com/liquibase/liquibase/pull/942

**Closed** 2022-09-13 17:23 UTC
Labels: TypeBug, Severity3, ImpactMedium, PRAssociated, DBMySQL, IntegrationAny, sprint2022-31
