### ISSUE TITLE
Too many open file on spring application start

### ISSUE THREAD

**Issue by pmancaux** [liquibase/liquibase#1449] opened 2020-10-02 09:44 UTC
## Environment
**Liquibase Version**:
4.0.0

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
Spring

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:
Postgres 12

**Operating System Type & Version**:
Ubuntu 18.04 or linux with kernel 3.10.0-862.14.4.el7.x86_64 

## Description
When i upgrade from 3.8.1 to 4.0.0 i see Too many open file when i start my application.

What i see is a change in SpringLiquibase when createLiquibase is done. method createResourceOpener in 3.8.1 is 

```
/**
	 * Create a new resourceOpener.
	 */
	protected SpringResourceOpener createResourceOpener() {
		return new SpringResourceOpener(getChangeLog());
	}

```

and in 4.0.0 become :

```
/**
	 * Create a new resourceOpener.
	 */
	protected SpringResourceAccessor createResourceOpener() {
		return new SpringResourceAccessor();
	}
```

The fact is when method DatabaseChangeLog.load is call, espacially this part of code : 

```
for (ParsedNode childNode : parsedNode.getChildren()) {
            handleChildNode(childNode, resourceAccessor);
        }
```

when childNode.nodeName is equal to "include", code is loading/accessing all jar of my application and if i do lsof -p [PID] | wc -l on my system i can see that it pass from 500 to 1200 to 1500 to 2000 very rapidly and at the end of this foreach to 200.

If i come back to 3.8.1 i can see that lsof | wc -l is always equals to 500 and never grow up.

I don't understand why we search in all jar of the application for an include node when relativetochangelog is set to true, we just need to search only in this jar, not all?

## Steps To Reproduce
with liquibase 3.8.1
create à changelog with many include like this :

<include
		file="db.changelog-1.1-postgresql.xml"
		relativeToChangelogFile="true" />

and see lsof -p [PID] | wc -l on the filesystem 

do the same with liquibase 4.0.0 and you will see the difference.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-748) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment] 2020-10-16 02:31
Thank you @pmancaux for writing up this issue.  We will add this to our list of issues to process.

**Comment by pmancaux** [comment] 2020-11-10 08:26
@molivasdat any news about this issue? i m doing upgrade of my lib every 3 month but i can t go to 4.0.0 for now thanks

**Comment by pmancaux** [comment] 2021-02-01 09:34
@molivasdat just for any news if you have :) thanks!

**Comment by ro-rah** [comment] 2021-02-01 16:37
This has been reported in 3.10.3 as well:
https://forum.liquibase.org/t/too-many-open-files-error-when-upgrading-to-3-10-3/5014

**Comment by molivasdat** [comment] 2021-02-01 17:26
Hi @pmancaux and @ro-rah .  I have not had a chance to repro this issue.  If you have a suggested fix, go ahead and open up a PR to suggest a fix.  In the meantime, I'll see if I can track down why the change was made.

**Comment by nvoxland** [comment] 2021-05-21 18:40
Duplicate of #1815

**Comment by nvoxland** [comment] 2021-05-21 18:41
Since this is a duplicate, I'm closing this issue to consolidate tracking and discussion.

**Closed by nvoxland** 2021-05-21 18:41 UTC
Labels: DBPostgres, ImpactMedium, IntegrationSpringboot, Severity3, StatusDiscovery, TypeBug, hacktoberfest
