### ISSUE TITLE
Liquibase errors with a formatting error on sql changelog files when it contains a word property

### ISSUE THREAD

**Issue by jaygeorgeInforma** [liquibase/liquibase#3025] opened 2022-06-30 11:52 UTC
Liquibase fails with formatting error when the sql changelog has a word property in changeset id  or comment or in the SQL. This has stopped working from 4.10 on wards. 4.9.1 works fine. You can reproduce this by running validate on the following changeset.

Here is the sql changelog file I tested 

--liquibase formatted sql

--changeset test:test_property labels:DEV,QA,PROD,ALL context:test
--comment: test1
create table test_property ( abc integer, id integer);
--rollback DROP TABLE test_property

--changeset test:test_property1  labels:DEV,QA,PROD,ALL context:test
--comment:  test2
ALTER TABLE IF EXISTS test_property
    ADD CONSTRAINT fk_test_id FOREIGN KEY (id)
    REFERENCES abc (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

--rollback ALTER TABLE IF EXISTS test_property  DROP constraint fk_test_id

I have tried the following scenarios.

1. If I change the changeset id in the first changeset test_prop it errors on the second changeset
2. It does not work even if I change the changeset id to something other than property. This I think it gets confused with the a word property being there in the table name.
3. If I remove the second changeset altogether along with a change to the changesetid without the word property it works.

The error I get is something like this.

Starting Liquibase at 12:17:15 (version 4.11.0 #2708 built at 2022-05-23 15:17+0000)
Liquibase Version: 4.11.0
Liquibase Community 4.11.0 by Liquibase

Unexpected error running Liquibase: 
Unexpected formatting at line 3. Formatted SQL changelogs require known formats, such as '--property name=<property name> value=<property value>' and others to be recognized and run. Learn all the options at https://docs.liquibase.com/concepts/changelogs/sql-format.html

**Comment by kataggart** [comment] 2022-06-30 13:01
@jaygeorgeInforma thanks for logging this; noting this may be duplicate of issue reported https://github.com/liquibase/liquibase/issues/3017

**Comment by nvoxland** [comment] 2022-09-01 21:54
Yes, this is a duplicate of #3017

**Closed by nvoxland** 2022-09-01 21:54 UTC
Labels: TypeBug, ver4.10.0, formattedSQL
