### ISSUE TITLE
EndDelimiter '/' not working as expected since 4.29

### ISSUE THREAD

**Issue by danielWaschke-kalo-de** [liquibase/liquibase#6150] opened 2024-07-31 09:06 UTC
### Search first

- [X] I searched and no similar issues were found

### Description

We are deploying SQL and PLSQL scripts on an Oracle Database via Liquibase. We use ‘/’ as endDelimiter because it’s compatible with native SQL and PLSQL.

Since 4.29 this is some kind of broken. Before only a single "/" as first and only character of a new line was recognized as endDelimiter. Now also a "/" at the end of a line is interpreted as endDelimiter. This is not compatible with native SQL anymore.

### Steps To Reproduce

Code similar to the following was leading to an error because of false code splitting

```
-- liquibase formatted sql
-- changeset abc:ABC_PROC runOnChange:true stripComments:false endDelimiter:/
-- comment Initial Creation
CREATE OR REPLACE PROCEDURE ABC_PROC…IS
…
BEGIN
…
i := j /
 2;
…
END;
/
```

### Expected/Desired Behavior

"/" should only interpreted as endDelimiter if it's the only character on a new line.

### Liquibase Version

4.29

### Database Vendor & Version

Oracle 19

### Liquibase Integration

CLI

### OS and/or Infrastructure Type/Provider

Docker

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by david-thaler** [comment] 2024-07-31 15:08
This has also broken all of my custom sql written changelogs for MSSQL too.

Before I had my changeset comments like:
```
-- liquibase formatted sql
-- changeset AUTHOR:CHANGESET_NAME endDelimeter:GO rollbackEndDelimiter:GO runAlways:true runOnChange:true dbms:mssql
```

This would allow me to use GO as my delimiter between blocks of sql and semicolons are just used to simply finishing the line sometimes. Since 4.29.0 my changelogs fail because the semicolon ';' is being treated as this "splitStatement" stuff and now one block of sql is being treated as two.

Meaning some code like this does not work for me:
```
declare cursorToProcess cursor local
	read_only forward_only fast_forward
	for
		QUERY HERE;

open cursorToProcess;
```

because the `open cursorToProcess;` is being treated as a separate block and therefore it cannot find a reference to any cursor called cursorToProcess.

I suspected this has something to do with #5359 #5704

**Comment by filipelautert** [comment] 2024-07-31 16:47
Hi @danielWaschke-kalo-de and @david-thaler  - could any of you confirm that this was working on 4.28.0 ? Thanks!

**Comment by david-thaler** [comment] 2024-07-31 17:03
Yes I can confirm it was working on 4.28.0. Our ci/cd pipeline always pulls the latest cli. This is how it was discovered for us.






---- On Wed, 31 Jul 2024 17:48:20 +0100 ***@***.*** wrote ----



Hi @danielWaschke-kalo-de and @david-thaler - could any of you confirm that this was working on 4.28.0 ? Thanks!

**Comment by filipelautert** [comment] 2024-07-31 17:24
We tried to reproduce it using the following SQL, but it's working:
```
-- liquibase formatted sql
-- changeset abc:ABC_PROC runAlways:true stripComments:false endDelimiter:/
-- comment Initial Creation
CREATE OR REPLACE PROCEDURE "PROC_HELLO_WORLD" AS
       i number;
     j number := 0;
BEGIN
  DBMS_OUTPUT.PUT_LINE('Hello  World!');
  i := j /
    2;
END PROC_HELLO_WORLD;
/
```

Am I missing something ?

**Comment by filipelautert** [comment] 2024-07-31 18:30
@david-thaler in your example it is typed `endDelimeter:GO` instead of `endDelimiter:GO` . It it a real problem or it just happened when you typed in github issue?

**Comment by filipelautert** [comment] 2024-07-31 18:33
@danielWaschke-kalo-de could you check if adding splitStatements:false fixes your issue?

**Comment by david-thaler** [comment] 2024-07-31 18:59
@filipelautert I've tried with i and e in delimiter and neither have worked.

**Comment by filipelautert** [comment] 2024-07-31 19:08
Thanks! If I create a PR reverting https://github.com/liquibase/liquibase/pull/5704 would you be able to test the artifacts? Then if it's confirmed that this PR is the root cause we can fix it.

**Comment by david-thaler** [comment] 2024-07-31 19:13
I can try, haven't built liquibase from source before.

**Comment by danielWaschke-kalo-de** [comment] 2024-08-01 06:12
> Hi @danielWaschke-kalo-de and @david-thaler - could any of you confirm that this was working on 4.28.0 ? Thanks!

Yes, I switched back to 4.28 and it was working again

> Am I missing something ?
I simplified my example and hoped it would behave the same as our production code. 

If necessary I could provide the original source code via personal message/mail...

**Comment by david-thaler** [comment] 2024-08-01 07:02
If the original bug is going to be marked as resolved please let me know and I'll raise my issue separately @filipelautert

**Comment by filipelautert** [comment] 2024-08-01 13:16
Hi @danielWaschke-kalo-de @david-thaler - are you able to test artifact from PR #6157 ? You can download the zip from here: https://github.com/liquibase/liquibase/actions/runs/10197263496/artifacts/1764459791 .
@danielWaschke-kalo-de if you could send me the files at flautert [at} liquibase.org it would be great, thanks!

**Comment by david-thaler** [comment] 2024-08-01 14:04
@filipelautert still not working for me:

```
####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ##
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ##
##                                                ##
####################################################
Starting Liquibase at 15:00:25 using Java 21.0.2 (version [Core: liquibase/liquibase/fix-sql-enddelimeter-issues/8363/03dc29/2024-08-01 11:21:03 UTC, Pro: master/8800/8ac2fa/2024-07-29 17:44:14] #8363 built at 2024-08-01 11:21:03 UTC)
Liquibase Version: [Core: liquibase/liquibase/fix-sql-enddelimeter-issues/8363/03dc29/2024-08-01 11:21:03 UTC, Pro: master/8800/8ac2fa/2024-07-29 17:44:14]
Liquibase Open Source [Core: liquibase/liquibase/fix-sql-enddelimeter-issues/8363/03dc29/2024-08-01 11:21:03 UTC, Pro: master/8800/8ac2fa/2024-07-29 17:44:14] by Liquibase
Running Changeset: PATH.sql::CHANGESET_ID::AUTHOR
Running Changeset: PATH.sql::CHANGESET_ID::AUTHOR
Running Changeset: PATH.sql::CHANGESET_ID::AUTHOR
Running Changeset: PATH.sql::CHANGESET_ID::AUTHOR

UPDATE SUMMARY
Run:                          3
Previously run:             550
Filtered out:                 0
-------------------------------
Total change sets:         1313

ERROR: Exception Details
ERROR: Exception Primary Class:  SQLServerException
ERROR: Exception Primary Reason:  A cursor with the name 'cursorToProcess' does not exist.
ERROR: Exception Primary Source:  Microsoft SQL Server 16.00.1121

Unexpected error running Liquibase: Migration failed for changeset PATH.sql::CHANGESET_ID::AUTHOR:
     Reason: liquibase.exception.DatabaseException: A cursor with the name 'cursorToProcess' does not exist. [Failed SQL: (16916) open cursorToProcess;]

For more information, please use the --log-level flag
```

**Comment by filipelautert** [comment] 2024-08-01 14:27
@david-thaler are you able to send me those 3 changes at the e-mail I posted above? Seems the problem is somewhere else...

**Comment by tati-qalified** [comment] 2024-08-01 14:29
Hi guys, I tested the code you both provided, but it worked for me with no issues. 

@danielWaschke-kalo-de I tested your code with no modifications and it ran. The procedure was created as expected:
![image](https://github.com/user-attachments/assets/72447176-2f1e-4598-a103-ef0ea7defd79)
Maybe providing the error logs could help us determine the source of the error.

---

@david-thaler I tested the changeset you provided but changing `endDelimeter` to `endDelimiter` and it worked for me with no issues, using the released 4.29 version.

This is also reflected when running `update-sql`:
**delimEter:**
```
-- Changeset mssql.sql::CHANGESET_NAME::AUTHOR
declare cursorToProcess cursor local
	read_only forward_only fast_forward
	for
		QUERY HERE;
GO

open cursorToProcess;
GO
```

**delimiter**
```
-- Changeset mssql.sql::CHANGESET_NAME::AUTHOR
declare cursorToProcess cursor local
	read_only forward_only fast_forward
	for
		QUERY HERE;

open cursorToProcess;
GO
```

I used a simple `select` query and the changelog ran: 
![image](https://github.com/user-attachments/assets/40b57d0a-2a12-464b-97be-d7dbf2dfb044)


Is there any more information you could provide that would change the settings / process?


Thank you both,
Tatiana

**Comment by danielWaschke-kalo-de** [comment] 2024-08-02 07:22
Hi @tati-qalified sorry, I did not test my example code. Nontheless our production code is still failing with a similar constellation (Liquibase 4.29.1).

I just mailed the original code and log file to @filipelautert.

**Comment by david-thaler** [comment] 2024-08-02 08:15
@filipelautert file that is failing has been sent to you as requested.

**Comment by filipelautert** [comment] 2024-08-06 19:19
@danielWaschke-kalo-de could you confirm that the artifacts from PR #6150 (you can download the zip here: https://github.com/liquibase/liquibase/actions/runs/10272189479/artifacts/1782543791 ) fixes your issue?

**Comment by danielWaschke-kalo-de** [comment] 2024-08-07 05:51
hi @filipelautert, I can confirm that our code is compiled as expected with the fix version!

**Comment by david-thaler** [comment] 2024-08-21 13:57
Just making a note to keep this alive as my issue still exsists.

**Comment by filipelautert** [comment] 2024-10-01 14:07
@david-thaler as discussed I'm closing this issue as you managed to workaround it. Thanks!

**Closed by filipelautert** 2024-10-01 14:07 UTC
Labels: TypeBug, triage, TypeSupport
