### ISSUE TITLE
Liquibase mongodb commercial Jar is not working with mongodb atlas

### ISSUE THREAD

**Issue by gkulkarni-qt** [liquibase/liquibase#5496] opened 2024-01-23 07:35 UTC
### Search first

- [X] I searched and no similar issues were found

### Description

Hi Liquibase Team,

We have trial license liquibase and we are testing the liquibase pro functionality with mongodb pro extension with native mongodb scripts as changesets and we are using liquibase as docker image only as it is easily shippable across.

**Changelog.js**
// liquibase formatted mongodb
// changeset guru:1 runWith:mongosh
db.createCollection('employees');
// rollback db = db.employees.drop()

liquibase.docker.properties file
liquibase.command.url: mongodb+srv://<cluster-dns-name>/company
liquibase.command.username: liquibase_test
liquibase.command.password: <password>
liquibase.command.changelog-file: /liquibase/changelog/changelog.js
liquibase.command.classpath: /liquibase/liquibase_libs/liquibase-commercial-mongodb-1.3.0.jar
liquibase.licenseKey: <license key>

**Docker file for liquibase**
FROM liquibase/liquibase
RUN lpm add liquibase-commercial-mongodb@1.3.0

**Docker command executed** 
 docker run --rm -v /root/liquibase:/liquibase/changelog liquibase/liquibase-mongodb-pro-guru1 --defaults-file=/liquibase/changelog/liquibase.docker.properties --log-level=debug update

When we run the liquibase its giving the following error
Unexpected error running Liquibase: The changelog '/liquibase/changelog/changelog.js' contains invalid formatting at line 1. Formatted Mongodb changelogs require specific elements, such as '// liquibase formatted mongo' to be recognized and run. Learn more at https://docs.liquibase.com/mongodb.

FYI - we are using mongodb atlas as our database and we want to move ahead and purchase license from liquibase if we get the resolution

### Steps To Reproduce

Execute the commands specified above 

### Expected/Desired Behavior

It should run the update query whereas, its giving an error that its not in the right format.

### Liquibase Version

latest

### Database Vendor & Version

mongodb atlas

### Liquibase Extensions

liquibase-mongodb-commercial:1.3.0

### OS and/or Infrastructure Type/Provider

Debian GNU/Linux

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment] 2024-03-04 13:52
Hi @gkulkarni-qt, thank you for reporting this issue.
I've been able to replicate the bug using the liquibase-commercial-mongodb extension and a MongoDB Atlas instance.
Using MongoDB without Atlas, through a Docker instance, works as expected.

Here are the steps to reproduce:

**1.** Create a cluster in MongoDB Atlas
**2.** Set up your `liquibase.docker.properties` and `changelog.js` files
**3.** Build your Docker image:
Dockerfile:
```
FROM liquibase/liquibase
RUN lpm add liquibase-commercial-mongodb@1.3.0 --global
```
Command: `docker build -t imageName .`

**4.** Run Liquibase
Command: `docker run -v <path>:/liquibase/changelog imageName --defaults-file=/liquibase/changelog/liquibase.docker.properties update`

_________________________________

I'll be forwarding this to our development team so they can look into it.

Thank you,
Tatiana

**Comment by jbennett-liquibase** [comment] 2024-03-04 20:47
Hi @tati-qalified @gkulkarni-qt can you ensure you are invoking docker with a search path? If you are mounting to /liquibase/changelog it would look something like this:

`docker run --env LIQUIBASE_SEARCH_PATH=/liquibase/changelog ...`

**Comment by tati-qalified** [comment] 2024-03-11 16:29
I was using `classpath`, but not `search-path`, but according to the [docs](https://docs.liquibase.com/concepts/changelogs/how-liquibase-finds-files.html) this should be enough:

> Default locations based on how you run Liquibase
     CLI: the current working directory where Liquibase commands are running, plus everything in your LIQUIBASE_HOME/lib and liquibase_libs directories, plus the classpath setting

Can this be a bug?

**Comment by Tylorjg** [comment] 2024-03-21 19:08
The error message itself is misleading. The root cause of the issue is the file cannot be found.

I was able to replicate this error in Docker and also found the same behavior occurs with the Liquibase CLI. If a changelog file that doesn't exist (or can't be found) is given to the Liquibase Pro Mongo extension, it will fail with the `contains invalid formatting at line 1` error with normal logging. Setting the `--log-level=fine`, the log shows there is another error that occurs which is the `java.io.FileNotFoundException` for the changelog. 

@gkulkarni-qt , can you please email support@liquibase.com with this issue as this is a Pro feature, so we can work with you directly to get this working? If you can email us with your company email that would be appreciated. If you are unable to, you can use your normal email.

As @jbennett-liquibase noted, you will need to have the /liquibase/changelog set in the **search path** and **mongosh installed** on the docker container also for it to pick up the changelog file.

@tati-qalified, it appears that the classpath isn't being picked up as a location to search for the changelog. I tested by adding /liquibase/changelog to the classpath, and it still ran into the same error message. If the docs state that the classpath should be searched and it was previously worked that way, then that would be a bug.

**Comment by jbennett-liquibase** [comment] 2024-03-21 19:41
@Tylorjg @tati-qalified the classpath definition was removed from the Liquibase properties file used by Docker.
https://github.com/liquibase/docker/commit/0bf484df47833931195ce9ed98fced825d525391

**Comment by gkulkarni-qt** [comment] 2024-03-26 15:11
Hi @Tylorjg ,

Yes its a bug in the liquibase code i was able to reproduce the same please find the screenshot that the error is misleading
![Screenshot 2024-03-26 at 8 40 57 PM](https://github.com/liquibase/liquibase/assets/127286426/ae32810f-14d5-4e8d-b987-021d7123b4b8)

**Comment by filipelautert** [comment] 2024-07-19 14:31
Hi! this was fixed on https://github.com/liquibase/liquibase-commercial-mongodb/pull/241 and in docker image too.
Please reopen if the problem persists.

**Closed by filipelautert** 2024-07-19 14:31 UTC
Labels: TypeBug, DBMongoDB, needs_review
