### ISSUE TITLE
Error "Incorrect syntax near ‘GO’" on SQL Server when a changelog contains multiple inserts with Nvarchar strings with backward slashes

### ISSUE THREAD

**Issue by peter17ji** [liquibase/liquibase#5455] opened 2024-01-11 08:02 UTC
### Search first

- [X] I searched and no similar issues were found

### Description

This changelog can be executed without exception on Liquibase 4.9.1, but it emits "Incorrect syntax near ‘GO’" in Liquibase 4.25.1.

Liquibase version: org.liquibase:liquibase-core:4.25.1 as Maven dependency
Liquibase runs on: Win10 19044, redhatopenjdk-11
JDBC driver: com.microsoft.sqlserver:mssql-jdbc:11.2.0.jre11

### Steps To Reproduce

```TSQL
-- liquibase formatted sql
-- changeset TestAuthor:R00001.01 context:R00001.01.0101 endDelimiter:GO dbms:mssql stripComments:false SplitStatements:true
-- comment: An edge case on Liquibase 4.25.1 where 2 insert statements with slashes in nvarchar string will break Liquibase grammar scanner

use DB1
go
create table DB1.dbo.template_document_map
(
    Template_Document_Path nvarchar(500)
)
go
INSERT [dbo].[template_document_map] ([Template_Document_Path]
                                      )
values ( N'C:\path\to\The_File\File.html')
go
INSERT [dbo].[template_document_map] ([Template_Document_Path]
                                      )
values ( N'C:\path\to\The_File2\File2.html')
go

```

### Expected/Desired Behavior

No exception should occur, and changelog should be executed successfully.

### Liquibase Version

4.25.1

### Database Vendor & Version

Microsoft SQL Server 15.00.4335，AWS managed RDS

### Additional Context

Issue #3687 has similar exception, but with a different pattern. Better leave to dev to investigate if they're related.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment] 2024-01-17 15:50
Hi @peter17ji, thank you for reporting this issue. I can confirm that this is replicable for Liquibase version 4.25.1, but I've found a few workarounds that might help for now.

1. Separate each `insert` statement into different changesets
2. Insert the data in a single statement, using the syntax `insert into tableName (col1, col2) values (val1,val2),(val3,val4),(...)`
3. Use double backslashes, though it will affect the value that's saved on the database

Considering point 3, it seems to be related to [escaping characters in Java](https://codegym.cc/groups/posts/escaping-characters-java), though I'm not sure if it's a Liquibase error or an MSSQL error.

I'll be forwarding this to the dev team so they can look into it.

Thank you,
Tatiana

**Comment by MalloD12** [comment] 2024-04-04 21:40
I tried with the same changelog and couldn't reproduce this issue. It was successfully deployed, see below:  
![insertChangelogSuccessfullyExecuted](https://github.com/liquibase/liquibase/assets/75833793/3a3db5c1-3c50-4214-b925-78a33c573399)

I think the reason for this working now could be related to this [PR](https://github.com/liquibase/liquibase/pull/5700) we recently merged. I'll close this issue for now, but feel free to try it on your own and if it's still an issue for you we would appreciate you could share some additional details. 

Thanks,
Daniel.

**Closed by MalloD12** 2024-04-04 21:40 UTC
Labels: TypeBug, DBMSSQLServer, needs_review, sql-parsing
