### ISSUE TITLE
PostgreSQL 12 Support

### ISSUE THREAD

**Issue by raja-hm** [liquibase/liquibase#1482] opened 2020-10-15 12:46 UTC
As mentioned in the forum https://forum.liquibase.org/t/postgresql-12-support/4468 liquibase fails with error column adsrc not found in postgres version 12.x

## Environment
**Liquibase Version**: **Please update**

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.> **Please update**

**Liquibase Extension(s) & Version**: **Please update**

**Database Vendor & Version**: PostgreSQL 12

**Operating System Type & Version**: **Please update**

## Description (Please update)
A clear and concise description of the issue being addressed.

* Describe the actual problematic behavior.
* Ensure private information is redacted.

## Steps To Reproduce (Please update)
Please update
List the steps to reproduce the behavior.

* Please be precise and ensure private information is redacted
* Include things like
  * Files used - sql scripts, changelog file(s), property file(s), config files, POM Files
  * Exact commands used - CLI, maven, gradle, spring boot, servlet, etc.

## Actual Behavior (Please update)
A clear and concise description of what happens in the software **before** this pull request.

* Include console output if relevant
* Include log files if available.

## Expected/Desired Behavior (Please update)
A clear and concise description of what happens in the software **after** this pull request.

**Comment by molivasdat** [comment] 2020-10-15 15:36
Hi @raja-hm Thanks for taking the time to report this as requested.  Can you fill in the additional info that I have added to the description section?

**Comment by MarkusLutum** [comment] 2021-01-05 11:45
Same issue here. 
Fails on a simple precondition check
`<changeSet id="drop_duplicate_pi_index" author="markuslutum">
    <preConditions onFail="MARK_RAN">
      <indexExists indexName="sk_myindex" />
    </preConditions>
    <dropIndex tableName="thetable" indexName="sk_myindex" />
  </changeSet>`

**Comment by molivasdat** [comment] 2021-01-05 17:03
Hi @MarkusLutum Thanks for the update which version of Liquibase are you using? And is this for PostgreSQL v12 as well?

Hi @raja-hm - Can you update the Description section.  I checked the forum and did not find the version of Liquibase you are using to test your upgrade to PG 12.

**Comment by sudo-cody** [comment] 2021-02-02 12:39
@molivasdat I can confirm what @MarkusLutum said: fails on postgres 12.2 and 13.1 (installed on MacOS with homebrew).

**Comment by sumitbhardwaj** [comment] 2021-02-11 14:02
is there a plan to fix this issue?

**Comment by molivasdat** [comment] 2021-02-11 18:31
Hi @sumitbhardwaj Which version of Liquibase were you using when this error occurred?

**Comment by sumitbhardwaj** [comment] 2021-02-12 06:06
we eare using version 3.2.2

**Comment by MarkusLutum** [comment] 2021-02-12 16:25
We are also using an old version. 2.0.5 with some incompatible own features so an easy upgrade is not possible. Thats also why I have not tested this with the newest version. Could be that its fixed there already

**Comment by molivasdat** [comment] 2021-02-13 00:06
Hi @sumitbhardwaj and @MarkusLutum I cannot recreate the error that you are seeing with the information that was shared. PG12 should be working with the latest version of Liquibase.  We are not going to be able to fix this on 3.2.2(circa 2014) or 2.0.5(circa 2012)  because we are focusing on newer editions of Liquibase to be able to provide quicker turnaround and more features on a smaller number of releases.  If you find a bug in the latest release, please open an issue and/or PR to fix and we will process it as quick as we can.

Here are the changesets that I ran against PG11.7 and PG12.6 using liquibase cli v4.2.2
```
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:pro="http://www.liquibase.org/xml/ns/pro" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-4.1.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.1.xsd">

<changeSet author="mikeo" id="pg12-1">
    <preConditions onFail="MARK_RAN">
        <not>
            <tableExists tableName="mytable" />
        </not>
    </preConditions>

    <createTable tableName="mytable">
        <column name="id" type="INT" >
            <constraints primaryKey="true" />
        </column>
        <column name="C1" type="INT" />
        <column name="C2" type="VARCHAR(64)" />
        <column name="C3" type="VARCHAR(64)" />
        <column name="C4" type="DATETIME" />
    </createTable>
</changeSet>
<changeSet author="mikeo" id="1_createIndex">
<createIndex indexName="mytable_index" tableName="mytable">
      <column name="id"/>
      <column name="C1"/>
  </createIndex>
 </changeSet>	

<changeSet id="drop_index" author="mikeo"> 
<preConditions onFail="MARK_RAN"> 
<indexExists indexName="mytable_index" /> 
</preConditions> 
<dropIndex tableName="mytable" indexName="mytable_index" />
 </changeSet>
</databaseChangeLog>
```

**Comment by sumitbhardwaj** [comment] 2021-02-24 08:16
@Mike,

Thanks. I am trying with latest version of the liquibase now. I am facing
one issue if you can help me or direct me to some article.

We create a war for our project and keep all the changes sets and xsd files
in a changeset folder inside the war. It used to work fine in older
releases of liquibase(3.2.2). with latest release it's not able to find the
xsd from the war, and I have to copy it to tomcat bin directory for it to
work correctly.

If I dont copy dbchangelog-4.3.xsd in tomcat bin/changesets folder, I get
the following exception. With 3.2.2 it used to work fine.

Can you help?











































*  Caused by: java.io.FileNotFoundException:
D:\tools\apache-tomcat-9.0.38\bin\changesets\dbchangelog-4.3.xsd (The
system cannot find the path specified) at
java.io.FileInputStream.open0(Native Method) ~[?:?] at
java.io.FileInputStream.open(FileInputStream.java:219) ~[?:?] at
java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?] at
java.io.FileInputStream.<init>(FileInputStream.java:112) ~[?:?] at
sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
~[?:?] at
sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184)
~[?:?] at
org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
~[xercesImpl-2.11.0.jar:?] at
org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown
Source) ~[xercesImpl-2.11.0.jar:?] at
org.apache.xerces.impl.xs.opti.SchemaParsingConfig.parse(Unknown Source)
~[xercesImpl-2.11.0.jar:?] at
org.apache.xerces.impl.xs.opti.SchemaParsingConfig.parse(Unknown Source)
~[xercesImpl-2.11.0.jar:?] at
org.apache.xerces.impl.xs.opti.SchemaDOMParser.parse(Unknown Source)
~[xercesImpl-2.11.0.jar:?] at
org.apache.xerces.impl.xs.traversers.XSDHandler.getSchemaDocument(Unknown
Source) ~[xercesImpl-2.11.0.jar:?] at
org.apache.xerces.impl.xs.traversers.XSDHandler.parseSchema(Unknown Source)
~[xercesImpl-2.11.0.jar:?] at
org.apache.xerces.impl.xs.XMLSchemaLoader.loadSchema(Unknown Source)
~[xercesImpl-2.11.0.jar:?] at
org.apache.xerces.impl.xs.XMLSchemaValidator.findSchemaGrammar(Unknown
Source) ~[xercesImpl-2.11.0.jar:?] at
org.apache.xerces.impl.xs.XMLSchemaValidator.handleStartElement(Unknown
Source) ~[xercesImpl-2.11.0.jar:?] at
org.apache.xerces.impl.xs.XMLSchemaValidator.startElement(Unknown Source)
~[xercesImpl-2.11.0.jar:?] at
org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElementAfterName(Unknown
Source) ~[xercesImpl-2.11.0.jar:?] at
org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown
Source) ~[xercesImpl-2.11.0.jar:?] at
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown
Source) ~[xercesImpl-2.11.0.jar:?] at
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown
Source) ~[xercesImpl-2.11.0.jar:?] at
org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
~[xercesImpl-2.11.0.jar:?] at
org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
~[xercesImpl-2.11.0.jar:?] at
org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
~[xercesImpl-2.11.0.jar:?] at
org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
~[xercesImpl-2.11.0.jar:?] at
org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
~[xercesImpl-2.11.0.jar:?] at
liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:88)
~[liquibase-core-4.3.1.jar:?] at
liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:15)
~[liquibase-core-4.3.1.jar:?] at
liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:366)
~[liquibase-core-4.3.1.jar:?] at
liquibase.Liquibase.lambda$update$1(Liquibase.java:229)
~[liquibase-core-4.3.1.jar:?] at
liquibase.Scope.lambda$child$0(Scope.java:160)
~[liquibase-core-4.3.1.jar:?] at liquibase.Scope.child(Scope.java:169)
~[liquibase-core-4.3.1.jar:?] at liquibase.Scope.child(Scope.java:159)
~[liquibase-core-4.3.1.jar:?] at liquibase.Scope.child(Scope.java:138)
~[liquibase-core-4.3.1.jar:?] at
liquibase.Liquibase.runInScope(Liquibase.java:2322)
~[liquibase-core-4.3.1.jar:?] at
liquibase.Liquibase.update(Liquibase.java:216)
~[liquibase-core-4.3.1.jar:?] at
liquibase.Liquibase.update(Liquibase.java:202)
~[liquibase-core-4.3.1.jar:?] at
liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:322)
~[liquibase-core-4.3.1.jar:?] at
liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:275)
~[liquibase-core-4.3.1.jar:?] at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1765)
~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE] at
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1702)
~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE] ... 60 more*
Best
Sumit

**Comment by molivasdat** [comment] 2021-02-24 13:21
Hi @sumitbhardwaj When you say 
"
We create a war for our project and keep all the changes sets and xsd files
in a changeset folder inside the war. It used to work fine in older
releases of liquibase(3.2.2). with latest release it's not able to find the
xsd from the war, and I have to copy it to tomcat bin directory for it to
work correctly.
"
What directory structure are you using to package up the war file?
How are you calling Liquibase to make your database updates in that war file?

And before you were copying the xsd files into a changeset directory?

**Comment by sumitbhardwaj** [comment] 2021-02-24 14:07
Hi Mike,

This is our directory structure for 3.2.2. Yes we are calling changesets
inside the war file for database updates. For 4.3, I made the changes to
use xsds for 4.3

Best
Sumit

[image: Liquibase3.2.2.png]

**Comment by molivasdat** [comment] 2021-02-24 15:38
Hi @sumitbhardwaj Sorry the image did not come through in GitHub of the directory structure.
Also , how are you running liquibase updates?
Are you using ./liquibase --url ... update?
Are you running java -jar liquibase.jar?
Is it running by having it in your pom.xml file?

**Comment by sumitbhardwaj** [comment] 2021-02-24 16:03
Hi Mike,

Let me explain how the setup is done and how it's structured.

Ours is spring based web app and we have defined a spring bean for liquibase

 
<bean id="liquibase"
class="liquibase.integration.spring.SpringLiquibase">
<property name="dataSource" ref="dataSource" />
<property name="changeLog"
value="classpath:*sql/liquibase/*changelog.xml" />


<property name="contexts" value="production" />
</bean>



and this is how our changelog.xml looks like

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:xsi="
http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
dbchangelog-4.3.xsd
http://www.liquibase.org/xml/ns/dbchangelog-ext dbchangelog-ext.xsd">

<include file="changesets/a_pre_init_check.xml"
relativeToChangelogFile="true"/>
.....
.......
  </databaseChangeLog>


All the changeset xmls are inside the *sql/liquibase/changesets* directory
along with the xsds in the war.

The liquibase scripts are run on the application startup.

Here is a sample changeset as well

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<databaseChangeLog
xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
dbchangelog-4.3.xsd
    http://www.liquibase.org/xml/ns/dbchangelog-ext dbchangelog-ext.xsd">

<changeSet
logicalFilePath="x1.xml"
author="Abc xyz" id="y1">
.....
</changeSet>
</databaseChangeLog>


I hope I am able to make it clear, please let me know if you need any mode
details.


Best
Sumit

**Comment by sumitbhardwaj** [comment] 2021-03-01 12:26
Hi Mike,

Please let me know if you have any suggestions for resolving this.

Best
Sumit

**Comment by molivasdat** [comment] 2021-03-02 15:20
Hi @sumitbhardwaj 
Rather that copying down the xsd files yourself, all xsd files are in the liquibase.jar file that is in your war file and should be found locally when using http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.3.xsd as the location in your changelog file.
So changing your xsi schema locations from local 
xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog dbchangelog-4.3.xsd
to this 
xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.3.xsd
should fix that

**Comment by sumitbhardwaj** [comment] 2021-03-03 03:46
Thanks a lot Mike!

Best
Sumit

**Comment by nvoxland** [comment] 2021-12-03 20:14
The current code is no longer using the `adsrc` column for any version of postgreql anymore when snapshotting sequences.

So this should no longer be an issue in current releases.

**Closed by nvoxland** 2021-12-03 20:14 UTC
Labels: StatusDiscovery, DBPostgres, GStatusAddtionalInfo
