### ISSUE TITLE
Community Request: nobanner cli flag for CLI

### ISSUE THREAD

**Issue by kataggart** [liquibase/liquibase#2681] opened 2022-03-24 19:49 UTC
## Environment

**Liquibase Version**: future (does not need to be backwards supported)

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: N/A

**Database Vendor & Version**: all

**Operating System Type & Version**:  all

## Description
Add a cli flag (--nobanner) to suppress the Liquibase banner. This introduces a lot of unneeded noise when running via scripts or CI/CD.

Originally suggested by Priest, via Ideas Portal
https://liquibase.productboard.com/portal/1-liquibase-idea-portal/tabs/c8c192ee-dbc3-4a61-acf4-c5ded58c0988/features/12485670/portal/expanded?utm_medium=social&utm_source=portal_share

## Expected/Desired Behavior
running command via CLI produces all standard/current outputs except the Liquibase banner

**Comment by jimpriest** [comment] 2022-05-05 15:19
This may be a dupe of #1561

**Closed** 2022-05-31 15:18 UTC
Labels: TypeEnhancement
