### ISSUE TITLE
[V4.25.0] CreateViewGenerator issue

### ISSUE THREAD

**Issue by adamjones0101** [liquibase/liquibase#5353] opened 2023-12-11 22:43 UTC
### Search first

- [X] I searched and no similar issues were found

### Description

CreateViewGenerator.generateSql is not creating the correct SQL when isFullDefinition is false and replaceIfExists is true.

Code should read something like this around line 81:

.prepend("VIEW")
.prepend(" ");
if (statement.isReplaceIfExists()) {
   viewDefinition.prepend("CREATE OR REPLACE");
}
else {
   viewDefinition.prepend("CREATE");
}

### Steps To Reproduce

use fullDefinition false and replaceIfExists true on a view that exists

### Expected/Desired Behavior

SQL should be CREATE OR REPLACE

### Liquibase Version

4.25.0

### Database Vendor & Version

Oracle 19.3

### Additional Context

Oracle 19.3

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kevin-atx** [comment] 2023-12-17 20:29
@adamjones0101 - thank you for this issue. Since you already identified the code that would need to change, would you be willing to submit the change as a PR?

**Comment by adamjones0101** [comment] 2023-12-18 15:54
I could.  I had to make a little more change to CreateViewGenerator.java to get it to work right.  However, I have not been able to fully test our changesets because of https://github.com/liquibase/liquibase/issues/5359 which is a serious regression.  Therefore I hesitate to submit the PR at this time.

**Comment by adamjones0101** [comment] 2024-01-02 21:43
I do not have a Git environment from which I can create a PR, I only download the zip, build it and use it within our product.
However, I am attaching my changed file for anybody to review and push
[CreateViewGenerator.zip](https://github.com/liquibase/liquibase/files/13814103/CreateViewGenerator.zip)

**Comment by MalloD12** [comment] 2024-01-18 18:29
Hi @adamjones0101,

I think this issue could have already been fixed by #5304. Would you mind trying on the latest liquibase version? 

Thanks,
Daniel.

**Comment by adamjones0101** [comment] 2024-01-19 12:27
It's not a high priority because we are still blocked by Issue 5359.  In fact we are considering using Version 4.15.0 with the hope that the issue had not yet been introduced.

**Comment by MalloD12** [comment] 2024-01-22 18:51
If it becomes something required to fix, could you please expand a little bit more on the steps performed to reproduce this issue? Which command were you trying to execute when you faced this issue, changelog example, etc? If you were trying to execute a `generate-changelog` or `diff` command I would recommend you to try with latest version when you have some time.

Thanks,
Daniel.

**Comment by lbadam** [comment] 2024-08-28 16:06
I'm going to close this issue as possibly fixed by #5304 in a more recent version. If this issue persists, please reopen 👍

**Closed by lbadam** 2024-08-28 16:06 UTC
Labels: TypeBug, DBOracle, awaiting_response

**Comment by adamjones0101** [comment] 2024-08-28 18:47
Thanks.  Having this fix is good.  Unfortunately it isn't sufficient for us
because we have over 600 createView replaceIfExists changesets with SQL
that starts like this:
    -- CREATE OR REPLACE VIEW VIEWNAME_XXX AS
It may have been done as a pseudo comment, I don't know but because the
query already contains CREATE OR REPLACE, CreateViewGenerator doesn't think
it needs to make any changes.
I replaced the check with this:
if (viewDefinition.contains("CREATE") {
    viewDefinition.replace("CREATE", "CREATE OR REPLACE");
}
and this resolves our issue.
