### ISSUE TITLE
setColumnRemarks incorrectly changes the table comment on MariaDB

### ISSUE THREAD

**Issue by stevenpaligo** [liquibase/liquibase#1330] opened 2020-08-18 21:22 UTC
## Environment
**Liquibase Version**: 3.8.0

**Liquibase Integration & Version**: Spring Boot 2.2.2.RELEASE

**Liquibase Extension(s) & Version**: N/A

**Database Vendor & Version**: MariaDB 10.4.7

**Operating System Type & Version**: Debian 10

## Description
When using the `setColumnRemarks` feature with MariaDB, the table comment is altered instead of the column comment.

## Steps To Reproduce
Create and run a change set similar to the following: `<setColumnRemarks tableName="my_table" columnName="id"                           remarks="ID of the row"/>`

## Actual Behavior
The table comment is changed instead of the column comment. The following SQL is generated: `ALTER TABLE my_db.my_table COMMENT = 'ID of the row'`

## Expected/Desired Behavior
I expect that the column comment would be changed and the table comment remains intact.

## Screenshots (if appropriate)
N/A

## Additional Context
N/A

**Comment by stevenpaligo** [comment] 2020-08-18 21:32
I just verified this is not fixed as of 3.10.2

**Comment by stevenpaligo** [comment] 2020-08-18 21:51
I can't verify whether or not it works in 4.0.0 because I am using Spring Boot and running into issue #1276

**Comment by molivasdat** [comment] 2020-08-26 13:39
Hi @stevenpaligo Thanks for writing up this issue.  I believe there is another is that is related or the same.
https://github.com/liquibase/liquibase/issues/1210. Could you take a look and see if this the same?? If so, we'll make sure both mysql and MariaDB get fixed with that one.

**Comment by FBurguer** [comment] 2022-08-22 13:40
As mentioned on issue [#1210](https://github.com/liquibase/liquibase/issues/1210) it looks like it got fixed by PR #2752. Try upgrading liquibase to that version or our latest (`4.15 `). If the issue is not fixed for you, try re-opening the issue and will take a second look into it. Thanks!

**Closed by FBurguer** 2022-08-22 13:40 UTC
Labels: TypeBug, Severity3, DBMariaDB, IntegrationSpringboot, hacktoberfest
