### ISSUE TITLE
Could I separate sql statements in DDL and DML?

### ISSUE THREAD

**Issue by cnotario** [liquibase/liquibase#1055] opened 2020-03-25 13:19 UTC
**Description**
I would like to separate sql statements in DDL type and DML type from the same file .xml. I checked the documentation and I didn't find a feature for this. I checked the extensions too.
I would like know whether liquibase could do it or if I would have to do it ad-hoc. Thanks for your support!

**To Reproduce**
- mvn clean liquibase:updateSQL
- separate statements DML or DDL
- migrate.sql is generated

**Expected behavior**
Example migrate1DML.sql

INSERT ....

UPDATE ....

DELETE

Example migrate2DDL.sql

CREATE 

DROP

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-166) by [Unito](https://www.unito.io/learn-more)

**Comment by SteveDonie** [comment] 2020-03-25 21:25
You haven't include your master changelog, but the issue is likely that you need to add the attributes `splitStatements=TRUE` and `endDelimiter=;` (or whatever statement delimiter you are using in the SQL files) to the `<sql>` changes in your master changelog.

In the future, please include the changelog (or a representative subset of it) and the actual SQL being used and what is expected.

**Comment by cnotario** [comment] 2020-03-30 07:09
My changelog.xml example

<?xml version="1.0" encoding="utf-8"?>
<databaseChangeLog
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.4.xsd" objectQuotingStrategy="QUOTE_ALL_OBJECTS">



    <changeSet id="data" author="xxxx" dbms="postgresql">

        
        <update tableName="TB_GENERIC_LOADER">
            <column name="PARSER" type="character varying" value="itemNum1:2;itemLngStr1:4;itemLngStr2:5;itemAmount1:6;itemAmount2:7;itemCode1:8;itemCode2:9;itemCode3:10;itemStr1:11;itemDate1:12;itemDate2:13;itemDate3:14;itemDate4:15;itemLngStr3:16;itemLngStr4:17;itemLngStr5:18;itemStr2:19;itemCode4:20;itemCode5:21;itemStr3:22;itemCode6:23;itemLngStr6:24;itemLngStr7:25;itemLngStr8:26;itemLngStr9:27;itemDate5:28;itemAmount3:29;itemAmount4:30;itemAmount5:31;itemStr4:32;itemStr5:33;itemStr6:34;itemStr7:35;itemStr8:36;itemStr9:37;itemCode7:38;itemCode8:39;itemCode9:40;itemCode10:41;itemAmount6:42;itemAmount7:43;itemLngStr10:44;itemStr10:45;itemNum3:46;itemAmount8:47;itemAmount9:48;itemAmount10:49;itemNum4:50;itemNum5:51;itemNum6:52;itemNum2:53;itemNum7:54;itemNum8:55;itemNum9:56;"/>
            <where>"SIDE"='BV' </where>
        </update>

        
      <addColumn tableName="TB_GENERIC_LOADER">
			<column name="HAS_COPY" type="boolean" defaultValueBoolean="false">
				<constraints nullable="true"/>
			</column>
		</addColumn>

    </changeSet>
</databaseChangeLog> 

Expected behavior

migrate1DML.sql example

-- Lock Database
UPDATE databasechangeloglock SET LOCKED = TRUE, LOCKEDBY = '172.17.0.1 (172.17.0.1)', LOCKGRANTED = '2020-03-27 11:16:46.239' WHERE ID = 1 AND LOCKED = FALSE;


UPDATE "TB_GENERIC_LOADER" SET "PARSER" = 'itemNum1:2;itemLngStr1:4;itemLngStr2:5;itemAmount1:6;itemAmount2:7;itemCode1:8;itemCode2:9;itemCode3:10;itemStr1:11;itemDate1:12;itemDate2:13;itemDate3:14;itemDate4:15;itemLngStr3:16;itemLngStr4:17;itemLngStr5:18;itemStr2:19;itemCode4:20;itemCode5:21;itemStr3:22;itemCode6:23;itemLngStr6:24;itemLngStr7:25;itemLngStr8:26;itemLngStr9:27;itemDate5:28;itemAmount3:29;itemAmount4:30;itemAmount5:31;itemStr4:32;itemStr5:33;itemStr6:34;itemStr7:35;itemStr8:36;itemStr9:37;itemCode7:38;itemCode8:39;itemCode9:40;itemCode10:41;itemAmount6:42;itemAmount7:43;itemLngStr10:44;itemStr10:45;itemNum3:46;itemAmount8:47;itemAmount9:48;itemAmount10:49;itemNum4:50;itemNum5:51;itemNum6:52;itemNum2:53;itemNum7:54;itemNum8:55;itemNum9:56;' WHERE "SIDE"='BV';


INSERT INTO databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('202003160830-mychangelog.xml', 'xxxx', 'src/main/resources/config/liquibase/changelog/202003160830-mychangelog.xml'', NOW(), 324, '7:a4ef3e26dc54515d2482b8dd09fa825d', 'update tableName=TB_GENERIC_LOADER; loadData tableName=TB_ROLE_FUNCTION_AUTHORITIES; update tableName=TB_GENERIC_LOADER', '', 'EXECUTED', NULL, NULL, '3.5.3', '5304208244');

-- Release Database Lock
UPDATE databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;


migrateDDL2.sql

ALTER TABLE "TB_GENERIC_LOADER" ADD "HAS_COPY" BOOLEAN DEFAULT FALSE;

**Comment by SteveDonie** [comment] 2020-03-30 15:22
OK - you added expected behavior, but what was the actual behavior, and how was that different? 

I would expect that the actual behavior would be that the SQL would have the lock statement, then the update statement, then the alter table statement, then the insert into the DATABASECHANGELOG and then the release lock. 

You seem to expect that the alter table would come afterwards, but that is not how the tool is designed to work. When changesets are executed (or the SQL for them is generated) they are intended to have the pattern:
* lock
* apply changes
* update DATABASECHANGELOG
* unlock

If there are multiple changesets to be applied, then the two "inner" statements are repeated for each changeset.

If a changeset has multiple changes in it, then those are always applied together.

**Comment by molivasdat** [comment] 2020-05-11 19:57
@cnotario Does Steve's comment make sense?  If so, can I close this as working as designed?

**Comment by cnotario** [comment] 2020-05-13 13:14
Yes, you can. Thanks!

**Comment by molivasdat** [comment] 2020-05-13 13:16
Working as designed.  Thanks again.

**Closed by molivasdat** 2020-05-13 13:16 UTC
Labels: StatusDiscovery
