### ISSUE TITLE
loaddata command fails when importing data from a CSV into a h2 database with columns of type date

### ISSUE THREAD

**Issue by darac79** [liquibase/liquibase#2982] opened 2022-06-21 16:56 UTC
## Environment
Windows/Java 8

**Liquibase Version**:  
4.9.1

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
liquibase CLI 4.11.0

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:
h2 database in version 2.1.212

**Operating System Type & Version**:
Windows 11

**Infrastructure Type/Provider**: <AWC, GCS, Azure, VM, etc>

## Description
It's not possible to re-import exported data with the loadData command from a CSV file into a h2 table that contains a column of type DATE.

The used h2 table has been created with liquibase. It contains columns of type DATE.

`<changeSet author="ostricki (generated)" id="1.0 create piv_car">
		<preConditions onFail="MARK_RAN" onSqlOutput="TEST">
			<not>
				<tableExists tableName="PIV_CAR" />
			</not>
		</preConditions>
		<createTable tableName="PIV_CAR">
			<column name="ID" type="INT" />
			<column name="TRANSPORT_DETAIL_ID" type="INT" />
			<column name="RENTAL_CLASS" type="INT" />
			<column name="DAYS_RENTED" type="INT" />
			<column name="START_CITY" type="VARCHAR(20 ${VARCHAR_COLUMN_LENGTH_TYPE})" />
			<column name="START_DATE" type="date" />
			<column name="END_CITY" type="VARCHAR(20 ${VARCHAR_COLUMN_LENGTH_TYPE})" />
			<column name="END_DATE" type="date" />
		</createTable>
		<rollback>
			<dropTable tableName="PIV_CAR" cascadeConstraints="true" />
		</rollback>
	</changeSet>`

I exported data from a database using the liquibase CLI tool into a CSV file.
Within the CSV file the format is standardized in ISO format. 2009-08-12T00:00:00

An exemplary entry can be seen here.
`"ID","TRANSPORT_DETAIL_ID","RENTAL_CLASS","DAYS_RENTED","START_CITY","START_DATE","END_CITY","END_DATE"
"1","1008","0","0","DETROIT","2009-08-12T00:00:00","DETROIT","2009-08-15T00:00:00"`

The csv file is imported again with load data into a h2 database with the same schema.

The import fails with the following error:
`ERROR: DB: H2: arctic_ha: liquibase.exception.MigrationFailedException: Migration failed for change set dbschema/test/arctic_ha/import-dump-data.xml::1655815589061-3::jenkins (generated):
     Reason: liquibase.exception.DatabaseException: Cannot parse "DATE" constant "2009-08-12 00:00:00"; SQL statement:
INSERT INTO PUBLIC.PIV_CAR (ID, TRANSPORT_DETAIL_ID, RENTAL_CLASS, DAYS_RENTED, START_CITY, START_DATE, END_CITY, END_DATE) VALUES (1, 1008, 0, 0, 'DETROIT', '2009-08-12 00:00:00', 'DETROIT', '2009-08-15 00:00:00') [22007-212] [Failed SQL: (22007) INSERT INTO PUBLIC.PIV_CAR (ID, TRANSPORT_DETAIL_ID, RENTAL_CLASS, DAYS_RENTED, START_CITY, START_DATE, END_CITY, END_DATE) VALUES (1, 1008, 0, 0, 'DETROIT', '2009-08-12 00:00:00', 'DETROIT', '2009-08-15 00:00:00')]
INFO: DB: Init h2|arctdevha@arcticdev in 3692 ms
INIT: DB: h2/DEVCIB@arcticdev: {]`

Appearently for h2 columns of datatype DATE the value is converted by liquibase into "2009-08-12 00:00:00" but h2 only allows the format without time "2009-08-12".

Expectation:
For h2 columns of type date the ISO formatted time value should be transformed into the proper date format for the SQL creation.

## Steps To Reproduce

@see above

## Actual Behavior
It's possible to export data from any database to CSV when the table has columns of date type DATE.
It's not possible to reimport exported CSV data into a h2 database using the loadData command when the table has columns of date type DATE. 

## Expected/Desired Behavior
A reimport of exported data should be possible also for the combination of h2  + table with columns, of type DATE.

**Comment by FBurguer** [comment] 2022-09-06 16:52
Hi! Im trying to reproduce this issue, but in my case, the DATE values are not exported in ISO format. 
When I tried to reproduce it I did the next few steps:
1)Had this changelog
```
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:pro="http://www.liquibase.org/xml/ns/pro" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-latest.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd">  
    <changeSet id="20210913_job" author="Marcel">
       <createTable tableName="job">
           <column name="id" type="bigint" autoIncrement="true">
               <constraints primaryKey="true" primaryKeyName="job_id_pk"/>
           </column>
           <column name="start_time" type="time"/>
       </createTable>
   </changeSet>
    <changeSet id="persons_test_data" author="john_doe">
    <loadData commentLineStartsWith="#"
          encoding="UTF-8"
          file="test.csv"

          relativeToChangelogFile="true"
          separator="," 
          tableName="job"
          usePreparedStatements="true">
        <column name="start_time" type="TIME" />      
    </loadData>
  </changeSet>
</databaseChangeLog>
```
With this csv file
```
ID,TRANSPORT_DETAIL_ID,RENTAL_CLASS,DAYS_RENTED,START_CITY,START_DATE,END_CITY,END_DATE 
1,1008,0,0,DETROIT,2009-08-12,DETROIT,2009-08-15
```
I ran `liquibase update`
2)I ran `liquibase generatechangelog --diff-types=data` --dataOutputDirectory=changelogs
And got the next csv:
```
"ID","TRANSPORT_DETAIL_ID","RENTAL_CLASS","DAYS_RENTED","START_CITY","START_DATE","END_CITY","END_DATE"
"1","1008","0","0","DETROIT","2009-08-12","DETROIT","2009-08-15"
```
Looks like it got fixed for liquibase `4.15`.
Im going to close the issue but if the isssue continues to happens to you, please re-open the issue and we will have a second look!

**Closed by FBurguer** 2022-09-06 16:52 UTC
Labels: TypeBug, DBH2, OSWindows, featureLoadData, ver4.9.1, ver4.11.0
