### ISSUE TITLE
When loading changelogs LiquibaseEntityResolver slows down loading of huge changelog file structures by inefficiently processing classpath resources

### ISSUE THREAD

**Issue by ckulenkampff** [liquibase/liquibase#1754] opened 2021-03-10 11:28 UTC
## Environment
**Liquibase Version**: 4.3.1

**Liquibase Integration & Version**: Java 1.8 (a custom Gradle plugin)

## Description
When upgrading from Liquibase 4.2.2 to 4.3.1 parsing our changelog became extremely slow (a few seconds vs. several minutes). Our changelog is split into many XML files (~750 XML files).

The cause of the slowdown is the following:
The `LiquibaseEntityResolver`  is created per changlog file. Each `LiquibaseEntityResolver` initiates a new `ClassLoaderResourceAccessor`. The initialization of `ClassLoaderResourceAccessor` causes a scan of all `URL`s that are processed by the underlying `ClassLoader` and unfortunately the costly creation of a new `FileSystem` per `URL`.

Solution alternatives that came to my mind: 

1. use the context `ClassLoader` directly 
1. lazily initialize the root paths in `ClassLoaderResourceAccessor`
1. Initialize the `LiquibaseEntityResolver` once and provide it via `Scope`

## Steps To Reproduce
1. Create a changelog XML structure with many (hundreds) included sub changelog XML files.
1. Use Liquibase to load this changelog hierarchy.

## Actual Behavior
Loading the big changelog is really slow.

## Expected/Desired Behavior
Loading the big changelog is not slow.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1339) by [Unito](https://www.unito.io)

**Comment by molivasdat** [comment] 2021-03-12 01:55
Hi @ckulenkampff Thanks for adding this issue to github.  We will add this to the list of issues to process.

**Comment by NoStreamDK** [comment] 2021-03-29 20:56
Hi,
We are experiencing the same issue. The resolving time went from 5 sec. to 5 min and is just increasing as we apply more changelogs.
Currently we have 640 changelogs that are scanned and 249 jars/URLs (240 MB), which all are scanned for every changelog, which ends up in 159360 scans.

**Comment by stolp** [comment] 2021-05-09 23:07
I am experiencing the same issue here, effectively preventing us to update to newer versions.

I like to add resource caching to the list of viable solutions here, AFAIKS this is limited to schemas anyway.

**Comment by blutorange** [comment] 2021-05-13 07:53
Just for reference, this seems to be the same issue as the ticket I made #1815 The way it's currently done not only affects performance, but in addition to opening file systems for each JAR these file systems are never closed explicitly. This results in many file descriptors being created, and depending on the system limits, the application server process may eventually run out of file descriptors.

**Comment by nvoxland** [comment] 2021-05-21 18:39
Yes, this is a duplicate of #1815 so I'll close this one and move discussion to that ticket.

**Comment by nvoxland** [comment] 2021-05-21 18:39
Duplicate of #1815

**Closed** 2021-05-21 18:39 UTC
Labels: DBAll, ImpactMedium, IntegrationGradle, Severity2, StatusDiscovery, TypeBug
