### ISSUE TITLE
XML Schema defintion no longer provided via HTTP, only HTTPS

### ISSUE THREAD

**Issue by Simulant87** [liquibase/liquibase#2342] opened 2022-01-07 11:31 UTC
I define the liquibase XML schema definition the the databaseChangeLog element of my liquibase change sets like this, but I get an error, that the file cannot be parsed.

```
<databaseChangeLog
xmlns="http://www.liquibase.org/xml/ns/dbchangelog/"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog/ http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd">
```

Checking the URL via curl on the terminal returns that the page was moved permanently. 
```
% curl -i http://www.liquibase.org/xml/ns/dbchangelog/
HTTP/1.1 301 Moved Permanently
Location: https://www.liquibase.org/xml/ns/dbchangelog/

% curl -i http://www.liquibase.org/xml/ns/dbchangelog 
HTTP/1.1 301 Moved Permanently
Location: https://www.liquibase.org/xml/ns/dbchangelog

% curl -i https://www.liquibase.org/xml/ns/dbchangelog
HTTP/2 301
location: http://www.liquibase.org/xml/ns/dbchangelog/

% curl -i https://www.liquibase.org/xml/ns/dbchangelog/
HTTP/2 200
Expected body contained.
```

Is this expected behaviour, the the schema definition is no longer served via HTTP?

Also when I update my file to use HTTPS like this:

```
<databaseChangeLog
xmlns="https://www.liquibase.org/xml/ns/dbchangelog/"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.liquibase.org/xml/ns/dbchangelog/ https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd">
```

I get the following Exception:

```
java.lang.RuntimeException: liquibase.exception.ChangeLogParseException:
Error parsing line 5 column 44 of my_file_name.xml:
TargetNamespace.1: Expecting namespace 'https://www.liquibase.org/xml/ns/dbchangelog/',
  but the target namespace of the schema document is 'http://www.liquibase.org/xml/ns/dbchangelog'.
```

**Comment by rajaasthana** [comment] 2022-01-07 11:48
All of a sudden, we also face the similar issue
Error: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.

**Comment by codymartin** [comment] 2022-01-07 12:48
We're having the same issue.

**Comment by davidpgg** [comment] 2022-01-07 12:56
I have tried the workaround suggested in #1038 of using schema version 3.1 and this appear to work.

**Comment by JessThrysoee** [comment] 2022-01-07 13:36
We see 403 ?

```
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.9.xsd
```

But, the schema version 3.1 workaround works.

**Comment by dattnguyen1991** [comment] 2022-01-07 13:37
I tried with below schema and it work. 

```xml
<databaseChangeLog  
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:ext="https://www.liquibase.org/xml/ns/dbchangelog-ext" 
        xmlns:pro="https://www.liquibase.org/xml/ns/pro" 
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.3.xsd
        https://www.liquibase.org/xml/ns/dbchangelog-ext https://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd https://www.liquibase.org/xml/ns/pro https://www.liquibase.org/xml/ns/pro/liquibase-pro-4.3.xsd">
```

**Comment by codymartin** [comment] 2022-01-07 13:38
I can't get the 3.1 workaround to work. Using 3.6.3

**Comment by kprateek777** [comment] 2022-01-07 13:38
Isn't it supposed to read the ones available in the jar?

**Comment by Raotor123** [comment] 2022-01-07 13:40
> I can't get the 3.1 workaround to work. Using 3.6.3

@codymartin We got it working again with 3.5 for some files.

**Comment by asifm-mms** [comment] 2022-01-07 13:42
are there any side effects of changing the dbchangelog version?

**Comment by kpagan** [comment] 2022-01-07 13:49
In order Liquibase to be able to load the cached XSDs bundled inside the JAR the versions on the XSD file defined in the XML header in the schemaLocation attribute must match the version of the liquibase-core artifact that is the dependency in the Maven or Gradle project.

**NOTE:** check the version of **liquibase-core**, not the version of the _liquibase-maven-plugin_ or the _liquibase-gradle-plugin_. These version don't match

**Comment by davidpgg** [comment] 2022-01-07 14:43
I can confirm kpagan post in that we were using liquibase-core 3.6.3 in our runner image and it works with version 3.6 but nothing newer.

**Comment by nvoxland** [comment] 2022-01-07 14:45
There is is that a “require https” setting somehow got enabled for the XSD urls. We’re shifting our website hosting provider and despite the fact that we explicitly tested for this requirement on staging, something seems different in their new production settings. We’ve gotten the settings fixed up so this should no longer be a problem. Both http and https URLs should return content without any redirects.

In general, Liquibase should read the xsd files bundled in the jar rather than try to download them but there have been a few versions over the years which had a bug that caused them to pull them from the network. If you were seeing this problem, it means you had one of those URLs and upgrading will make liquibase run a bit faster as it won't be making unnessisary network calls. But, if you don't upgrade, it should be working as before again.

**Comment by codymartin** [comment] 2022-01-07 15:06
@kpagan educated me on the need for the xsd version match the version of liquibase-core. jhipster had been spitting out versions later than 3.6 and that was causing my issue. I changed them to "../dbchangelog-3.6.xsd" to match and now it reads the cached files when deploying. many thanks

**Comment by nvoxland** [comment] 2022-01-07 15:09
It looks like there is a separte new-server setting to deny user-agent=java requests. Looking into that now...

**Comment by nvoxland** [comment] 2022-01-07 16:51
The user-agent block has been resolved now as well, so everything should be fixed up now. 

Let me know if you still have issues related to the XSD file downloading. The user agent one was a java 8 vs 11/17 thing so hard to know what other permutations may cause unexpected problems.

**Closed** 2022-01-07 16:51 UTC
