### ISSUE TITLE
Liquibase escaping the string in the apostrophes and messing up the entire code

### ISSUE THREAD

**Issue by DarrianCZE** [liquibase/liquibase#3002] opened 2022-06-24 10:05 UTC
## Environment

**Liquibase Version:** 4.8 - we are forced to used this version, as the version 4.9 is plagued by this issue: https://github.com/liquibase/liquibase/issues/2688 ; 

**Liquibase Integration & Version**: Docker build

**Database Vendor & Version Oracle**: Oracle 19c

**Operating System Type & Version**: Gitlab CICD pipeline

## Description

Liquibase is escaping the dashes in the apostrophes

For example, this is part of the Package body replace code we were running:

else
         nxt.put_line( ' ---- Prazdný ----- ' ) ;
        end if ;
        null ;
      end ;

and this is how Liquibase deployed it into the database

        else
          nxt.put_line( ' 
        end if ;
        null ;
      end ;

Which of course messed up the entire code.

## Steps To Reproduce

Run any PL/SQL package body create or replace command containing the ( ' ---- Prazdný ----- ' ) ;

For example: DBMS_OUTPUT.put_line( ' ---- Prazdný ----- ' ) ;

## Actual Behavior
Described above

## Expected/Desired Behavior
Ignore any string inside the apostrophes, as is expected in any PL/SQL code.

**Comment by DarrianCZE** [comment] 2022-08-01 19:47
I think I have found the cause. I think Liquibase treats "--" as a comment, and it will delete the rest of the line. We have not been using stripComments:false until recently, and it appears this issue had stopped occuring.

**Comment by FBurguer** [comment] 2022-08-31 17:10
If thats the case and you found the solution, im closing this issue. But, if it continues to happend, please let us know, thanks!

**Comment by DarrianCZE** [comment] 2022-08-31 17:50
I believe that what I have found is simply a workaround, and not a simply fix, as it considers "--" as comment, no matter whether it's in quotes and meant as a text string to show the user.

**Comment by filipelautert** [comment] 2022-10-10 16:52
Hello @DarrianCZE ! I'm having problems simulating this bug.... liquibase is working as expected for me.  I'm using liquibase from docker, trying with version 4.8.0 and 4.16.1:
```
docker run --rm -v $(pwd):/liquibase/changelog liquibase/liquibase:4.8.0 --defaultsFile=/liquibase/changelog/liquibase.workspace.oracle.properties update-sql
```
My changelog looks like: 
```
--liquibase formatted sql
--changeset data_public:create_fnc_get_string.sql failOnError:true runAlways:true runOnChange:true stripComments:true

CREATE OR REPLACE FUNCTION fnc_get_string
RETURN varchar2
 IS
BEGIN
    -- comment test
    DBMS_OUTPUT.put_line( ' ---- Prazdný ----- ' ) ;
    RETURN '---- Prazdný ----'; -- more comments?
END fnc_get_string;
/
```

I'm running against Oracle 19c and it's working fine, liquibase removes the comments and keeps the strings. Are you doing something different from that? Otherwise would you be able to check if it still happens with version 4.17 ?

Thanks

**Comment by DarrianCZE** [comment] 2022-10-10 17:17
Hi!

Interesting. Well, if you want, I can try to email you the entire procedure
I was trying to deploy.

And yes, we are running Oracle 19c.

I can try to check whether it happens with the latest Liquibase version.

Jan



po 10. 10. 2022 v 18:52 odesílatel filipe lautert ***@***.***>
napsal:

**Comment by filipelautert** [comment] 2022-10-10 17:29
If you could try with latest version would be great, as fixes are incorported only to latest versions. If it still failing I can try with the entire procedure - maybe something else is messing with the parser and causing it to fail.
Thanks again

**Comment by filipelautert** [comment] 2022-10-25 12:18
Hello @DarrianCZE - were you able to reproduce it with latest version? thanks

**Comment by filipelautert** [comment] 2022-11-11 19:15
Closing it as seems already fixed.  If it still happens please reopen it.

**Closed by filipelautert** 2022-11-11 19:15 UTC
Labels: TypeBug, Severity3, DBOracle, docker, ver4.8.0, CItoolGitlab, needs_response, sprint2022-35
