### ISSUE TITLE
IncludeAll does not work for Java 9+

### ISSUE THREAD

**Issue by alexander-shustanov** [liquibase/liquibase#1696] opened 2021-02-15 06:37 UTC
## Environment
**Liquibase Version**: 4.2.2

**Liquibase Integration & Version**: CLI

## Description
An approach used in liquibase to traverse directories inside jars does not work for Java 9.
It returns an empty list of files. The approach used to be used in liquibase 3.9 was right.

The exact place, where the empty list of files is returned: https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java#L237.

## Steps To Reproduce
Launch liquibase update with changelogs provided inside some jar from classpath.

## Actual Behavior
Changelogs from includeAll directory are ignored.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1244) by [Unito](https://www.unito.io/learn-more)

**Comment by nvoxland** [comment] 2021-02-15 18:50
I believe this is a duplicate of #1436 which should be fixed in 4.3.2

**Closed by nvoxland** 2021-02-15 18:50 UTC
Labels: StatusDiscovery
