### ISSUE TITLE
spring boot migration fails on DBMS precondition run from tests

### ISSUE THREAD

**Issue by mattiaskagstrom** [liquibase/liquibase#4951] opened 2023-09-25 15:33 UTC
### Search first

- [X] I searched and no similar issues were found

### Description

Adding a DBMS precondition to a changesets always fails. Setting it to onFail: HALT gives the error that it received a null value rather than the actuals dbms value, thus making the expected value worthless.

The migration is triggered when running JUnit tests and liquibase runs as part of the application startup via spring boot.

Tested with liquibase 4.23.2, 4.19.1 and 4.18.0

Changeset:
```
  - changeSet:
      id: 1694787386115-90
      author: redacted
      preConditions:
        - onFail: HALT
        - dbms:
          type: h2
      changes:
        - dropUniqueConstraint:
            constraintName: STATUS_HISTORYPK
            tableName: status_history
```

Output:
```
[ERROR] com.****Test  Time elapsed: 1.645 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext for [WebMergedContextConfiguration@4dc9e3ea testClass = com.****Test, locations = [], classes = [com****Application, com****Test.UserDetailsTestConfiguration], contextInitializerClasses = [], activeProfiles = ["junit", "no-kafka", "no-security"], propertySourceLocations = ["classpath:application.yml"], propertySourceProperties = ["org.springframework.boot.test.context.SpringBootTestContextBootstrappe
r=true"], contextCustomizers = [[ImportsContextCustomizer@7d241c26 key = [org.springframework.boot.test.autoconfigure.web.servlet.MockMvcAutoConfiguration, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcWebClientAutoConfiguration, org.springframework.boot.test.autoconfigure.web.servlet.MockM
vcWebDriverAutoConfiguration, org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration, org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration, org.springframework.boot.autoconfigure.security.servlet.SecurityAu
toConfiguration, org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration, org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcSecurityConfiguration, org.springframework.boo
t.test.autoconfigure.web.reactive.WebTestClientAutoConfiguration, org.springframework.boot.test.autoconfigure.jdbc.TestDatabaseAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration]], org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@76889e60, o
rg.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@3e104d4b, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@15c7d7e0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@74d3b638, org.springframework.
boot.test.autoconfigure.actuate.observability.ObservabilityContextCustomizerFactory$DisableObservabilityContextCustomizer@1f, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@481df700, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFa
ctory$Customizer@6b52dd31, org.springframework.boot.test.context.SpringBootTestAnnotation@c80234b4], resourceBasePath = "src/main/webapp", contextLoader = org.springframework.boot.test.context.SpringBootContextLoader, parent = null]
        at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:143)
        at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:127)
        at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:191)
        at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:130)
        at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:241)
        at org.springframework.test.context.junit.jupiter.SpringExtension.postProcessTestInstance(SpringExtension.java:138)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$10(ClassBasedTestDescriptor.java:377)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.executeAndMaskThrowable(ClassBasedTestDescriptor.java:382)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$11(ClassBasedTestDescriptor.java:377)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestInstancePostProcessors(ClassBasedTestDescriptor.java:376)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$instantiateAndPostProcessTestInstance$6(ClassBasedTestDescriptor.java:289)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:288)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$4(ClassBasedTestDescriptor.java:278)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$5(ClassBasedTestDescriptor.java:277)
        at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$before$2(ClassBasedTestDescriptor.java:203)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:202)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:84)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
        at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
        at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:50)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:184)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:148)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: liquibase.exception.MigrationFailedException: Migration fai
led for changeset liquibase/changelogs/2023-09-15-vtopc-history-refactoring.yml::1694787386115-90::a451908:
     Reason:
          liquibase/changelogs/ : DBMS Precondition failed: expected null, got h2

        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:313)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:931)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:436)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
        at org.springframework.boot.test.context.SpringBootContextLoader.lambda$loadContext$3(SpringBootContextLoader.java:137)
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:58)
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:46)
        at org.springframework.boot.SpringApplication.withHook(SpringApplication.java:1406)
        at org.springframework.boot.test.context.SpringBootContextLoader$ContextLoaderHook.run(SpringBootContextLoader.java:545)
        at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:137)
        at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:108)
        at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:187)
        at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:119)
        ... 66 more
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset liquibase/changelogs/2023-09-15-vtopc-history-refactoring.yml::1694787386115-90::a451908:
     Reason:
          liquibase/changelogs/ : DBMS Precondition failed: expected null, got h2

        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:136)
        at liquibase.Liquibase.lambda$null$0(Liquibase.java:301)
        at liquibase.Scope.lambda$child$0(Scope.java:187)
        at liquibase.Scope.child(Scope.java:196)
        at liquibase.Scope.child(Scope.java:186)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.Scope.child(Scope.java:256)
        at liquibase.Liquibase.lambda$update$1(Liquibase.java:299)
        at liquibase.Scope.lambda$child$0(Scope.java:187)
        at liquibase.Scope.child(Scope.java:196)
        at liquibase.Scope.child(Scope.java:186)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.Liquibase.runInScope(Liquibase.java:2714)
        at liquibase.Liquibase.update(Liquibase.java:239)
        at liquibase.Liquibase.update(Liquibase.java:224)
        at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:329)
        at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:284)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1816)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
        ... 89 more
Caused by: liquibase.exception.MigrationFailedException: Migration failed for changeset liquibase/changelogs/2023-09-15-vtopc-history-refactoring.yml::1694787386115-90::a451908:
     Reason:
          liquibase/changelogs/ : DBMS Precondition failed: expected null, got h2

        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:631)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:59)
        at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:124)
        at liquibase.Scope.lambda$child$0(Scope.java:187)
        at liquibase.Scope.child(Scope.java:196)
        at liquibase.Scope.child(Scope.java:186)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:124)
        at liquibase.Scope.lambda$child$0(Scope.java:187)
        at liquibase.Scope.child(Scope.java:196)
        at liquibase.Scope.child(Scope.java:186)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.Scope.child(Scope.java:256)
        at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:105)
        at liquibase.Scope.lambda$child$0(Scope.java:187)
        at liquibase.Scope.child(Scope.java:196)
        at liquibase.Scope.child(Scope.java:186)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.Scope.child(Scope.java:256)
        at liquibase.Scope.child(Scope.java:260)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:75)
        ... 107 more
Caused by: liquibase.exception.PreconditionFailedException: Preconditions Failed
        at liquibase.precondition.core.AndPrecondition.check(AndPrecondition.java:47)
        at liquibase.precondition.core.PreconditionContainer.check(PreconditionContainer.java:213)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:617)
        ... 127 more

```

### Steps To Reproduce

Running via mvn test with a h2 in memory db in postgres mode

### Expected/Desired Behavior

The changeset should run on h2 databases bot not other

### Liquibase Version

4.23.2

### Database Vendor & Version

H2

### Liquibase Integration

spring boot

### OS and/or Infrastructure Type/Provider

Windows 10

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment] 2023-10-02 13:57
Hello @mattiaskagstrom, thank you for bringing this issue to our attention.
I've been able to replicate it with H2, PostgreSQL and MSSQL, so I can confirm it's not a database-specific problem.
I'll be forwarding this to the development team so they can evaluate how to move forward.
Thank you
Tatiana

**Comment by tati-qalified** [comment] 2024-01-19 19:01
Still an issue for version 4.25.1

**Comment by MalloD12** [comment] 2024-02-02 20:23
Hi @mattiaskagstrom,

From what I'm seeing here there is not a Liquibase issue, the issue I can see here is a missing tab on the `type` property from the specified precondition.

I tried with the below changelog and it worked well:

```
databaseChangeLog:
  - changeSet:
      id: create_table_change
      author: mallod
      changes:
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                  name: id
                  type: INT
              - column:
                  constraints:
                    nullable: false
                  name: name
                  type: VARCHAR(40)
            tableName: team
  - changeSet:
      id: drop_column
      author: mallod
      preConditions:
        - onFail: HALT
        - dbms:
            type: postgresql
      changes:
        - dropColumn:
            columnName: name
            tableName: team

```

cc: @tati-qalified 

I'm closing this issue since it's working as expected. Please, feel free to reopen if even adding the missing tab you can still reproduce this issue. 

Thanks,
Daniel.

**Closed by MalloD12** 2024-02-02 20:23 UTC
Labels: IntegrationSpringboot
