### ISSUE TITLE
SQLFileChange broken relative path resolving

### ISSUE THREAD

**Issue by bostandyksoft** [liquibase/liquibase#4249] opened 2023-05-11 01:46 UTC
### Search first

- [X] I searched and no similar issues were found

### Description

After upgrading from 4.15.0 to 4.21.1 we found exception, when execute our scripts.

We are often using relative pathes to our changes. So it works correctly until we updates to last release.

### Steps To Reproduce

We have changeset into another changeset with relative path to parent

```
<changeSet author="nufefelov" id="Create_tables" runOrder="first">
        <comment>Создание таблиц</comment>
        <sqlFile relativeToChangelogFile="true"
                 path="../../oracle/crtable.sql"
                 encoding="Cp1251"
                 dbms="oracle"/>
        <sqlFile relativeToChangelogFile="true"
                 path="../../postgresql/crtable.sql"
                 encoding="UTF-8"
                 dbms="postgresql"/>
    </changeSet>
```
Since update we got error
liquibase.exception.LiquibaseException: liquibase.exception.UnexpectedLiquibaseException: java.io.FileNotFoundException: JAR entry com/asuproject/usoi/db/manage/scripts/liquibase/scheme/../../oracle/crtable.sql not found in D:\usoi5\master\core\build\libs\exploded\core.war\WEB-INF\lib\com.asuproject-usoi-db-scripts-5.x.jar

### Expected/Desired Behavior

I found, that there are changes in SQLFileChange.java

There is method, that calculates relative path correctly (4.15.0)

```
@Override
    public InputStream openSqlStream() throws IOException {
        if (path == null) {
            return null;
        }

        InputStream inputStream;
        try {
            String relativeTo = null;
            if (ObjectUtil.defaultIfNull(isRelativeToChangelogFile(), false)) {
                relativeTo = getChangeSet().getChangeLog().getPhysicalFilePath();
            }
            inputStream = Scope.getCurrentScope().getResourceAccessor().openStream(relativeTo, path);
        } catch (IOException e) {
            throw new IOException("Unable to read file '" + path + "'", e);
        }

        if (inputStream != null) {
            return inputStream;
        }
        throw new IOException(FileUtil.getFileNotFoundMessage(path));
    }
```
And there is new version of this code, that does’not work from 4.21.1

```
@Override
    public InputStream openSqlStream() throws IOException {
        if (path == null) {
            return null;
        }

        ResourceAccessor resourceAccessor = Scope.getCurrentScope().getResourceAccessor();
        if (ObjectUtil.defaultIfNull(isRelativeToChangelogFile(), false)) {
            return resourceAccessor.get(getChangeSet().getChangeLog().getPhysicalFilePath()).resolveSibling(path).openInputStream();
        } else {
            return resourceAccessor.getExisting(path).openInputStream();
        }
    }
```
The method resolveSiblings() does’nt resolve it.

### Liquibase Version

4.21.1

### OS and/or Infrastructure Type/Provider

Windows 10

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by jccampanero** [comment] 2023-05-15 23:13
The changeset is located in `com/asuproject/usoi/db/manage/scripts/liquibase/scheme/` and the scripts in something similar to `com/asuproject/usoi/db/manage/scripts/oracle/crtable.sql`, is it correct?

**Comment by bostandyksoft** [comment] 2023-05-16 01:58
Yes. It is correct

**Comment by jccampanero** [comment] 2023-05-30 22:51
Thank you very much @bostandyksoft, and sorry for the late reply.

I tested your directory structure with different tests cases and all of them worked properly.

Anyway, I will try to perform further tests try finding the error.

**Comment by bostandyksoft** [comment] 2023-06-01 09:51
Hi.

Yes. It is inside another (common) changelog.xml and includes by following way

`<include relativeToChangelogFile="true" file="scheme/CreateScheme.xml" context="install"/>`

**Comment by jccampanero** [comment] 2023-06-04 15:03
Thank you very much for the feedback @bostandyksoft.

I think the issue closely resembles #3200, it may be caused by the same problem.

**Comment by kevin-atx** [comment] 2023-08-01 13:53
@filipelautert - even though this ticket is not marked as "willing to submit a PR", I'd like to request development guidance on fixing this newly introduced change to behavior.

**Comment by filipelautert** [comment] 2023-08-02 19:52
Hello @jccampanero ! Were you able to reproduce this issue?

**Comment by jccampanero** [comment] 2023-08-03 22:40
Sorry for the late reply @filipelautert. 

No, I did some initial testing, that's the reason I identified that this issue might be related to #3200, but I'm sorry, I've been very busy at work with limited sparse time and couldn't continue working on the issue.

I'm still busy, although now I have more free time: I could work on it if you wish.

**Comment by filipelautert** [comment] 2023-08-07 13:06
@jccampanero I see, no problems! We had some path fixes that were added to 4.23.0 , maybe it's already fixed there?
@bostandyksoft do you think you can try it with 4.23.0 ?

**Comment by jccampanero** [comment] 2023-08-09 21:58
Sorry for the late reply @filipelautert.

Thank you very much for the feedback, I will try reviewing it in version 4.23.0.

Thank you very much again!!

**Comment by MalloD12** [comment] 2023-08-30 17:01
Hi @jccampanero,

Have you had a chance to reproduce this issue using 4.23.0?  

Thanks,
Daniel.

**Comment by jccampanero** [comment] 2023-08-30 22:53
No @MalloD12 Daniel, sorry, I haven't tried it yet. I'm so sorry, I've had very little free time. I will try to do my best to test it asap. Sorry again.

**Comment by MalloD12** [comment] 2023-08-31 13:35
Hi @jccampanero, 

No worries, I was just checking as I was going through some of the tickets on our list. 

Thanks,
Daniel.

**Comment by jccampanero** [comment] 2023-09-01 23:14
Hi @MalloD12,

Sorry for the late reply.

I perform some simple tests with the latest Liquibase version as of writing, 4.23.1, and I was unable to reproduce the issue.

The same is true for the issue #3200, the provided failing test case now success.

Please, be aware that, in contrast, I experienced some strange behavior when testing the YAML example proposed for the #3200 issue. It is the following.

The YAML provided in the issue doesn't define an `author` field:

```yaml
databaseChangeLog:
  - changeSet:
      id: create-schema
      changes:
        - sqlFile:
            path: sql/sql-file.sql
            relativeToChangelogFile: true
            splitStatements: false
```

If you try to perform `liquibase update` then it will cause the following error:

```
Unexpected error running Liquibase: La columna "AUTHOR" no permite valores nulos (NULL)
NULL not allowed for column "AUTHOR"; SQL statement:
INSERT INTO PUBLIC.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES (...)
```
Please, note that it causes that the corresponding migration record will not be inserted in `DATABASECHANGELOG` but the migration script is executed, the test table referenced in `sql-file.sql` is created.

If you try updating again, after including `author` in the YAML file, then Liquibase will fail because as stated, the test table defined in the migration script already exists.

Perhaps the existence of the field `author` could be validated before executing the `changeSet` to avoid this type of problems.

**Comment by MalloD12** [comment] 2023-09-04 21:03
Thanks so much @jccampanero for taking the time to perform this testing effort. We highly appreciate it. I have created #4837 for the SQL file issue you found.

I'm closing this issue as it wasn't reproduced in 4.23.1. Please feel free to reopen if anyone can still see this issue happening.

Thanks,
Daniel.

**Closed by MalloD12** 2023-09-04 21:03 UTC
Labels: TypeBug, needs_guidance
