### ISSUE TITLE
Liquibase-core Booleantype always returns BOOLEAN in combination with liquibase-dbi2 plugin with version 4.4.X (plugin version 4.3.0)

### ISSUE THREAD

**Issue by ducatier** [liquibase/liquibase#2067] opened 2021-09-02 07:43 UTC
## Environment

**Liquibase Version**: 4.4.X

**Liquibase Integration & Version**: Maven/spring-boot

**Liquibase Extension(s) & Version**:  liquibase-dbi2 version 4.3.0

**Database Vendor & Version**: DB2 on system I (As400)

**Operating System Type & Version**: Linux/ISeries

## Description

Liquibase-core Booleantype always returns BOOLEAN in combination with liquibase-dbi2 plugin with version 4.4.0 (plugin version 4.3.0). However de AS400/Iseries doesn't support this boolean type. This results in a SQL error by creating the DATABASECHANGELOGLOCK file

 [SQL0204] BOOLEAN in *LIBL type *SQLUDT is niet gevonden. [Failed SQL: (-204) CREATE TABLE "XR013ONT".DATABASECHANGELOGLOCK ("ID" INTEGER NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DBCHGLOGLOCK PRIMARY KEY ("ID"))]

This issue can be fixed in liquibase.datatype.core.BooleanType by changing 

} else if (database.getClass().isAssignableFrom(DB2Database.class))

in

} else if (database instanceof DB2Database)

The issue occurs while de DB2iDatabase extends DB2Database. So in case of assignablefrom the DB2iDatabase class is never a DB2Database en this will result in the all fails step and returns a BOOLEAN.

## Steps To Reproduce

The issue occurs while de DB2iDatabase extends DB2Database. So in case of assignablefrom the DB2iDatabase class is never a DB2Database en this will result in the all fails step and returns a BOOLEAN.

This issue can be fixed in liquibase.datatype.core.BooleanType by changing 

} else if (database.getClass().isAssignableFrom(DB2Database.class))

in

} else if (database instanceof DB2Database)

## Actual Behavior
Liquibase aborts the start of the application!!

## Expected/Desired Behavior
Liquibase runs in combination with the correct DB2 plugin

## Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/1206222/131803433-9e01ac22-8e4c-4e5b-a555-d7417e06e2f1.png)

**Comment by molivasdat** [comment] 2021-09-07 12:10
Hi @ducatier Thanks for creating this issue.  This looks to be a duplicate of #2058 , if so we can add your steps for recreation there.

**Comment by ducatier** [comment] 2021-09-07 13:29
The behaviour is the same as #2058. But the Exception not only occur during a dropAll. In this case it's the creation of a new databaseschema.

**Comment by molivasdat** [comment] 2021-09-07 17:20
Hi @ducatier Will this fix break DB2 LUW instances that do support boolean types?

**Comment by ducatier** [comment] 2021-09-07 18:14
Hi @molivasdat. No this will not break DB2 LUW instances that support boolean types. In case of the liquibase-DB2i plugin it will actualy validate if the db version supports BOOLEAN types. The current situation is that it will never reach that code. 

The issue is that DB2iDatabase extends DB2Database. And in the current BooleanType.class it will only validate the support of a booleantype if the database is a DB2Database,class. (if (database.getClass().isAssignableFrom(DB2Database.class)))

If it is changed in ( if (database instanceof DB2Database)) then it will support also the plugins that extends the DB2Database.class

**Comment by nvoxland** [comment] 2021-11-11 18:02
The PR should address this issue as well, but I'll leave this open as well as another test option

**Closed** 2021-11-24 22:57 UTC
Labels: GStatusAddtionalInfo
