### ISSUE TITLE
liquibase-maven-plugin propertyFile YAML bug loading wrong username from application*.yml depending on order (Maven, Spring)

### ISSUE THREAD

**Issue by hci2** [liquibase/liquibase#1529] opened 2020-11-05 07:46 UTC
## Environment
**Liquibase Version**: 4.1.1

**Liquibase Integration & Version**: maven (3.6.1) spring boot (2.3.3.RELEASE)

**Liquibase Extension(s) & Version**: -

**Database Vendor & Version**: mssql-jdbc (7.4.1.jre8)

**Operating System Type & Version**: Windows 10 Enterprise (1909 18363.1139)

## Description
When using the liquibase-maven-plugin with propertyFile (configuration) pointing to an application_.yml to reuse my credentials of the database of the_ _spring environment yml property files__. The_ _order_

* within the application_.yml_ _is depending_* regarding the username **key** value, **if there are multiple**. In our case there are multiple username keys (spring.ldap.username, spring.mail.noreply.username, spring.mail.alert.username). They plugin only loads the username correct if it is at the bottom of the application*.yml. So the order matters. I think that this is not good. 

## Steps To Reproduce
pom.xml:

```
<parent>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-parent</artifactId>
    <version>Hoxton.SR8</version>
 </parent>

<org.liquibase.plugin.version>4.1.1</org.liquibase.plugin.version>

<dependency>
      <groupId>org.liquibase</groupId>
      <artifactId>liquibase-core</artifactId>
</dependency>

<plugins>
<!--      https://mvnrepository.com/artifact/org.liquibase/liquibase-maven-plugin     -->
      <plugin>
        <groupId>org.liquibase</groupId>
        <artifactId>liquibase-maven-plugin</artifactId>
        <version>${org.liquibase.plugin.version}</version> <!-- 4.1.1 -->
        <configuration>
<!--          Really helpful for defining correct relative path: https://stackoverflow.com/questions/16605099/using-liquibase-file-paths-via-both-maven-and-spring-->
          <propertyFile>application-${active.profile}.yml</propertyFile>
        </configuration>
      </plugin>
    </plugins>
```

application-ext.yml excerpt:
![LiquibaseMavenPlugin!UNITO-UNDERSCORE!ApplicationYAML!UNITO-UNDERSCORE!KeyOrderMatters](https://user-images.githubusercontent.com/19223435/98212059-58eb0800-1f43-11eb-8559-45bd4a459af4.PNG)

Command Line (CMD/PowerShell) in the root directory of the project:
`mvn liquibase:update`

When I switch the order of the username within the application-ext.yml following console output (using user INTRANET* for login) happens after executing "mvn liquibase:status -P ext":
![LiquibaseMavenPlugin!UNITO-UNDERSCORE!ApplicationYAML!UNITO-UNDERSCORE!WrongKeyOrder!UNITO-UNDERSCORE!ConsoleOutput](https://user-images.githubusercontent.com/19223435/98211055-c8f88e80-1f41-11eb-8c66-1a416b94d75a.PNG)

## Actual Behavior
Caring of the key order for the plugin as a workaround.

## Expected/Desired Behavior
The correct loading of the liquibase keys without depending on the order. Maybe there is a bug when loading from .yml instead of .properties files.

## Additional Context
We want to use the liquibase-maven-plugin to manually update the db schema. But we also use liquibase-core dependency to update the schema in former times but we have the problem when using multiple instances (pods Kubernets --> Azure Kubernetes Service) because the DATABASECHANGELOGLOCK is locked and sometimes stays in this status. Afterwards the system is not working and we have to manually release the locks and restart. Details of something similar are described here: [lock problem OpenShift](https://stackoverflow.com/questions/61387510/how-to-solve-liquibase-waiting-for-changelog-lock-problem-in-several-pods-in-ope)

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-896) by [Unito](https://www.unito.io/learn-more)

**Comment by molivasdat** [comment] 2020-11-06 04:11
Hi @hci2 Thanks for writing up this issue.
You might try something like this
https://stackoverflow.com/questions/52645232/how-to-divide-liquibase-package-structure-for-dev-and-prod-environment-in-spring
As for the additional context, if I understand this correctly, you have a micro service architecture where multiple micro services are all connecting to the same database?

**Comment by hci2** [comment] 2020-11-06 18:57
Hi @molivasdat ,

I already read this article but I do not like the approach of making own db.properties/liquibase.properties and separate it via folder structure. Moreover to use a separate filter plugin to distinct and multiple places to care. I prefer to stick to the spring boot approach with different application*.properties/yml files. Therefore I am writing this issue because it should only read the appropriate key and not depend on the order.

Yes you are right. Based on the microservice manifesto that is not a good practice but we use on database because of cost reasons and to keep the joining and data exchange simple. 

I thank you for your answer and I wish you a good evening!

**Comment by nvoxland** [comment] 2021-06-09 21:08
I agree that we should be able to support .yaml files like spring boot does. 

Currently we just support .properties format, so this issue ends up being "unexpected behavior if you try to parse a yaml file as a properties format" which is "by design".

I created #1898 to track adding support for yaml files, and will close this one.

**Closed by nvoxland** 2021-06-09 21:08 UTC
Labels: DBMSSQLServer, ImpactLow, IntegrationMaven, IntegrationSpringboot, PRAssociated, Severity4, StatusDiscovery, TypeEnhancement
