### ISSUE TITLE
Including a Dockerfile in your change log directory causes StackOverflowException

### ISSUE THREAD

**Issue by edeesis** [liquibase/liquibase#2869] opened 2022-05-24 03:06 UTC
## Environment

**Liquibase Version**: v4.10.0, but I believe it'll affect v4.11.0 as well.

**Liquibase Integration & Version**: CLI (via Docker container)

**Liquibase Extension(s) & Version**: N/A

**Database Vendor & Version**: Postgres 13

**Operating System Type & Version**: MacOS Catalina

## Description

If a Dockerfile is included in the changelog root, the code that loads the files to be parsed and process will consider this file a Directory, because it can't load it as a URL, and it doesn't have a file extension.

https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java#L349

## Steps To Reproduce

List the steps to reproduce the behavior.

Create a changelog file:
```yaml
databaseChangeLog:
  - includeAll:
      path: changelog
      relativeToChangelogFile: true
```

Then in a changelog folder on the same level:

```yaml
databaseChangeLog:
  - changeSet:
      id: 1
      author: edeesis
      changes:
        - createTable:
            tableName: test
            columns:
              - column:
                  name: id
                  type: varchar(27)
                  constraints:
                    primaryKey: true
                    nullable: false
```

Then also include a Dockerfile on the same level, example:

```dockerfile
FROM liquibase/liquibase

ADD . /liquibase/changelog

CMD ["sh", "-c", "docker-entrypoint.sh --url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME} --username=${DB_USERNAME} --password=${DB_PASSWORD} --changeLogFile=liquibase-changelog.yml update"]
```

## Actual Behavior

When running the dockerfile above, you get this:

```
Unexpected error running Liquibase: Unknown reason

liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: Unknown reason
	at liquibase.command.CommandScope.execute(CommandScope.java:163)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:51)
	at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:21)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:325)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:291)
	at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:80)
Caused by: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: Unknown reason
	at liquibase.integration.commandline.Main$1.run(Main.java:443)
	at liquibase.integration.commandline.Main$1.run(Main.java:221)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.integration.commandline.Main.run(Main.java:221)
	at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:32)
	at liquibase.command.CommandScope.execute(CommandScope.java:157)
	... 14 more
Caused by: java.lang.StackOverflowError
	at java.base/java.net.URLStreamHandler.parseURL(Unknown Source)
	at java.base/sun.net.www.protocol.file.Handler.parseURL(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/java.net.URL.<init>(Unknown Source)
	at java.base/jdk.internal.loader.URLClassPath$FileLoader.getResource(Unknown Source)
	at java.base/jdk.internal.loader.URLClassPath$FileLoader.findResource(Unknown Source)
	at java.base/jdk.internal.loader.URLClassPath$1.next(Unknown Source)
	at java.base/jdk.internal.loader.URLClassPath$1.hasMoreElements(Unknown Source)
	at java.base/java.net.URLClassLoader$3$1.run(Unknown Source)
	at java.base/java.net.URLClassLoader$3$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader$3.next(Unknown Source)
	at java.base/java.net.URLClassLoader$3.hasMoreElements(Unknown Source)
	at java.base/java.lang.CompoundEnumeration.next(Unknown Source)
	at java.base/java.lang.CompoundEnumeration.hasMoreElements(Unknown Source)
	at liquibase.resource.ClassLoaderResourceAccessor.listFromClassLoader(ClassLoaderResourceAccessor.java:261)
	at liquibase.resource.ClassLoaderResourceAccessor.listFromClassLoader(ClassLoaderResourceAccessor.java:312)
	at liquibase.resource.ClassLoaderResourceAccessor.listFromClassLoader(ClassLoaderResourceAccessor.java:312)
	at liquibase.resource.ClassLoaderResourceAccessor.listFromClassLoader(ClassLoaderResourceAccessor.java:312)
[...]
```

This infinite recursive loop is from Liquibase processing the lines of the Dockerfile. While the lines with Docker commands get ignored properly, the empty lines are processed by [this line](https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java#L305) turning them into the exact same folder that's currently being processed (in this case changelog/Dockerfile/ (which is not a folder), and the cycle repeats.

## Expected/Desired Behavior
I would expect the class loader processing to either ignore Dockerfiles entirely, or maybe add an if check for empty strings on childName:

```java
for (String childName : fileList.split("\n")) {
  if (!childName.isEmpty()) {
    String childPath = (path + "/" + childName).replaceAll("//+", "/");

    if (isDirectory(childPath)) {
        if (includeDirectories) {
            returnSet.add(childPath);
        }
        if (recursive) {
            returnSet.addAll(listFromClassLoader(childPath, recursive, includeFiles, includeDirectories));
        }
    } else {
        if (includeFiles) {
            returnSet.add(childPath);
        }
    }
  }
}
```

## Screenshots (if appropriate)

From my debugger:

<img width="1746" alt="image" src="https://user-images.githubusercontent.com/1738038/169940630-1d081c44-7f69-4116-be68-f5139131ce28.png">

<img width="1492" alt="image" src="https://user-images.githubusercontent.com/1738038/169940596-7967295e-312a-4a06-a021-046c617e1e57.png">

<img width="1493" alt="image" src="https://user-images.githubusercontent.com/1738038/169940611-40d1de8f-e970-4e7a-910e-0253f43bfd11.png">

## Additional Context

```
src/main/resources/db
├── Dockerfile
├── changelog
│   └── 001_init.yml
└── liquibase-changelog.yml
```

**Comment by edeesis** [comment] 2022-05-24 03:44
Also, the documentation for the liquibase Docker container says to specify the changelog file relative to `/liquibase/changelog`, but it looks like Liquibase is looking for it from `/liquibase` instead

[2022-05-24 03:42:54] INFO [liquibase.resource] Relative path liquibase-changelog.yml in /liquibase/. does not exist

**Comment by edeesis** [comment] 2022-05-24 03:50
This also appears to only happen with the folder structure of
<root>/root-file.yml
<root>/changelog/<migration 1>.yml

If I rename my subfolder anything other than changelog, it seems to work fine.

**Comment by FBurguer** [comment] 2022-08-31 12:14
Hi. I tried to reproduce this issue but I could not. Looks like it got fixed with the latest liquibase docker image. Can you try to reporduce it again after upgrading? If the issue continues to happen to you, please reach out again, thanks for submiting this issue and im looking forward to your answer!

**Closed by FBurguer** 2022-08-31 12:14 UTC
Labels: TypeBug, DBPostgres, IntegrationCLI, docker, ver4.10.0
