### ISSUE TITLE
Cannot call extension function from migration

### ISSUE THREAD

**Issue by Greenbones** [liquibase/liquibase#1823] opened 2021-05-04 16:33 UTC
## Environment
**Liquibase Version**: 4.3.3

**Liquibase Integration & Version**: Spring Boot 2.4.5

**Database Vendor & Version**: PostgresQL 12 w/ Timescale Extension

**Operating System Type & Version**: Linux 5.11

## Description
I am attempting to call an extension function that is added by the Timescale extension via a migration using a \<sql\> element. When the migration runs, I get an error indicating that the function doesn't existing with the given arguments. However, I have confirmed that the function is present by running the exact same SQL against the database directly.

I have used a similar call in the past and had success, so I eventually discovered that this sort of thing used to work in 3.7.0, but no longer works in 4.3.3. It seems like something is now configured in Liquibase such that it can't find these extension functions (schema related perhaps?).

This seems like it might be related to: https://github.com/liquibase/liquibase/issues/1821, but I wasn't sure.

## Steps To Reproduce
1) Run Timescale docker image (timescale/timescaledb:2.0.1-pg12)
2) Attempt to run a migration calling the create_hypertable extension function, or any extension function I suspect ```<sql>select create_hypertable('schema.table', 'timestamp');</sql>```
3) Run migration

## Actual Behavior
Migration fails with:

ERROR: function create_hypertable(unknown, unknown) does not exist
Hint: No function matches the given name and argument types. You might need to add explicit type casts.

## Expected/Desired Behavior
Migration succeeds.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1581) by [Unito](https://www.unito.io)

**Comment by molivasdat** [comment] 2021-05-07 12:00
Hi @Greenbones Thanks for creating the issue and providing the generic steps to recreate.  We will add this to the list of issues to process.  This may be similar to #1821 as you stated.

**Comment by nvoxland** [comment] 2021-05-25 19:34
Yes, this is a duplicate issue, so I'll close this one to consolidate discussion.

I have a fix for 4.5.0

**Comment by nvoxland** [comment] 2021-05-25 19:35
Duplicate of #1821

**Closed by nvoxland** 2021-05-25 19:35 UTC
Labels: DBPostgres, ImpactMedium, IntegrationSpringboot, Severity3, StatusDiscovery, TypeBug
