### ISSUE TITLE
generateChangeLog for MySQL produces BIT(3) for boolean columns defined as TINYINT(1).

### ISSUE THREAD

**Issue by victorrodrigueznadq** [liquibase/liquibase#3923] opened 2023-03-08 16:21 UTC
### Search first

- [X] I searched and no similar issues were found

### Description

generateChangeLog for MySQL produces BIT(3) for boolean columns defined as TINYINT(1).  This produces unexpected results when testing migrations during our build.  As a work around, I have to do the following, but I shouldn't have to do that.  If it's a TINYINT(1) in the database, it should be a TINYINT(1) in the databaseChangeLog.xml file produced.

```
find . -type f -name 'databaseChangeLog.xml' -exec sed -i 's:BIT(3):TINYINT(1):g' {} \;
```

Example....

```
create table rms.ACCOUNT_DESIGNATIONS
(
    ID                  varchar(36)            not null
        primary key,
    PARTICIPANT_ID      int                    not null,
    MP_ID               varchar(32)            null,
    USER_ID             int                    null,
    USER_ACCOUNT        varchar(32)            null,
    BILLING_ENTITY_ID   int                    null,
    BILLING_ENTITY_SIGN varchar(32)            null,
    IS_AUTD             tinyint(1) default 0   null,
    XSTO_EQ_PL          varchar(4)             null,
    XHEL_EQ_PL          varchar(4)             null,
    XCSE_EQ_PL          varchar(4)             null,
    XSTO_EQ_LPS         tinyint(1) default 0   null,
    XHEL_EQ_LPS         tinyint(1) default 0   null,
    XCSE_EQ_LPS         tinyint(1) default 0   null,
    NOK_EQ_LPS          tinyint(1) default 0   null,
    XSTO_EQ_TOP         tinyint(1) default 0   null,
    XHEL_EQ_TOP         tinyint(1) default 0   null,
    XCSE_EQ_TOP         tinyint(1) default 0   null,
    XSTO_WAR_PL         varchar(4)             null,
    XHEL_WAR_PL         varchar(4)             null,
    XCSE_WAR_PL         varchar(4)             null,
    XSTO_ETF_LPS        tinyint(1) default 0   null,
    XHEL_ETF_LPS        tinyint(1) default 0   null,
    NOK_ETF_LPS         tinyint(1) default 0   null,
    VALID_FROM_DATE     date                   null,
    YEAR_AND_MONTH      date                   null,
    NOTES               varchar(256)           null,
    TERMINATE_DATE      date                   null,
    XSTO_EQ_LPS_WAIVED  tinyint(1) default 0   null,
    XHEL_EQ_LPS_WAIVED  tinyint(1) default 0   null,
    XCSE_EQ_LPS_WAIVED  tinyint(1) default 0   null,
    NOK_EQ_LPS_WAIVED   tinyint(1) default 0   null,
    NOK_WAR_PL          varchar(4)             null,
    XSTO_AOD_LPS        tinyint(1) default 0   null,
    XHEL_AOD_LPS        tinyint(1) default 0   null,
    XCSE_AOD_LPS        tinyint(1) default 0   null,
    NOK_AOD_LPS         tinyint(1) default 0   null,
    XCSE_ETF_LPS        tinyint(1) default 0   null,
    XICE_EQ_PL          varchar(4) default '1' null,
    XICE_EQ_LPS         tinyint(1) default 0   null,
    XICE_EQ_TOP         tinyint(1) default 0   null,
    XICE_WAR_PL         varchar(4) default '1' null,
    XICE_ETF_LPS        tinyint(1) default 0   null,
    XICE_EQ_LPS_WAIVED  tinyint(1) default 0   null,
    XICE_AOD_LPS        tinyint(1) default 0   null
);
```

Looks like this in the generated changelog...note BIT(3) instead of TINYINT(1).

```
    <changeSet author="vicrod (generated)" id="1677692882380-1">
        <createTable tableName="ACCOUNT_DESIGNATIONS">
            <column name="ID" type="VARCHAR(36)">
                <constraints nullable="false" primaryKey="true"/>
            </column>
            <column name="PARTICIPANT_ID" type="INT">
                <constraints nullable="false"/>
            </column>
            <column name="MP_ID" type="VARCHAR(32)"/>
            <column name="USER_ID" type="INT"/>
            <column name="USER_ACCOUNT" type="VARCHAR(32)"/>
            <column name="BILLING_ENTITY_ID" type="INT"/>
            <column name="BILLING_ENTITY_SIGN" type="VARCHAR(32)"/>
            <column defaultValueBoolean="false" name="IS_AUTD" type="BIT(3)"/>
            <column name="XSTO_EQ_PL" type="VARCHAR(4)"/>
            <column name="XHEL_EQ_PL" type="VARCHAR(4)"/>
            <column name="XCSE_EQ_PL" type="VARCHAR(4)"/>
            <column defaultValueBoolean="false" name="XSTO_EQ_LPS" type="BIT(3)"/>
            <column defaultValueBoolean="false" name="XHEL_EQ_LPS" type="BIT(3)"/>
            <column defaultValueBoolean="false" name="XCSE_EQ_LPS" type="BIT(3)"/>
            <column defaultValueBoolean="false" name="NOK_EQ_LPS" type="BIT(3)"/>
            <column defaultValueBoolean="false" name="XSTO_EQ_TOP" type="BIT(3)"/>
            <column defaultValueBoolean="false" name="XHEL_EQ_TOP" type="BIT(3)"/>
            <column defaultValueBoolean="false" name="XCSE_EQ_TOP" type="BIT(3)"/>
            <column name="XSTO_WAR_PL" type="VARCHAR(4)"/>
            <column name="XHEL_WAR_PL" type="VARCHAR(4)"/>
            <column name="XCSE_WAR_PL" type="VARCHAR(4)"/>
            <column defaultValueBoolean="false" name="XSTO_ETF_LPS" type="BIT(3)"/>
            <column defaultValueBoolean="false" name="XHEL_ETF_LPS" type="BIT(3)"/>
            <column defaultValueBoolean="false" name="NOK_ETF_LPS" type="BIT(3)"/>
            <column name="VALID_FROM_DATE" type="date"/>
            <column name="YEAR_AND_MONTH" type="date"/>
            <column name="NOTES" type="VARCHAR(256)"/>
            <column name="TERMINATE_DATE" type="date"/>
            <column defaultValueBoolean="false" name="XSTO_EQ_LPS_WAIVED" type="BIT(3)"/>
            <column defaultValueBoolean="false" name="XHEL_EQ_LPS_WAIVED" type="BIT(3)"/>
            <column defaultValueBoolean="false" name="XCSE_EQ_LPS_WAIVED" type="BIT(3)"/>
            <column defaultValueBoolean="false" name="NOK_EQ_LPS_WAIVED" type="BIT(3)"/>
            <column name="NOK_WAR_PL" type="VARCHAR(4)"/>
            <column defaultValueBoolean="false" name="XSTO_AOD_LPS" type="BIT(3)"/>
            <column defaultValueBoolean="false" name="XHEL_AOD_LPS" type="BIT(3)"/>
            <column defaultValueBoolean="false" name="XCSE_AOD_LPS" type="BIT(3)"/>
            <column defaultValueBoolean="false" name="NOK_AOD_LPS" type="BIT(3)"/>
            <column defaultValueBoolean="false" name="XCSE_ETF_LPS" type="BIT(3)"/>
            <column defaultValue="1" name="XICE_EQ_PL" type="VARCHAR(4)"/>
            <column defaultValueBoolean="false" name="XICE_EQ_LPS" type="BIT(3)"/>
            <column defaultValueBoolean="false" name="XICE_EQ_TOP" type="BIT(3)"/>
            <column defaultValue="1" name="XICE_WAR_PL" type="VARCHAR(4)"/>
            <column defaultValueBoolean="false" name="XICE_ETF_LPS" type="BIT(3)"/>
            <column defaultValueBoolean="false" name="XICE_EQ_LPS_WAIVED" type="BIT(3)"/>
            <column defaultValueBoolean="false" name="XICE_AOD_LPS" type="BIT(3)"/>
        </createTable>
    </changeSet>
```

### Steps To Reproduce

run generateChangeLog against a MySql database that has some TINYINT(1) columns.

### Liquibase Version

4.19

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by victorrodrigueznadq** [comment] 2023-03-08 17:32
Likely the same for mariadb.

**Comment by LonwoLonwo** [comment] 2023-03-09 11:46
something similiar https://github.com/liquibase/liquibase/issues/2037

**Comment by victorrodrigueznadq** [comment] 2023-03-09 17:56
@nvoxland  well, it's a LITTLE better now after adding ?tinyInt1isBit=false to the url used by generateChangeLog...TINYINT(3), but it should be TINYINT(1)

<column defaultValueNumeric="0" name="IS_AUTD" type="TINYINT(3)"/>

**Comment by victorrodrigueznadq** [comment] 2023-03-09 19:15
@nvoxland and just tried it and TINYINT(3) breaks my application, so it needs to be TINYINT(1).

**Comment by nwcm** [comment] 2023-04-06 04:31
#2037 
#3172 
 Are related
 
 I am working on something that could possible fix 
 
 https://github.com/liquibase/liquibase/pull/4090

**Comment by MalloD12** [comment] 2023-05-26 18:55
Hi guys, I have been testing this scenario and this seems to be working as designed because on the way MySql handle `tinyInt(1)` by default. Look I have deployed this changelog in MySQL (5.7):
 
<img width="502" alt="Screenshot 2023-05-26 at 3 25 46 PM" src="https://github.com/liquibase/liquibase/assets/75833793/fcf10126-d75a-40fa-b12b-add0e4ac4e67">

which deployed in the DB both columns as `tinyInt(1)` as you can see on below screenshot:

<img width="327" alt="Screenshot 2023-05-26 at 3 25 58 PM" src="https://github.com/liquibase/liquibase/assets/75833793/8d1ac73c-8dc2-428a-a48f-7370a8810a4e">

But when performing a `generate-changelog` command the output is:

<img width="967" alt="Screenshot 2023-05-26 at 3 26 52 PM" src="https://github.com/liquibase/liquibase/assets/75833793/a06e71f2-667e-4c14-a94e-409e8c95700d">

This is fine because MySQL driver by default uses this configuration `tinyInt1isBit=true&transformedBitIsBoolean=false`. I guess. What you can do is try setting different URL parameter pairs of value for these flags.  I tried also `tinyInt1isBit=false&transformedBitIsBoolean=false` and the output was exactly the same.

Please let me know if there is anything I can do to help you with.  

Thanks,
Daniel.

**Comment by MalloD12** [comment] 2023-06-21 20:32
Closing this issue as I could not reproduce and in my opinion, it is working as expected. Please feel free to reopen it if are able to still reproduce it. Please share any additional info or steps in case you are able to keep facing it. 

Thanks,
Daniel

**Closed by MalloD12** 2023-06-21 20:32 UTC
Labels: good first issue
