### ISSUE TITLE
MySQL Datatype incorrectly applied TINYINT(1) -> BIT(1)

### ISSUE THREAD

**Issue by winklevos** [liquibase/liquibase#2037] opened 2021-08-16 02:28 UTC
## Environment

**Liquibase Version**: Liquibase Community 4.3.5

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: MySQL 8.0.21

**Operating System Type & Version**:  windows 10

## Description

- Any TINYINT(1) columns are converted to BIT(1) when generating a changelog. This is incorrectly applied boolean type for MySQL https://dev.mysql.com/doc/refman/8.0/en/other-vendor-data-types.html
- Some other external programs reading the database will not recognise BIT(1) as boolean for MySQL as it would with TINYINT(1)

## Steps To Reproduce
1. create table with boolean TINYINT(1) field
```CREATE TABLE `xxx` (
	`boolean` TINYINT(1) NOT NULL DEFAULT '0'
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;```

2. Generate changlog containing a TINYINT(1) field

## Actual Behavior

```
<changeSet author="xxx (generated)" id="xxx-x">
        <addColumn schemaName="xxx" tableName="xxxx">
            <column defaultValueBoolean="false" name="boolean" type="BIT(1)">
                <constraints nullable="false"/>
            </column>
        </addColumn>
</changeSet>
```

## Expected/Desired Behavior

```
<changeSet author="xxx (generated)" id="xxx-x">
        <addColumn schemaName="xxx" tableName="xxxx">
            <column defaultValueBoolean="false" name="boolean" type="TINYINT(1)">
                <constraints nullable="false"/>
            </column>
        </addColumn>
</changeSet>
```

**Comment by molivasdat** [comment] 2021-08-20 03:47
Hi @winklevos Thanks for creating this issue.  We will add this to the list of issues to process.

**Comment by nvoxland** [comment] 2021-12-22 16:22
This ends up being a "feature" of the mysql driver. When we ask it for the type of the `boolean` column in the example above, the driver tells us that it is of type bit and NOT tinyint like it actually is. 

There is a mysql URL parameter of `tinyInt1isBit=false` which changes the driver's behavior. See https://stackoverflow.com/questions/51258496/tinyint-returning-as-bit-in-databasemetadata-java

While it's perhaps possible to force an override or make the metadata queries ourselves, we also want Liquibase to respect the standard mysql behavior that other apps using the same URL will have. So for now at least I'll close this as "**by design, add the tinyInt1isBit=false parameter to your URL if you want the driver to act differently**". But, if you have arguments against that, feel free to comment here still.

**Closed by nvoxland** 2021-12-22 16:22 UTC
Labels: TypeBug, Severity3, ImpactLow, DBMySQL, IntegrationCLI, BKeyPlatform

**Comment by victorrodrigueznadq** [comment] 2023-03-09 15:57
@nvoxland you're saying that if I add tinyInt1isBit=false to the jdbc url when running generateChangeLog, it will work correctly?  (i.e. TINYINT(1) in the output, rather than BIT(3))

**Comment by victorrodrigueznadq** [comment] 2023-03-09 17:53
@nvoxland well, it's a LITTLE better now...TINYINT(3), but it should be TINYINT(1)

<column defaultValueNumeric="0" name="IS_AUTD" type="TINYINT(3)"/>
