### ISSUE TITLE
Changelogs that worked with 3.10 are failing on 4.17

### ISSUE THREAD

**Issue by MarkTJohnson** [liquibase/liquibase#3365] opened 2022-10-12 19:43 UTC
## Environment

**Liquibase Version**: 4.17

**Liquibase Integration & Version**:  gradle

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: SQL Server

**Operating System Type & Version**: Mac

**Infrastructure Type/Provider**: local machine testing

## Description

I am attempting to move from version 3.10 to 4.17 because 4.17 is supposed to fix the multithreading issue found here https://github.com/liquibase/liquibase/issues/2248

I changed my build.gradle to retrieve version 4.17.  Rebuilt my code and ran.  First time I got the error message below I thought it might be because I was still using the old dbchangelog-3.10.xsd so I tried the dbchangelog-latest.xsd and got the same message.  I next tried to use the specific dbchangelog-4.17.xsd and still see the same message

We call Liquibase in Java code like this
```
            Database db = DatabaseFactory.getInstance().findCorrectDatabaseImplementation((new JdbcConnection(c)));
            Liquibase lb = new Liquibase(changelogPath, new ClassLoaderResourceAccessor(), db);
            lb.update(context);
            closeDatabase(lb);
 ```
I have attached our master.xml, V181Changelog.xml, and the SQL file listed in the error.  These files worked perfectly in version 3.10 and have not changed, other than the dbchangelog-3.10.xsd to dbchangelog-4.17.xsd change.

The file structure is as follows
./master.xml
./version_181 (a directory)
./version_181/V181Changelog.xml
./version_181/DAYINT_11250_Add_Index_Idx_TAItinRow_ASK_IRK.sql

Error message received
```
liquibase.exception.LiquibaseException: liquibase.exception.UnexpectedLiquibaseException: java.net.MalformedURLException: No !/ in spec 'file:/DAYINT_11250_Add_Index_Idx_TAItinRow_ASK_IRK.sql'
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:126)
	at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:329)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:257)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Liquibase.runInScope(Liquibase.java:2447)
	at liquibase.Liquibase.update(Liquibase.java:236)
	at liquibase.Liquibase.update(Liquibase.java:221)
	at liquibase.Liquibase.update(Liquibase.java:207)
	at liquibase.Liquibase.update(Liquibase.java:197)
	at com.concur.reportdbservice.manager.ReportingSchemaMgr.update(ReportingSchemaMgr.java:69)
	at com.concur.reportdbservice.service.ReportingSchemaService.updateDatabase(ReportingSchemaService.java:56)
	at com.concur.reportdbservice.service.MigTaskService.entityMigrate(MigTaskService.java:51)
	at com.concur.reportdbservice.thread.MigMigrateJob.executeJob(MigMigrateJob.java:27)
	at com.concur.reportdbservice.thread.Job.run(Job.java:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: liquibase.exception.UnexpectedLiquibaseException: java.net.MalformedURLException: No !/ in spec 'file:/DAYINT_11250_Add_Index_Idx_TAItinRow_ASK_IRK.sql'
	at liquibase.change.AbstractSQLChange.generateCheckSum(AbstractSQLChange.java:204)
	at liquibase.changelog.ChangeSet.generateCheckSum(ChangeSet.java:314)
	at liquibase.changelog.ChangeSet.toString(ChangeSet.java:1036)
	at liquibase.changelog.ChangeLogIterator.createKey(ChangeLogIterator.java:181)
	at liquibase.changelog.ChangeLogIterator.alreadySaw(ChangeLogIterator.java:189)
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:94)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Scope.child(Scope.java:243)
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:93)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Scope.child(Scope.java:243)
	at liquibase.Scope.child(Scope.java:247)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:65)
	... 21 more
Caused by: java.net.MalformedURLException: No !/ in spec 'file:/DAYINT_11250_Add_Index_Idx_TAItinRow_ASK_IRK.sql'
	at java.base/java.net.URL.<init>(URL.java:679)
	at java.base/java.net.URL.fromURI(URL.java:719)
	at java.base/java.net.URI.toURL(URI.java:1116)
	at liquibase.resource.URIResource.openInputStream(URIResource.java:33)
	at liquibase.change.core.SQLFileChange.openSqlStream(SQLFileChange.java:120)
	at liquibase.change.AbstractSQLChange.generateCheckSum(AbstractSQLChange.java:190)
	... 39 more
Caused by: java.lang.IllegalArgumentException: No !/ in spec 'file:/DAYINT_11250_Add_Index_Idx_TAItinRow_ASK_IRK.sql'
	at org.springframework.boot.loader.jar.Handler.getFileFromSpec(Handler.java:235)
	at org.springframework.boot.loader.jar.Handler.parseURL(Handler.java:225)
	at java.base/java.net.URL.<init>(URL.java:674)
	... 44 more
```

**Comment by MarkTJohnson** [comment] 2022-10-12 19:48
[liquibase error.zip](https://github.com/liquibase/liquibase/files/9768237/liquibase.error.zip)

**Comment by MarkTJohnson** [comment] 2022-10-12 19:56
I just tried a test and picked Liquibase version 4.10 and the Changelog files included here worked properly.

**Comment by MarkTJohnson** [comment] 2022-10-12 20:02
Tested again and version 4.16 works properly with the same changelog files.

**Comment by Viserius** [comment] 2022-10-13 06:05
We are experiencing the same issue in which a changelog file will not be loaded on 4.17, but it does on 4.16.1

**Comment by kevin-atx** [comment] 2022-10-13 14:15
Thank you for reporting this. The development team made a fix for this issue that will be available in the next release.

**Comment by tabbyf00** [comment] 2022-10-14 16:12
We expect the release to be available within the next few weeks. The code's been merged to main, if you need to do a local build to fix the issue before the release.

**Comment by Viserius** [comment] 2022-10-14 16:59
Wonderful you were able to resolve this so quickly. Will look forward to (validating) the fix.

**Comment by FBurguer** [comment] 2022-11-11 14:32
@MarkTJohnson Hi! did the new liquibase version solved your issue?

**Comment by Marcosdg3** [comment] 2022-11-23 19:37
This looks like a duplicate of: https://github.com/liquibase/liquibase/issues/3200

**Closed** 2022-11-28 14:39 UTC
Labels: TypeBug, ver4.17.0
