### ISSUE TITLE
"includeAll" Adds changeSet Two Times in updateSQL Mode

### ISSUE THREAD

**Issue by zederisch** [liquibase/liquibase#2792] opened 2022-04-25 10:51 UTC
We are making heavily use of the Liquibas includeAll operation in a model to fill our applications database model. So far, this works great and allows us to split the configuration in small individual components, only carrying some settings, having it very well maintainable, and each accessing certain Liquibase master system files the ndoing the actual work on the databsae (e.g. inserts or updates of respective entities).

I figured out, that in our setup all "direct" changeSet operations, which we rarely use, appear twice inside the generates SQL code. I brought it down to some minimal example, so here is what seems wrong to me (or I am wrongly using it?):

1. I have a master configuration file, in which I link with "includeAll" a sub-directory.

databaseChangeLog:
- includeAll:
    path: ./config
    relativeToChangelogFile: true

2. Inside the "config" sub-folder, there is one file with actual configuration.

databaseChangeLog:
- changeSet:
    id: CreateBaseTable
    author: zederisch
    objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
    changes:
    - createTable:
        tableName: TestTable
        columns:
        - column:
            name: Column1
            type: int
        - column:
            name: Column2
            type: varchar(10)

When I compile the master file against an empty database (I tried PostgreSQL, SQLServer, Oracle and DB2), the create table block is contained two times in my generated SQL file:

-- Changeset ././config/createTable.yml::CreateBaseTable::zederisch
CREATE TABLE rsa.TestTable (Column1 INTEGER, Column2 VARCHAR(10));

INSERT INTO rsa.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('CreateBaseTable', 'zederisch', '././config/createTable.yml', NOW(), 1, '8:55d08f647b24ddec8cc0c87886955d69', 'createTable tableName=TestTable', '', 'EXECUTED', NULL, NULL, '4.9.1', '0883403649');

-- Changeset config/createTable.yml::CreateBaseTable::zederisch
CREATE TABLE rsa.TestTable (Column1 INTEGER, Column2 VARCHAR(10));

You can find here the minimal example that I described: [TEST.zip](https://github.com/liquibase/liquibase/files/8553834/TEST.zip)

In my real (way more complex) scenario, I have as a test just sourced out the direct changeSet part into a sub-file and referenced this via "include". In this example, everything works fine. So it seems like I cannot use a direct changeSet inside a configuration file referenced by includeAll, without getting duplicated code generation.

I tried with Liquibase version 4.9.1 (most recent) and 4.3.5 (which we are still using mainly because of other unresoved issues). Any advice how to solve that? Thanks! :)

**Comment by FBurguer** [comment] 2022-08-29 17:11
Hello! Im trying to reproduce this issue on liquibase `4.15` with the steps provided but I couldnt. Can you check if with the latest version of liquibase you still have this issue? Thanks!

**Comment by FBurguer** [comment] 2022-09-15 11:43
We couldnt reproduce this issue at this moment, Maybe its already fixed, for that reason Im closing up this issue. But, if the issue continues to happen to you, please re-open the issue/reach out. Thanks!

**Closed by FBurguer** 2022-09-15 11:43 UTC
Labels: TypeBug, ver4.3.5, ver4.9.1, featureIncludeAll
