### ISSUE TITLE
FormattedSQL property is not set when context is specified

### ISSUE THREAD

**Issue by droy-sandbox** [liquibase/liquibase#4067] opened 2023-04-03 15:08 UTC
### Search first

- [X] I searched and no similar issues were found

### Description

When declaring a property in a formatted SQL change log the property is improperly parsed if a context is specified.  For example:

`-- liquibase formatted sql
-- property name:PROPERTY_NAME value:PROPERTY_VALUE1 context:deploy.type.ci
-- property name:PROPERTY_NAME value:PROPERTY_VALUE2 context:!deploy.type.ci

-- changeset author:02eb4b93-193b-4f9b-8f34-0a02d8911795
create view demo as select '${PROPERTY_NAME}' alias`

The problem occurs because the formatted SQL parser creates the change log parameter using "PROPERTY_NAME value" as the key. 

### Steps To Reproduce

- Create a formatted change log using the example in the description.
- Executed a liquibase "update" while setting the "deploy.type.ci" context.

- The issue also occurs if the "deploy.type.ci" context is not set at run time, declare any other context at runtime (ex. "deploy.type.dev") to see this behavior.

### Expected/Desired Behavior

The change log parameter "${PROPERTY_NAME}" should be replaced with the correct property value based on the context declared at runtime.  In the example where the runtime context is set to "deploy.type.ci" the value should be "PROPERTY_VALUE1".

### Liquibase Version

4.20

### Database Vendor & Version

N/A

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

**Comment by MalloD12** [comment] 2023-05-12 20:45
Hey @droy-sandbox, 

While reviewing #4089 I've been trying to reproduce this issue without any luck yet. I have the below changelog:

```
--liquibase formatted sql
--property name:prop1 value:testValue context:testContext
--property name:prop2 value:testValue2 context:test

--changeset mallod:1
create table table1 (
                                 id int primary key not null,
                                 ${prop1} varchar(50) not null,
                                 address1 varchar(50),
                                 address2 varchar(50),
                                 city varchar(30)
)

--changeset mallod:2
create table table2 (
                               id int primary key not null,
                               ${prop2} varchar(50) not null,
                               address1 varchar(50),
                               address2 varchar(50),
                               city varchar(30)
)
```

And at runtime I'm specifying `--contexts=testContext`, but I'm not able to reproduce this issue. 

What I'm getting as output here is:
```
Running Changeset: changelog/sql/changelog.sql::1::mallod
Running Changeset: changelog/sql/changelog.sql::2::mallod

Unexpected error running Liquibase: Migration failed for changeset changelog/sql/changelog.sql::2::mallod:
     Reason: liquibase.exception.DatabaseException: ERROR: syntax error at or near "$"
  Position: 114 [Failed SQL: (0) create table table2 (
                               id int primary key not null,
                               ${prop2} varchar(50) not null,
                               address1 varchar(50),
                               address2 varchar(50),
                               city varchar(30)
)]
```

So, first changeSet is successfully deployed with the given property replacement correctly  done, but the second is giving a syntax error, but that's the issue you mentioned here. 

Are my steps the similar to what you have been executing here? Or is there any step I'm missing here.

Thanks,
Daniel.

**Comment by droy-sandbox** [comment] 2023-05-15 12:29
I believe the behavior you are experiencing is the desired outcome.  Because the context "test" is not specified at runtime the property "prop2" is not set and therefore, not substituted.

**Comment by MalloD12** [comment] 2023-05-15 12:45
Would you mind sharing (if possible) the change sets you used to reproduce this issue? 

Thanks,
Daniel.

**Comment by MalloD12** [comment] 2023-05-16 12:20
Hi Denis (@droy-sandbox), thank you for sharing this. As I comment in #4089 I could finally reproduce the issue and verify that your fix is resolving it. If you don't mind, could you please look at my comment there? Basically, I was asking whether would be possible to add two more unit tests besides the ones you already added (which I very much appreciate). If for time constraints you are not able to do it I can add them, so then we can move your fix forward.

Thanks,
Daniel.

**Comment by MalloD12** [comment] 2023-05-16 14:30
> 

Appreciate it, Denis.

Thanks,
Daniel.

**Closed** 2023-07-26 12:27 UTC
