### ISSUE TITLE
Liquibase not parsing the SQL correctly

### ISSUE THREAD

**Issue by gopisaba** [liquibase/liquibase#3024] opened 2022-06-30 10:10 UTC
## Environment

**Liquibase Version**:
v4.12.0
**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
CLI
**Liquibase Extension(s) & Version**: 
Snowflake v3.13.9
**Database Vendor & Version**:
Snowflake
**Operating System Type & Version**:
Ubuntu
**Infrastructure Type/Provider**: <AWC, GCS, Azure, VM, etc>
AWS

## Description

Liquibase v4.12.0 is not parsing the SQL correctly. It works perfectly well in v4.11.0. 

## Steps To Reproduce

List the steps to reproduce the behavior.
- Changeset
```xml
    <changeSet id="ID-001" author="Auth" runOnChange="true" >
        <comment>Stored procedure to move data from X to Y layer</comment>
        <sqlFile path="update/proj1/procedures/001_CREATE.sql"/>
    </changeSet>
```
- Stored Procedure
```sql
CREATE
OR REPLACE PROCEDURE SCHEMA.PROCNAME(
    SCENARIO_NAME VARCHAR(6),
    SCENARIO_YEAR VARCHAR(4)
) RETURNS STRING LANGUAGE JAVASCRIPT EXECUTE AS CALLER AS '
if(!["El1", "El21"]
    .includes(SCENARIO_NAME)){
        throw "Invalid SCENARIO_NAME Error!"
    }

if(!SCENARIO_YEAR.startsWith("20") || !(SCENARIO_YEAR.length==4)){
    throw "Invalid SCENARIO_YEAR Error!"
}

var JOB_NAME = "Job Name 1";
var SUMMARY = "Summary of the Job";

# AND REST OF THE STORED PROC
```
- run `liquibase update`
## Actual Behavior
```sql
Starting Liquibase at 10:26:21 (version 4.12.0 #3073 built at 2022-06-17 05:59+0000)
Liquibase Version: 4.12.0
Liquibase Community 4.12.0 by Liquibase
Running Changeset: update/proj1/changelogs/changelog-dml.xml::ID-001::Auth
Unexpected error running Liquibase: SQL compilation error:
parse error line 8 at position 44 near '<EOF>'.
syntax error line 6 at position 0 unexpected 'if'. [Failed SQL: (1003) CREATE
OR REPLACE PROCEDURE SCHEMA.PROCNAME(
    SCENARIO_NAME VARCHAR(6),
    SCENARIO_YEAR VARCHAR(4)
) RETURNS STRING LANGUAGE JAVASCRIPT EXECUTE AS CALLER AS '
if(!["El1", "El21"]
    .includes(SCENARIO_NAME)){
        throw "Invalid SCENARIO_NAME Error!"]
For more information, please use the --log-level flag
```
Changeset for the above stored procedure
```xml
    <changeSet id="ID-001" author="Auth" runOnChange="true" >
        <comment>Stored procedure to move data from X to Y layer</comment>
        <sqlFile path="update/proj1/procedures/001_CREATE.sql"/>
    </changeSet>
```

## Expected/Desired Behavior
Expected to deploy the stored procedure correctly. 

## Additional Context
UpdateSQL output
```sql
-- Lock Database
UPDATE LIQUIBASE.DATABASE_CHANGE_LOG_LOCK SET LOCKED = TRUE, LOCKEDBY = 'abf9e865aa04 (172.17.0.2)', LOCKGRANTED = current_timestamp::timestamp_ntz WHERE ID = 1 AND LOCKED = FALSE;
-- Changeset update/proj1/changelogs/changelog-dml.xml::ID-001::Auth
-- Stored procedure to move data from X to Y layer
USE ROLE RL_SF_ETL;
CREATE
OR REPLACE PROCEDURE SCHEMA.PROCNAME(
    SCENARIO_NAME VARCHAR(6),
    SCENARIO_YEAR VARCHAR(4)
) RETURNS STRING LANGUAGE JAVASCRIPT EXECUTE AS CALLER AS '
if(!["El1", "El21"]
    .includes(SCENARIO_NAME)){
        throw "Invalid SCENARIO_NAME Error!";
UPDATE LIQUIBASE.DATABASE_CHANGE_LOG SET COMMENTS = 'Stored procedure to move data from X to Y layer', CONTEXTS = NULL, DATEEXECUTED = current_timestamp::timestamp_ntz, DEPLOYMENT_ID = '6325577662', EXECTYPE = 'RERAN', LABELS = NULL, MD5SUM = '8:124ca85b5c5814eb1f2b0155904152d1', ORDEREXECUTED = 1615 WHERE ID = 'ID-001' AND AUTHOR = 'Auth' AND FILENAME = 'update/proj1/changelogs/changelog-dml.xml';
```
For some reason, liquibase (v4.12) not parsing the SQL right.

**Comment by nvoxland** [comment] 2022-06-30 15:52
Thanks for the additional info.

The issue is from the `{` causing problems due to a bug in 4.12.0. 

That has been fixed in #2984 which will be coming out in 4.13.0

**Closed** 2022-06-30 15:52 UTC
Labels: DBSnowflake, IntegrationCLI, OSLinux, cloudAWS, ver4.12.0
