### ISSUE TITLE
Default schema is not recognized on latest version

### ISSUE THREAD

**Issue by NicolaSpreafico** [liquibase/liquibase#2665] opened 2022-03-22 17:11 UTC
Hello,
I have this changeset:
```
--changeset nicola:003 runAlways:true
--comment: call function which enable auditing for every table 
SELECT audit_trigger_install();

--rollback -- nothing to do here
```

This functions exists inside the schema _application_
```
CREATE OR REPLACE FUNCTION application.audit_trigger_install()
...
```

Since about 2 years ago I started this project, I always used the changelog as you can see, without a specific declaration of which schema is the function installed. The command I used has always been:
```
liquibase \
   --driver=org.postgresql.Driver \
   --classpath=postgresql-42.2.20.jar \
   --url=jdbc:postgresql://127.0.0.1/postgres \
   --username=xxxxxx \
   --password=yyyyyyyy \
   --changeLogFile=databaseChangelog.xml \
   --liquibaseSchemaName=liquibase \
   --defaultSchemaName=application \
   --contexts=dev\
   update
```

You can see that there is a specific notation "_defaultSchemaName_" to allow Liquibase work on a specific schema, and that has always worked since always using the version 4.2.2 I installed at first
```
Liquibase Community 4.2.2 by Datical
####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ##
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ##
##  Free schema change activity reports at        ##
##      https://hub.liquibase.com                 ##
##                                                ##
####################################################
Starting Liquibase at 17:54:49 (version 4.2.2 #36 built at 2020-12-09 20:07+0000)
Liquibase: Update has been successful.
```

Today I updated the version of Liquibase up to the latest one, 4.9.0 (no other changes, same changelog, same postgres driver, same liquibase command, ...) and here is the result
```
####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ##
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ##
##  Free schema change activity reports at        ##
##      https://hub.liquibase.com                 ##
##                                                ##
####################################################
Starting Liquibase at 18:06:46 (version 4.9.0 #1885 built at 2022-03-16 16:58+0000)
Liquibase Version: 4.9.0
Liquibase Community 4.9.0 by Liquibase
Running Changeset: databaseChangeLog_BUILD/changelog_1000_001_setup auto_trigger[audit_tables].sql::1000_001-003::nicola

Unexpected error running Liquibase: ERROR: function audit_trigger_install() does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 8 [Failed SQL: (0) SELECT audit_trigger_install()]
```

The only way I found to be working (with this new release) is forcing the schema as prefix of the function inside the changelog;
```
SELECT application.audit_trigger_install();
```
But, while this seems to be working, has a wide impact on my changelogs because I have many cases like this.
I then reverted the version back to previous 4.2.2 and it is working again.

What is going on? Something changed during one of the last releases?
Thanks

**Comment by kataggart** [comment] 2022-03-22 19:22
@NicolaSpreafico Thanks for all the detail here. We are taking a look.

**Comment by NicolaSpreafico** [comment] 2022-03-23 10:39
Hi @kataggart ,
I think I found an additional information about this.

Using the working version 4.2.2 I tried the updateSQL command in order to find some hint on where is the issue.
This is the resulting code
```
-- Changeset databaseChangeLog_BUILD/changelog_1000_001_setup auto_trigger[audit_tables].sql::1000_001-003::nicola
-- call function which enable auditing for every table 
SET SEARCH_PATH TO application;

SELECT audit_trigger_install();
```

You can see that there is a notation here
```SET SEARCH_PATH TO application;```

While using the latest version 4.9.0, the generated code is different
```-- Changeset databaseChangeLog_BUILD/changelog_1000_001_setup auto_trigger[audit_tables].sql::1000_001-003::nicola
-- call function which enable auditing for every table 
SELECT audit_trigger_install();
```

Without the schema overidde with the `SEARCH_PATH` it is understandable why it is not able to find the function.
It seems that somehow we lost the `defaultSchemaName` definition with latest releases.

**Comment by kataggart** [comment] 2022-03-23 13:14
@nvoxland I am wondering if the above behavior was introduced inadvertently in https://github.com/liquibase/liquibase/commit/c950ccebef96be9862455a9b2b192e3f7da3baf8 https://github.com/liquibase/liquibase/pull/1864  v4.5.0 ?

**Comment by antoniotaha** [comment] 2022-05-27 21:31
Oracle has the same problem

**Comment by nvoxland** [comment] 2022-06-01 20:53
This should be resolved for postgresql in #2812 but the change wouldn't apply to oracle.

I'll see if I can tell what oracle is doing

**Comment by SambitNanda** [comment] 2022-09-21 01:01
@nvoxland Was this ever fixed in Oracle? This is still a problem in Oracle

**Comment by kataggart** [comment] 2022-09-21 13:51
@SambitNanda It is in our queue to resolve. Sorry we haven't been able to get to it yet.

**Comment by shaounak** [comment] 2022-10-13 19:05
A similar issue we had seen in Snowflake recently. Until the liquibase 4.9.1 version worked as we were using the liquibase 4.9.1 extension for the snowflake. I recently read through the documentation for liquibase-snowflake that they had stopped maintaining the repo as the support for the same is moved to the liquibase regular or core repo. We had a script for creating the relationships which we use for both redshift and snowflake. The DDL works in both the DW implementations but as the default schema doesn't work we can't provide the `use search_path` in the case of redshift or `use schema` in the case of snowflake as it's a common script.

**Comment by filipelautert** [comment] 2022-10-19 21:11
Hi @SambitNanda , which liquibase version are you using? I tested option "--defaultSchemaName=my_schema"  on liquibase 4.8, 4.12 and 4.16.1 and running in debug I can see it doing an ALTER SESSION SET CURRENT_SCHEMA=my_schema . I'm running a simple insert into a table that is located in the defined schema and it's working.  Could you test with 4.16.1 and check it it's ok now? 
@shaounak  could you test with liquibase 4.16.1 too? I see some fixes have been introduced since 4.9.1 . If it fails can you provide more details?

**Comment by shaounak** [comment] 2022-10-19 21:42
I think the 4.17 is also released let me try with that and get back to you.

**Comment by SambitNanda** [comment] 2022-10-20 02:28
> 

@filipelautert  4.16.1 is the version we are seeing the issue in. Database is Oracle

**Comment by filipelautert** [comment] 2022-10-20 02:37
Thanks @SambitNanda ! Could you provide more details on how to reproduce the issue, maybe an example file? Are you executing it from command line or using any integration as maven or springboot?

**Comment by SambitNanda** [comment] 2022-10-20 03:05
@filipelautert  invoking the Liquibase update() from a java class directly. Our DB upgrader is neither maven or springboot. It starts an init-container and upgrades the DB before the main service comes up.

We have an Oracle system type user with DBA permissions that creates the databse objects. It needs to create them in applcation/service schema.


   
    Database getDatabase(String schema, Connection connection) throws DatabaseException {
       Database database = DatabaseFactory.getInstance() .findCorrectDatabaseImplementation(new 
                                                                                                                                            JdbcConnection(connection));
        if (schema != null && !schema.isBlank()) {
            database.setDefaultSchemaName(schema);
        }

        return database;
    }
    
     void executeChangeLog(Contexts contexts, String schemaToConnect, final String resourcePath)
            throws LiquibaseException, SQLException, IOException {
        try (Connection connection = getConnection()) {
            Database database = getDatabase(schemaToConnect, connection);

        // Now execute service's changelogs
            Liquibase liquibase =
                    new liquibase.Liquibase(resourcePath, new ClassLoaderResourceAccessor(), database);
            liquibase.update(contexts, new LabelExpression());
        }
    }


**Current workaround**
Get this executed first before other objects are created.

```
<changeSet id="oracle-alter-session" author="me">
  <sql dbms="oracle">ALTER SESSION SET CURRENT_SCHEMA=${database.defaultSchemaName}</sql>
</changeSet>

```

Hope that helps.

**Comment by filipelautert** [comment] 2022-10-20 20:03
@SambitNanda I still reviewing the code to understand where/how to fix it, but so far I found out that for Oracle using method **setDefaultCatalogName** would fix it:
```
if (schema != null && !schema.isBlank()) {
       if (oracle) {
          database.setDefaultCatalogName(schema);
       } else {
          database.setDefaultSchemaName(schema);
       }
    }
```

**Comment by SambitNanda** [comment] 2022-10-21 03:37
@filipelautert That is interesting. It wasn’t obvious in the documentation to me, but I will let you know the result if my testing. Thanks

**Comment by shaounak** [comment] 2022-10-21 05:19
Isn't default catalogue name is the default database name? What should be
the case with Redshift and Snowflake?

**Comment by shaounak** [comment] 2022-10-21 19:17
Thanks, I'll check it out.

**Comment by filipelautert** [comment] 2022-10-28 20:08
Hello, did it work? If it's all fine now we can close this ticket.

**Comment by shaounak** [comment] 2022-10-29 01:52
Yes it worked for us.

Regards,
Shaounak Nasikkar
________________________________

**Closed** 2022-10-31 12:51 UTC
Labels: TypeBug, DBOracle, DBPostgres, BKeyPlatform, ver4.9.0, ver4.2.2, defaultSchema, needs_response
