### ISSUE TITLE
`<loadData>` with column of type UUID yields SQLException ("Invalid Column Type") when using ORACLE

### ISSUE THREAD

**Issue by aixigo-soffermann** [liquibase/liquibase#2064] opened 2021-09-01 13:00 UTC
## Environment

**Liquibase Version**: 4.4.3

**Liquibase Integration & Version**:  maven

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: ORACLE 12 (client: `ojdbc11 v21.1.0.0`)

**Operating System Type & Version**: Linux, Mac (any version), Java 11

## Description

When trying to use `<loadData>` on a table with a column of type `uuid`, I get a `java.sql.SQLException`: _Invalid column type_. 

The error occurs in `OraclePreparedStatementClass.setObjectCritical()` because the column type value was mapped to 1111, which is not recognized.

## Steps To Reproduce

```
      <createTable tableName="TL_OBJECTS">
         <column name="ID" type="uuid">
            <constraints nullable="false" primaryKey="true"/>
         </column>
      </createTable>

      <loadData file="liquibase/migrations/data/csv/tl_objects.csv" tableName="tl_objects" usePreparedStatements="true">
         <column name="id" type="uuid"/>
      </loadData>
```

CSV:
```
"id",...
a60b32c3-bc88-4042-9974-4624279c23af,...
```

**Comment by aixigo-soffermann** [comment] 2021-09-02 05:26
This may help:
https://stackoverflow.com/questions/51023782/how-to-insert-uuid-into-raw16-column

ORACLE stores UUID values as byte arrays (see also [here](https://docs.oracle.com/en/database/other-databases/nosql-database/20.3/java-driver-table/using-uuid-data-type.html)).

**Comment by aixigo-soffermann** [comment] 2021-09-02 06:32
It seems to work if I modify `ExecutablePreparedStatementBase.java` like this:

```
    private void applyColumnParameter(PreparedStatement stmt, int i, ColumnConfig col) throws SQLException,
            DatabaseException {

        final Logger LOG = Scope.getCurrentScope().getLog(getClass());
        if (col.getValue() != null) {
            LOG.fine("value is string/UUID/blob = " + col.getValue());
            if (col.getType() != null && col.getType().equalsIgnoreCase(LoadDataChange.LOAD_DATA_TYPE.UUID.name())) {
                if( database instanceof OracleDatabase ) {
                    stmt.setBytes( i, toBytes( UUID.fromString( col.getValue() ) ) );
                } else {
                    stmt.setObject(i, UUID.fromString(col.getValue()));
                }
            } else if (col.getType() != null && col.getType().equalsIgnoreCase(LoadDataChange.LOAD_DATA_TYPE.OTHER.name())) {
               ...
```

**Comment by aixigo-soffermann** [comment] 2021-09-06 09:53
Here is a diff for the fix:

```
diff --git base.pom.xml base.pom.xml
index 811f52348..da55893b1 100644
--- base.pom.xml
+++ base.pom.xml
@@ -50,9 +50,9 @@
     </scm>
 
     <properties>
-        <liquibase.base.version>4.4.3</liquibase.base.version>
-        <liquibase.version.qualifier>-local</liquibase.version.qualifier>
-        <liquibase.version.snapshot>-SNAPSHOT</liquibase.version.snapshot>
+        <liquibase.base.version>4.4.3-aixigo-patch.0</liquibase.base.version>
+        <liquibase.version.qualifier></liquibase.version.qualifier>
+        <liquibase.version.snapshot></liquibase.version.snapshot>
         <liquibase.version>${liquibase.base.version}${liquibase.version.qualifier}${liquibase.version.snapshot}
         </liquibase.version>
         <maven.compiler.source>1.8</maven.compiler.source>
diff --git liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
index ed1fcaad0..29f2fbfe6 100644
--- liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
+++ liquibase-core/src/main/java/liquibase/statement/ExecutablePreparedStatementBase.java
@@ -5,6 +5,7 @@ import liquibase.change.ColumnConfig;
 import liquibase.changelog.ChangeSet;
 import liquibase.database.Database;
 import liquibase.database.PreparedStatementFactory;
+import liquibase.database.core.OracleDatabase;
 import liquibase.datatype.DataTypeFactory;
 import liquibase.datatype.LiquibaseDataType;
 import liquibase.exception.DatabaseException;
@@ -129,7 +130,11 @@ public abstract class ExecutablePreparedStatementBase implements ExecutablePrepa
         if (col.getValue() != null) {
             LOG.fine("value is string/UUID/blob = " + col.getValue());
             if (col.getType() != null && col.getType().equalsIgnoreCase(LoadDataChange.LOAD_DATA_TYPE.UUID.name())) {
-                stmt.setObject(i, UUID.fromString(col.getValue()));
+                if( database instanceof OracleDatabase ) {
+                    stmt.setString( i, col.getValue().replaceAll( "-", "" ) );
+                } else {
+                    stmt.setObject( i, UUID.fromString( col.getValue() ) );
+                }
             } else if (col.getType() != null && col.getType().equalsIgnoreCase(LoadDataChange.LOAD_DATA_TYPE.OTHER.name())) {
                 stmt.setObject(i, col.getValue(), Types.OTHER);
             } else if (LoadDataChange.LOAD_DATA_TYPE.BLOB.name().equalsIgnoreCase(col.getType())) {
diff --git liquibase-dist/pom.xml liquibase-dist/pom.xml
index 59649a767..41d8c06ec 100644
--- liquibase-dist/pom.xml
+++ liquibase-dist/pom.xml
@@ -147,6 +147,7 @@
                 <artifactId>maven-assembly-plugin</artifactId>
                 <version>3.1.1</version>
                 <configuration>
+                    <tarLongFileMode>posix</tarLongFileMode>
                     <finalName>liquibase-${liquibase.version}</finalName>
                     <appendAssemblyId>false</appendAssemblyId>
                     <attach>false</attach>
diff --git liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/history.test.groovy liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/history.test.groovy
index dd0579098..c7a6209bc 100644
--- liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/history.test.groovy
+++ liquibase-integration-tests/src/test/resources/liquibase/extension/testing/command/history.test.groovy
@@ -62,7 +62,7 @@ Optional Args:
 
         expectedOutput = [
                 Pattern.compile("""
-- Database updated at \\d+/\\d+.+. Applied 4 changeset\\(s\\) in \\d+.\\d+s, DeploymentId: \\d+
+- Database updated at \\d+.+ \\d+.+\\. Applied 4 changeset\\(s\\) in \\d+.\\d+s, DeploymentId: \\d+
   db/changelog/db.changelog-master.xml::1::nvoxland
   db/changelog/sql/create_test2.sql::raw::includeAll
   db/changelog/sql/create_test3.sql::raw::includeAll
```

**Comment by molivasdat** [comment] 2021-09-07 12:00
Hi @aixigo-soffermann Thanks for creating this issue and doing the research to provide a fix.  We will add this to the list of issues that we are processing.

**Comment by FBurguer** [comment] 2022-08-18 13:08
Looks like a duplicate of #1667

**Comment by kataggart** [comment] 2022-08-18 14:44
closing as duplicate; tracking via #1667

**Closed by kataggart** 2022-08-18 14:44 UTC
Labels: TypeBug, Severity3, ImpactLow, DBOracle, IntegrationMaven, BKeyPlatform, daily_review, featureLoadData, ver4.4.3
