### ISSUE TITLE
mvn liquibase:dropAll does not drop anything (much)

### ISSUE THREAD

**Issue by alf** [liquibase/liquibase#2977] opened 2022-06-21 08:50 UTC
## Environment

**Liquibase Version**: 4.12.0

**Liquibase Integration & Version**: maven

**Liquibase Extension(s) & Version**: -

**Database Vendor & Version**: Oracle XE 18c

**Operating System Type & Version**: NixOS 21.11

**Infrastructure Type/Provider**: VM

## Description

We're switching from flyway to liquibase. For developer productivity we sometimes need to drop everything and re-migrate. This worked very well with `flyway clean`, however with liquibase it seems that our database objects are not dropped.

See [debug.log](https://github.com/liquibase/liquibase/files/8947288/debug.log).

## Steps To Reproduce

Be us. Run the command. Watch it noop.

I can assist with reproducing this, but I need some help getting started here.

## Actual Behavior

Lots of tables and views remain in the schema.

## Expected/Desired Behavior

The schema should no longer have any tables and views.

**Comment by FBurguer** [comment] 2022-08-31 13:23
Hi! Thanks for submiting this issue. It would be great if you gives a little more context, like an example changelog of the database that you are trying to drop and it does not succed.

**Comment by FBurguer** [comment] 2022-09-22 13:25
With information provided, we could not reproduce the issue. So we are closing it for the moment, you are free to re-open the issue if it continue to happen to you. Thanks!

**Closed by FBurguer** 2022-09-22 13:25 UTC
Labels: TypeEnhancement, DBOracle, IntegrationMaven, ver4.12.0, infraVM, commandDropAll

**Comment by FBurguer** [comment] 2022-09-22 14:31
Of course! Let us know
