### ISSUE TITLE
Simple sql changeSet not executed anymore since version 4.22.0

### ISSUE THREAD

**Issue by pineappleexperience** [liquibase/liquibase#4500] opened 2023-07-17 08:06 UTC
### Search first

- [X] I searched and no similar issues were found

### Description

I hava a changeset using two [sql changes](https://docs.liquibase.com/change-types/sql.html) for different dbms, which has been working just fine up to version 4.21.1. Since version 4.22.0 It is not working anymore (4.23.0 did not fix the issue). The change set is not being executed anymore. I tested on MariaDB but not on other dbms. I suspect there will be the same issue.

### Steps To Reproduce

Here is an example of the change set which has been working up to version 4.21.1 but is not working anymore since version 4.22.0.

```xml
<changeSet id="my change set id" author="author">
	<sql dbms="mssql,postgresql">
		UPDATE first_table
		SET second_table_name = second_table.name
		FROM second_table
		WHERE first_table.second_table_id = second_table.id
	</sql>
	<sql dbms="oracle,mysql,mariadb">
		UPDATE first_table ft
		SET ft.second_table_name = (SELECT st.name FROM second_table st WHERE ft.second_table_id = st.id)
	</sql>
</changeSet>
```

### Expected/Desired Behavior

Expected the change set to be executed. Instead the following happens since version 4.22.0:

The change set **appears** to be executed. The databasechangelog table has an entry for the changeset with `exectype` `EXECUTED` and a `description` of `empty`. In versions prior to version 4.22.0 the description for the change set was `sql; sql`. But the actual SQL inside the [sql change](https://docs.liquibase.com/change-types/sql.html) is not being executed.

A later change set is attempting to add a not null constraint on the column `first_table.second_table_name` which fails because the sql from the change set "my change set id" was not executed. Therefore the column is null for every entry. Both columns `first_table.second_table_name` and `second_table.name` have a data type of `VARCHAR(50)`. `second_table.name` has a value for every entry and a not null constraint.

Error log: 
```java
liquibase.exception.DatabaseException: liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/liquibase/changelog.xml::add not null constraint::author:
     Reason: liquibase.exception.DatabaseException: (conn=115) Data truncated for column 'second_table_name' at row 1 [Failed SQL: (1265) ALTER TABLE my_db.first_table MODIFY second_table_name VARCHAR(50) NOT NULL]
```

### Liquibase Version

4.22.0 & 4.23.0

### Database Vendor & Version

MariaDB 10.3.38

### Liquibase Integration

Maven

### OS and/or Infrastructure Type/Provider

Ubuntu

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by MalloD12** [comment] 2023-07-17 16:04
Hi @pineappleexperience,

I have just tried executing the shared changelog on a MariaDB instance, which was executed successfully. 
<img width="850" alt="Screenshot 2023-07-17 at 12 59 19 PM" src="https://github.com/liquibase/liquibase/assets/75833793/3b8ee7a0-8c02-4637-989d-2fda4443d4c2">

Recently, we have merged #4453 which fixed #4443. I'm wondering if that could fix your issue as well, because from my master I wasn't able to reproduce the same error.  Would you mind copying the below changes we added in the **AbstractChange** class and let me know whether that helps you or not?

```
 @Override
    public boolean equals(Object reference) {
        return (this == reference);
    }

    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), changeSet);
    }
```

Thanks,
Daniel.

**Comment by pineappleexperience** [comment] 2023-07-19 07:51
Hello Daniel,

thanks for the reply. I tried running the change set with the current **master** version where `equals` and `hashCode` of `AbstractChange` are implemented the way you posted. And the change set is run successfully. 👍  The `description` for the change log entry in the databasechangelog table is now `sql` instead of `empty`.

**Comment by kevin-atx** [comment] 2023-10-27 13:14
It sounds like this issue was resolved. Please re-open this issue if you believe otherwise. Thanks.

**Closed by kevin-atx** 2023-10-27 13:14 UTC
