### ISSUE TITLE
Store execution time of a change-set in the databasechangelog table

### ISSUE THREAD

**Issue by johnny-the-coder** [liquibase/liquibase#5920] opened 2024-05-15 10:00 UTC
### Search first

- [X] I searched and no similar issues were found

### Description

It would be great to have stored in the DATABASECHANGELOG table the execution time of a change-set.

### Steps To Reproduce

nothing relevant

### Expected/Desired Behavior

I would expect that a new column EXECUTION_TIME will be added in the table DATABASECHANGELOG with the execution time of the particular change-set.

### Liquibase Version

4.24.0

### Database Vendor & Version

Postgres

### Liquibase Integration

maven

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR (Thank you!)

**Comment by kevin-atx** [comment] 2024-05-20 16:40
@johnny-the-coder - would you be interested in submitting a PR if our team shared guidance on where to make this change?

**Comment by johnny-the-coder** [comment] 2024-05-20 18:53
Hi @kevin-atx,
Although I don't know the source code, I could at least try to prepare a PR if I get some hints in which files (classes) the change should be done.

**Comment by MalloD12** [comment] 2024-06-12 18:25
Hi @johnny-the-coder,

Previously we have been discussing this topic with other community members and the answer this time would be the same. 
DatabaseChangelog is one of our main tables and if we start adding new columns per different requests/needs it could become something unmaintainable at a certain point of time. Although, this seems to be something several people in the community are looking for, this is a sensitive table we are trying to avoid changing (unless it's extremely necessary).  For cases like this, the most suitable scenario would be to create an extension and then do this kind of update.

Particularly, this type of information (execution time) can be found in logs. In curious about your use case. How would it help to have this data in the `databasechangelog` table?

Thanks,
Daniel.

**Comment by johnny-the-coder** [comment] 2024-06-17 12:35
Hi @MalloD12,

I think that if we store other information regarding change set execution adding only one column to store very informative fact like script execution time should not be a problem (and should not make the table unmaintainable because of that).

Information in logs could be troublesome to obtain if you have multiple services or numerous pod instances. This information could be also lost (if the pod is restarted or short-living) or difficult to find.

If you have it stored in the table or important information is in one place. In that way you can compare the execution time in any point if you have multiple instances of the system (especially if the data size is different among them).

Unfortunately from your answer I may read between the lines that you do not want the feature to be implemented and try to excuse why this should not happen (while being obvious that's is something many people want to have and seem to be quite easy to implement).

**Comment by MalloD12** [comment] 2024-06-17 18:21
Hi,

It's not something we don't want to implement, it's a product decision to not update the structure of one of the main liquibase tables for now. Hope you guys can understand this.

Thanks,
Daniel.

**Comment by MalloD12** [comment] 2024-09-03 17:00
Closing this for now. According to the last conversations we had with the team we are not planning to implement this change in the near future. 

cc: @lbadam @filipelautert @mariochampion  

Thanks,
Daniel.

**Closed by MalloD12** 2024-09-03 17:00 UTC
Labels: TypeEnhancement, performance, needs_guidance, observability

**Comment by lbadam** [comment] 2024-09-03 17:55
This is also a duplicate of #5577
