### ISSUE TITLE
Liquibase stopped working after upgrading from 3.6.3 to 3.8.7/3.10.2

### ISSUE THREAD

**Issue by h00jraq** [liquibase/liquibase#1341] opened 2020-08-24 09:44 UTC
## Environment
**Liquibase Version**: 3.8.7 or 3.10.2

**Liquibase Integration & Version**: Our own builder written for IBM i platform together with jt400
IBM Toolbox for Java:
Open Source Software, JTOpen 9.5, codebase 5770-SS1 V7R3M0.00 built=20180111 VB
Supports JDBC version 4.2
Toolbox driver version 11.5

**Liquibase Extension(s) & Version**: No extensions

**Database Vendor & Version**: DB2 for i. We are using jt400 for db2 connection

**Operating System Type & Version**: IBM i 7.3

## Description
When using version 3.6.3, everything works as it should. After moving to 3.8.7 or 3.10.2, our scripts no longer work when called from liquibase but they work if we run them directly without liquibase so for sure if it not the script problem. Problem is we do not get any error but they are just hang without any error message

## Steps To Reproduce
List the steps to reproduce the behavior.
Difficult to say but everything works fine with 3.6.3

## Actual Behavior
```
liquibase.log exist.
Liquibase found.
10:42:16.338 [main] DEBUG l.integration.commandline.Main - Custom logging config found, not going to modify
10:42:16.373 [main] DEBUG l.r.ClassLoaderResourceAccessor - Opening jar:file:/C:/ProgramData/chocolatey/lib/liquibase/content/liquibase.jar!/liquibase.build.properties as liquibase.build.properties
10:42:16.378 [main] INFO  l.integration.commandline.Main - 
Starting Liquibase at Mon, 24 Aug 2020 10:42:16 CEST (version 3.10.2 #22 built at Mon Jul 27 04:21:02 UTC 2020)
10:42:16.392 [main] DEBUG l.r.ClassLoaderResourceAccessor - Opening jar:file:/C:/ProgramData/chocolatey/lib/liquibase/content/liquibase.jar!/META-INF/MANIFEST.MF as META-INF/MANIFEST.MF
10:42:16.393 [main] DEBUG l.r.ClassLoaderResourceAccessor - Opening jar:file:/C:/ProgramData/chocolatey/lib/liquibase/content/lib/commons-cli-1.4.jar!/META-INF/MANIFEST.MF as META-INF/MANIFEST.MF
10:42:16.393 [main] DEBUG l.r.ClassLoaderResourceAccessor - Opening jar:file:/C:/ProgramData/chocolatey/lib/liquibase/content/lib/h2-1.4.200.jar!/META-INF/MANIFEST.MF as META-INF/MANIFEST.MF
10:42:16.394 [main] DEBUG l.r.ClassLoaderResourceAccessor - Opening jar:file:/C:/ProgramData/chocolatey/lib/liquibase/content/lib/jaxb-api-2.3.0.jar!/META-INF/MANIFEST.MF as META-INF/MANIFEST.MF
10:42:16.394 [main] DEBUG l.r.ClassLoaderResourceAccessor - Opening jar:file:/C:/ProgramData/chocolatey/lib/liquibase/content/lib/jaxb-core-2.3.0.jar!/META-INF/MANIFEST.MF as META-INF/MANIFEST.MF
10:42:16.395 [main] DEBUG l.r.ClassLoaderResourceAccessor - Opening jar:file:/C:/ProgramData/chocolatey/lib/liquibase/content/lib/jaxb-impl-2.3.0.jar!/META-INF/MANIFEST.MF as META-INF/MANIFEST.MF
10:42:16.396 [main] DEBUG l.r.ClassLoaderResourceAccessor - Opening jar:file:/C:/ProgramData/chocolatey/lib/liquibase/content/lib/logback-classic-1.2.3.jar!/META-INF/MANIFEST.MF as META-INF/MANIFEST.MF
10:42:16.397 [main] DEBUG l.r.ClassLoaderResourceAccessor - Opening jar:file:/C:/ProgramData/chocolatey/lib/liquibase/content/lib/logback-core-1.2.3.jar!/META-INF/MANIFEST.MF as META-INF/MANIFEST.MF
10:42:16.397 [main] DEBUG l.r.ClassLoaderResourceAccessor - Opening jar:file:/C:/ProgramData/chocolatey/lib/liquibase/content/lib/slf4j-api-1.7.25.jar!/META-INF/MANIFEST.MF as META-INF/MANIFEST.MF
10:42:16.398 [main] DEBUG l.r.ClassLoaderResourceAccessor - Opening jar:file:/C:/ProgramData/chocolatey/lib/liquibase/content/lib/slf4j-api-1.7.28.jar!/META-INF/MANIFEST.MF as META-INF/MANIFEST.MF
10:42:16.398 [main] DEBUG l.r.ClassLoaderResourceAccessor - Opening jar:file:/C:/ProgramData/chocolatey/lib/liquibase/content/lib/snakeyaml-1.18.jar!/META-INF/MANIFEST.MF as META-INF/MANIFEST.MF
10:42:16.398 [main] DEBUG l.r.ClassLoaderResourceAccessor - Opening jar:file:/C:/ProgramData/chocolatey/lib/liquibase/content/lib/snakeyaml-1.24.jar!/META-INF/MANIFEST.MF as META-INF/MANIFEST.MF
10:42:16.403 [main] DEBUG l.servicelocator.ServiceLocator - ServiceLocator.findClasses for liquibase.license.LicenseService
10:42:16.403 [main] DEBUG l.servicelocator.ServiceLocator - ServiceLocator finding classes matching interface liquibase.license.LicenseService
10:42:16.403 [main] DEBUG l.s.DefaultPackageScanClassResolver - Searching for implementations of liquibase.license.LicenseService in packages: [liquibase.change, liquibase.command, liquibase.changelog, liquibase.database, liquibase.parser, liquibase.precondition, liquibase.datatype, liquibase.serializer, liquibase.sqlgenerator, liquibase.executor, liquibase.snapshot, liquibase.logging, liquibase.diff, liquibase.structure, liquibase.structurecompare, liquibase.lockservice, liquibase.sdk.database, liquibase.ext, liquibase.pro, com.datical.liquibase]
```

## Expected/Desired Behavior
With 3.6.3, everything build as it should.

**Comment by h00jraq** [comment] 2020-08-24 14:17
I think I have found the cause:
I've called liquibase manually from command line, and this is what I've got:
 16:11:51.779 [main] DEBUG liquibase.executor.jvm.JdbcExecutor - Executing with the 'jdbc' executor
16:11:51.779 [main] INFO  liquibase.executor.jvm.JdbcExecutor - SELECT fixpack_num FROM TABLE (sysproc.env_get_inst_info()) as INSTANCEINFO
16:11:51.997 [main] INFO  liquibase.database.core.DB2Database - Error getting fix pack number
liquibase.exception.DatabaseException: Error executing SQL SELECT fixpack_num FROM TABLE (sysproc.env_get_inst_info()) as INSTANCEINFO: [SQL0204] ENV_GET_INST_INFO in SYSPROC type *N not found.

We are not running this SQL, it looks like forced by liquibase

**Comment by molivasdat** [comment] 2020-08-27 03:51
Hi @h00jraq Thanks for writing up this issue.  You are correct in that the code is using a different way to find out the version of DB2 that is being run.  It is related to https://liquibase.jira.com/browse/CORE-3580 where that table does not exist on DB2i or DB2on Z.  We will add it to our list of issues to process.

**Comment by molivasdat** [comment] 2020-08-27 04:28
@h00jraq .  Do you know that command on db2i that returns the version of db2 running?
Looking for something that shows Version Mod and Fixpack.
boolean column types were added in v11.1.1.1 of DB2 LUW but I don't know how to query db2i via a select statement to find version info.

**Comment by h00jraq** [comment] 2020-08-27 10:37
Hi,

Unfortunately, there is no command that allow you to check DB2 version on IBM i(old AS400). Basically, DB2 for i version match the system level/release so for example system version 7.3 is also db2 version. You can check that with sql SELECT * FROM "SYSIBMADM".ENV_SYS_INFO ;Result it (among other columns)
OS_NAME = IBM i
OS_VERSION = 7
OS_RELEASE = 3

In our opinion, it should be enough to use classpath or driver but of course using above sql is an good option.

Filip
    W czwartek, 27 sierpnia 2020, 06:29:07 CEST, Mike Olivas <notifications@github.com> napisał(-a):  
 
 


@h00jraq . Do you know that command on db2i that returns the version of db2 running?
Looking for something that shows Version Mod and Fixpack.
boolean column types were added in v11.1.1.1 of DB2 LUW but I don't know how to query db2i via a select statement to find version info.

**Comment by molivasdat** [comment] 2020-08-27 23:20
Thanks for the feedback.  This probably belongs in the db2i repository as an issue there.

**Comment by jaapspiering** [comment] 2022-09-29 11:59
The change in behaviour was introduced in https://github.com/liquibase/liquibase/pull/865 - before 3.7.0 the attempt to query sysproc.env_get_inst_info() was not there.

The description of the issue here is a little generic - it is specifically AS/400 / iSeries support that is broken.

**Comment by jaapspiering** [comment] 2022-10-04 18:20
@FBurguer Yes, this still reproduces with the latest 4.16.1 with plain liquibase - the same bit of code is still in there.

But the solution is to use the liquibase-db2i, then it works.  https://github.com/liquibase/liquibase-db2i
As of 3.7.0 DB2 I-series/AS400 is probably no longer supported by Liquibase which would mean this is not an issue.

**Comment by nvoxland** [comment] 2022-10-05 20:26
It's not so much that we "don't support db2 on i" as "to use liquibase with db2 on i, you need the extension added".

Since it's working correctly with the extension, I'll close the issue. Thanks for the info.

**Closed by nvoxland** 2022-10-05 20:26 UTC
Labels: TypeBug, Severity3, needs_response
