### ISSUE TITLE
liquibaseCatalogName not include in generated SQL

### ISSUE THREAD

**Issue by ppo-38** [liquibase/liquibase#3036] opened 2021-08-27 15:35 UTC
**Liquibase Snowflake version** : 4.4.3
**Database Vendor & Version**: snowflake

## Description
The calalog name is not include in generated sql orders for liquibase objects (with snowflake database)
For snowflake, catalogName represents database name

So if the databasechangelog tables are not in the same database with another schema name, Liquibase returns that the schema does not exists

## Steps To Reproduce
Set liquibaseCatalogName and liquibaseSchemaName in properties file :
liquibaseCatalogName: MY_DB
liquibaseSchemaName: MY_SCHEMA
Run liquibase updateSQL

## Actual Behavior
generateed SQL orders :

CREATE TABLE **MY_SCHEMA**.DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP_NTZ, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID));

## Expected/Desired Behavior
generated SQL order should be

CREATE TABLE **MY_DB**.**MY_SCHEMA**.DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP_NTZ, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID));

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-2039) by [Unito](https://www.unito.io)

**Comment by nvoxland** [comment] 2022-07-01 21:06
Moving this to liquibase/liquibase now that the snowflake support has moved there

**Comment by FBurguer** [comment] 2022-10-04 16:50
Still an issue for liquibase `4.16.1`

**Comment by Erik-vdg** [comment] 2022-10-25 13:52
@nvoxland By any chance, is there an ETA for this bugfix? My Snowflake organization scheme keeps the DATABASECHANGELOG tables in one catalog, but I wish to create objects in many other catalogs. It is annoying to embed raw sql in my changelogs instead of using the createTable change type.

**Comment by ashitabh** [comment] 2023-03-23 05:04
Hi Team, any update? The issue is still there in V  4.20.0

**Comment by ashitabh** [comment] 2023-03-23 08:59
When I provided all 4 values ( db, schema, warehouse, and role) in the URL, it worked. If the value for the role is not provided, then Liquibase throws a generic error 
"Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Error executing SQL SELECT COUNT(*) FROM DATABASECHANGELOGLOCK: Cannot perform SELECT. This session does not have a current database. Call 'USE DATABASE', or use a qualified name."
So, this issue is resolved for me as of now ( I am not worried about the wrong error message :)

**Comment by FBurguer** [comment] 2023-03-23 17:33
Thanks for the input! @Erik-vdg this is still on the queue to fix, if what @ashitabh says is true, then the issue has been fixed without us noticing it. @Erik-vdg Can you try to reproduce it in your environment? Thanks!

**Comment by roman-ef** [comment] 2023-04-05 16:42
We're currently blocked by this, too. 

The problem seems to be with `SnowflakeDatabase` incorrectly reporting Snowflake's capabilities:

```java
    @Override
    public boolean supportsCatalogInObjectName(Class<? extends DatabaseObject> type) {
        return false;
    }
```

Snowflake does in fact support catalog names in table definitions. I've added a patched `SnowflakeDatabase` in my project, and returning `true` for Tables works here. 

I'll see if I can raise a PR fixing this tomorrow.

**Comment by FBurguer** [comment] 2023-04-05 18:10
Thats great! Thanks

**Closed** 2023-05-03 01:37 UTC
Labels: TypeBug, DBSnowflake
