### ISSUE TITLE
Missing some import entries in OSGI headers

### ISSUE THREAD

**Issue by jherkel** [liquibase/liquibase#1254] opened 2020-07-07 19:44 UTC
## Environment
**Liquibase Version**: 3.10.1

**Liquibase Integration & Version**: osgi apache servicemix 7.0.1 (karaf 4.0.9)

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: PostgreSQL 12

**Operating System Type & Version**: Fedora Linux 32

## Description
There are still some problems with OSGI headers even if issue #1108 was fixed. I have tried to execute liquibase changeset under Apache ServiceMix but it failed with an exception :
java.lang.NoClassDefFoundError: javax/activation/DataSource
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_252]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_252]
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.defineClass(BundleWiringImpl.java:2310) ~[?:?]
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2094) ~[?:?]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1518) ~[?:?]
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:79) ~[?:?]
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1958) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_252]
	at liquibase.osgi.OSGiPackageScanClassResolver.find(OSGiPackageScanClassResolver.java:39) ~[?:?]
	at liquibase.servicelocator.DefaultPackageScanClassResolver.findImplementations(DefaultPackageScanClassResolver.java:89) ~[?:?]
	at liquibase.servicelocator.ServiceLocator.findClassesImpl(ServiceLocator.java:228) ~[?:?]
	at liquibase.servicelocator.ServiceLocator.findClasses(ServiceLocator.java:203) ~[?:?]
	at liquibase.database.DatabaseFactory.<init>(DatabaseFactory.java:28) ~[?:?]
	at liquibase.database.DatabaseFactory.getInstance(DatabaseFactory.java:46) ~[?:?]
	at tech.pantheon.chronos.liquibase.LiquibaseUtils.createDatabase(LiquibaseUtils.java:73) ~[?:?]
	at tech.pantheon.chronos.liquibase.LiquibaseUtils.createLiquibase(LiquibaseUtils.java:56) ~[?:?]
	at tech.pantheon.chronos.liquibase.LiquibaseDrop.performDrop(LiquibaseDrop.java:36) ~[?:?]
	at tech.pantheon.chronos.dev.command.LiquibaseDropAllCommand.execute(LiquibaseDropAllCommand.java:38) ~[?:?]
	at org.apache.karaf.shell.impl.action.command.ActionCommand.execute(ActionCommand.java:83) ~[!/:?]
	at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:67) ~[!/:?]
	at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:87) ~[!/:?]
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:480) ~[!/:?]
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:406) ~[!/:?]
	at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108) ~[!/:?]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:182) ~[!/:?]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:119) ~[!/:?]
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:480) ~[!/:?]
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:406) ~[!/:?]
	at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108) ~[!/:?]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:182) ~[!/:?]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:119) ~[!/:?]
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:94) ~[!/:?]
	at org.apache.karaf.shell.impl.console.ConsoleSessionImpl.run(ConsoleSessionImpl.java:274) [!/:?]
	at org.apache.karaf.shell.impl.console.osgi.DelayedStarted.run(DelayedStarted.java:75) [!/:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource not found by org.liquibase.core [244]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1550) ~[?:?]
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:79) ~[?:?]
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1958) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_252]
	... 35 more

At first I have tried to use command "bundle:dynamic-import" for liquibase-core bundle and everything was working with this. As the second step I have tried to edit manually MANIFEST.MF for liquibase-core.jar. I have added these entries to "Import-Package" section :
javax.activation;version="[1.1,1.1]",javax.xml.bind;version="[2.2.1,2.2.1]",javax.xml.bind.annotation.adapters;version="[2.2.1,2.2.1]",javax.xml.bind.annotation;version="[2.2.1,2.2.1]". (I set one specific version for this quick test). With this update I was also able to execute liquibase changesets.

## Steps To Reproduce
We have an internal library that calls liquibase, our createDatabase  method (see exception stack trace)  contains this code:
  DatabaseConnection liquibaseConnection = new JdbcConnection(c);
    Database database
            = DatabaseFactory.getInstance().findCorrectDatabaseImplementation(liquibaseConnection);

## Additional Context
We don't have any problem with liquibase 3.8.0

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-365) by [Unito](https://www.unito.io)
┆fixVersions: Community 4.x

**Comment by molivasdat** [comment] 2020-07-09 17:20
Thanks @jherkel for writing up the issue.  We will check for differences between 3.8.0 and 3.10.1 in the manifest to see what we can fix.

**Comment by steinarb** [comment] 2020-09-27 08:10
I see this problem as well and what I see is very strange:

1. I first saw the problem in 3.10.1 (which was the first release since 3.8.0 that was a valid OSGi bundle)
2. On July 26 2020 I built the head of the 3.10.x branch as 3.10.2-local-SNAPSHOT
3. When I tried 3.10.2-local-SNAPSHOT in one of my applications I did not get the ".NoClassDefFoundError: javax/activation/DataSource" error
4. The MANIFEST.MF of the 3.10.2-local-SNAPSHOT bundle does not import javax.activation either
5. 3.10.2 was released the day after, i.e. 27 July 2020 but I didn't get around to test it until yesterday (September 27 2020)
6. When I tried 3.10.2 I got the same ".NoClassDefFoundError: javax/activation/DataSource" error as with 3.10.2
7. Today I first tried using the 3.10.2-local-SNAPSHOT I built in July, and that worked fine and did not get the ".NoClassDefFoundError: javax/activation/DataSource" error
8. I scanned the git commits between July 26 and July 27 but didn't see anything that
9. I then built 3.10.3-local-SNAPSHOT from the current 3.10.x HEAD
10. I tried 3.10.3-local-SNAPSHOT and it worked without me getting the ".NoClassDefFoundError: javax/activation/DataSource" error
11. The MANIFEST.MF of the 3.10.3-local-SNAPSHOT does not have javax.activation in its MANIFEST.MF either

I don't know what conclusions to draw from this other than that locally built SNAPSHOTs work, but releases don't work.

And that the reasons the releases don't work is that they can't find a class that isn't imported by anything in the code.

**Comment by steinarb** [comment] 2020-09-27 08:48
The stack trace fails here: https://github.com/liquibase/liquibase/blob/3.10.x/liquibase-core/src/main/java/liquibase/osgi/OSGiPackageScanClassResolver.java#L39

The reason it fails is that the result from BundleWiring.listResources() contains javax.activation.DataSource

There are no javax.activation.DataSource class files in either the release bundles or the snapshot bundles.

Also, if javax.activation.DataSource had been inside the bundle there wouldn't have been any NoClassDefFoundError.

I wonder how BundleWiring.listResources() finds the classes it does?

I'm using karaf 4.2.8 and 4.2.9 with OSGi 6.0.0 for all tests (on openjdk 11 on debian 10 "buster" on amd64)

**Comment by steinarb** [comment] 2020-09-27 09:04
Another interesting thing: the exception that is thrown, is NoClassDefFoundError and not ClassNotFoundException (which is the obvious one) and is caught and logged here: https://github.com/liquibase/liquibase/blob/3.10.x/liquibase-core/src/main/java/liquibase/osgi/OSGiPackageScanClassResolver.java#L44

What's the difference between NoClassDefFoundError and ClassNotFoundException? 
Google tells me NoClassDefFoundError is a class that was available during compilation but not available at runtime.

That didn't tell me much.

However, a fix/workaround would be to catch and debug log NoClassDefFoundError in the same way ClassNotFoundException is caught today.

**Comment by steinarb** [comment] 2020-09-27 09:38
I've created a PR for adding a catch and log of NoClassDefinitionError: https://github.com/liquibase/liquibase/pull/1435

**Comment by steinarb** [comment] 2020-09-27 16:12
It suddenly struck me what might be different: I'm building with and running on Java 11, and the release is (most probably) made with Java 1.8.

I think javax.activation is one of the packages that was moved out in java9...? (or later...? At least it's gone in java 11)
So a reference to javax.activation when buildign may be the cause of the problem, if so there are three possible ways of fixing the issue:

1. Build the release with java 11
2. Add javax.activation manually to Import-Package in the MANIFEST.MF of the liquibase-core bundle and pull in javax.activation at runtime (i.e. ensure javax.activation it is found on the classpath)
3. The fix in the PR which is basically skip and ignore when looking for javax.activation.DataSource in the class scan at startup

**Comment by nvoxland** [comment] 2020-11-03 22:19
Yes, we do build with Java 8 because there is a surprisingly large number of people still running against 8, 9 and 10. It's generally forward compatible, but this sounds like one of the times it causes a problem.

I'm not an expert on OSGi by any means so relying on others for this...

We don't use javax.activation ourselves, but it must be in enough of a dependency to be picked up by the OSGI maven plugin. 

We don't want to auto-require more stuff than we need to so not sure how #2 works or what you mean.

I think the exception catching in #1435 is probably the best and easiest option, but we're also currently not planning on any more 3.10.x releases. The 4.0.0 releases rewrote the classloader logic in general in hopes of avoiding this, **so my big question is "is this issue already resolved in the current release (4.1.1) ? "**

**Comment by CMoH** [comment] 2020-11-11 20:32
Hey! I have also bumped into this, and believe I have a solution in #1534. Please investigate. I hope it will be picked up for an official release, but even so, the patch might be useful for others that need to delay the upgrade to 4.x series.

**Comment by ponziani** [comment] 2021-01-19 13:03
Hi,

About 
> We don't use javax.activation ourselves

For me it works when I remove the pro-package from the liquibase jar, so I do believe the import is necessary for one of the pro-classes. 

I did found the class importing javax.activationDataHandler during debugging, but obviously I can't tell you it's original name because of the obfuscation :-)

These are the packages missing from the Import-Package for me (3.10.3) : 

- javax.activation
- javax.xml.bind.annotation
- javax.xml.bind.annotation.adapters
- javax.servlet

**Comment by CMoH** [comment] 2021-05-04 21:52
Take a look at #1534 - not sure how things are handled here, but bugs should be addressed at some point

**Comment by steinarb** [comment] 2021-05-05 05:49
FWIW Both fixes will probably work, but I think my PR here (just catch the exception and continue) is simpler.

**Comment by molivasdat** [comment] 2021-05-05 18:58
Thanks @CMoH and @steinarb for the suggestions and contributions.  We are doing several things that should move issues and PRs along.  We have implemented a new process so that new PRs are automatically built upon approval and stored in github actions so that if need be you won't have to wait for an official release to test that it works for your specific case.  We are not rebuilding all PRs, just new ones at the moment.  We are also putting in place a new process to get the issues and PRs processed more quickly and transparently.  Thanks for your patience.

**Comment by nvoxland** [comment] 2021-06-14 18:13
I closed #1435 since the changed code is no longer there. But, #1534 is still a good change to get in.

**Comment by steinarb** [comment] 2021-06-14 18:59
Hm "isn't" there for #1435 means there will be no more 3.10.x maintenance releases?

Or does it mean that there will be a 3.10.x maintenance release, but the class scan that failed is no longer present? 
(because if there still is a class scan and it's built on java 8 and run on java 11, the same problem may occur)

**Comment by nvoxland** [comment] 2021-12-03 18:39
The code scanning stuff has changed significantly in 4.x and beyond and there won't be more 3.10.x maintenance releases.

We merged #1534 in for 4.5.0, so this should be addressed in all versions after that.

**Closed by nvoxland** 2021-12-03 18:39 UTC
Labels: TypeBug, StatusConditioning, Severity3, ImpactLow, PRAssociated, DBPostgres, DBAll, ThemeInternals, hacktoberfest
