### ISSUE TITLE
[V4.25.0] Diff changelog command fails without error when indexed column not existing

### ISSUE THREAD

**Issue by amazing4u** [liquibase/liquibase#5346] opened 2023-12-09 14:28 UTC
### Search first

- [X] I searched and no similar issues were found

### Description

Hi,

i want to inform you about a bug, which i found in version 4.25.0 (older versions also affected) and hibernate6:

If you have a Entity and index a column which does not exist (or you typed it wrong) the diff changelog fails without error.

The diff will not be created, but you don't know why. Please throw a exception with a meaningful error message for this error, so the users do not have to search for the problem as long as i had to :slight_smile:

### Steps To Reproduce

You can reproduce it with this example

```
@Entity
@Table(name = "users", indexes = {
        @Index(name = "username_index", columnList = "NOTEXISTINGCOLUMN"),
})
public class UserEntity { ... }
```

```
[INFO] Diff command completed
[INFO] BEST PRACTICE: The changelog generated by diffChangeLog/generateChangeLog should be inspected for correctness and completeness before being deployed. Some database objects and their dependencies cannot be represented automatically, and they may need to be manually updated before being deployed.
[WARNING] Diff changelog command failed
[INFO] Command execution complete
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

### Expected/Desired Behavior

Generation fails with a meaningful error message

### Liquibase Version

4.25

### Database Vendor & Version

PostgreSQL 15

### Liquibase Integration

maven

### Liquibase Extensions

liquibase-maven-plugin

### OS and/or Infrastructure Type/Provider

Windows 11

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment] 2023-12-14 12:58
Hi @amazing4u, thank you for reporting this issue. I have been able to replicate it and I agree that the error message should contain more information.

I'll be forwarding this to the development team so they can evaluate how to move forward.

Thank you,
Tatiana

**Comment by samuelm00** [comment] 2024-04-21 09:45
Not sure if this is related but I ran into a similar problem here when trying to create a many to many relationship between to tables: https://github.com/liquibase/liquibase-gradle-plugin/issues/143

**Comment by tati-qalified** [comment] 2024-04-23 13:46
Hi @amazing4u and @samuelm00. The error message problem is fixed with #5828 - could you use the artifacts from that PR to show what the error is? Let us know if you need further help after that.

Thank you,
Tatiana

**Comment by samuelm00** [comment] 2024-04-26 19:35
@tati-qalified This issues is probably related as well:

```java
class A {
  @Id
  private Long id;

  @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(
        name = "a",
        joinColumns = @JoinColumn(name = "b_id"),
        inverseJoinColumns = @JoinColumn(name = "a_id"))
    private Set<B> bs;
}

class B {
  @Id
  private Long id;

  @ManyToMany(mappedBy = A_.BS, fetch = FetchType.LAZY)
  private Set<A> as;
}
```

If the `@JoinTable(name)` is equal to an existing table, liquibase executed the `diffChangelog` command successfully but didn't generate any files.

But when you run the command with `--debug` you can see the following message:
`WARNING [liquibase.command] Diff changelog command failed`

**Comment by amazing4u** [comment] 2024-04-30 21:53
@tati-qalified How can we try the latest master when there is no new release yet? Is there some snapshot version we can use?

**Comment by tati-qalified** [comment] 2024-05-06 13:01
@amazing4u 
You can download it from here: https://github.com/liquibase/liquibase/actions/runs/8930022026/artifacts/1468641178 or obtain it using GPM [(gradle](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-gradle-registry#using-a-published-package) or [maven](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry) ):

```
<dependency>
 <groupId>org.liquibase</groupId>
 <artifactId>liquibase-core</artifactId>
 <version>master-SNAPSHOT</version>
</dependency>
```

```
api("org.liquibase:liquibase-core:master-SNAPSHOT")
```

**Comment by amazing4u** [comment] 2024-05-08 22:40
> @amazing4u You can download it from here: https://github.com/liquibase/liquibase/actions/runs/8930022026/artifacts/1468641178 or obtain it using GPM [(gradle](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-gradle-registry#using-a-published-package) or [maven](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry) ):
> 
> ```
> <dependency>
>  <groupId>org.liquibase</groupId>
>  <artifactId>liquibase-core</artifactId>
>  <version>master-SNAPSHOT</version>
> </dependency>
> ```
> 
> ```
> api("org.liquibase:liquibase-core:master-SNAPSHOT")
> ```

Sorry, i was not able to use/install the provided snapshot version.

Tried with maven, but the snapshot versions are not in maven central repository.
`Could not resolve dependencies for project XYZ: org.liquibase:liquibase-core:jar:master-SNAPSHOT was not found in https://repo.maven.apache.org/maven2/ during a previous attempt`

Also tried to install the library manually using mvn install:install-file on the liquibase-core.jar but this also failed ;/

**Comment by tati-qalified** [comment] 2024-05-15 13:17
@amazing4u no worries, thank you for trying.
I can confirm that the problem is solved with the current master version (as of 15/05/2024). 

To reproduce this scenario: have an entity annotated with 
```
@Entity
@Table(name = "users", indexes = {
        @Index(name = "username_index", columnList = "NOTEXISTINGCOLUMN"),
})
public class UserEntity { ... }
```
and an application that creates and commits an instance of this entity.

Run the application, which will fail with the following error message:
```
The following error was observed Unable to create index (NOTEXISTINGCOLUMN) on table 'items' since the column 'NOTEXISTINGCOLUMN' was not found 
(specify the correct column name, which depends on the naming strategy, and may not be the same as the entity property name)
```

This fix will be included in our next release, which should be in just a few days. I'll be closing this issue, but feel free to reopen it if the problem persists.

Thank you,
Tatiana

**Closed by tati-qalified** 2024-05-15 13:17 UTC
Labels: TypeBug, DBPostgres, IntegrationMaven, errorReporting, triaged
