### ISSUE TITLE
liquibase.exception.LockException: java.lang.ClassCastException: java.time.LocalDateTime cannot be cast to java.util.Date

### ISSUE THREAD

**Issue by haidiiii** [liquibase/liquibase#1749] opened 2021-03-05 07:11 UTC
## Environment
**Liquibase Version**:

4.3.1

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

spring boot

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:
MySQL  5.7.25

**Operating System Type & Version**:
windows 10

## Description
```
liquibase.exception.LockException: java.lang.ClassCastException: java.time.LocalDateTime cannot be cast to java.util.Date
	at liquibase.lockservice.StandardLockService.listLocks(StandardLockService.java:404)
	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:225)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:219)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.Liquibase.runInScope(Liquibase.java:2322)
	at liquibase.Liquibase.update(Liquibase.java:216)
	at liquibase.Liquibase.update(Liquibase.java:202)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:322)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:275)
	at org.springframework.boot.autoconfigure.liquibase.DataSourceClosingSpringLiquibase.afterPropertiesSet(DataSourceClosingSpringLiquibase.java:46)
	at com.test.jpa.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:100)
	at com.test.jpa.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$0(AsyncSpringLiquibase.java:75)
	at com.test.core.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: java.time.LocalDateTime cannot be cast to java.util.Date
	at liquibase.lockservice.StandardLockService.listLocks(StandardLockService.java:396)
	... 18 common frames omitted
```

**Comment by molivasdat** [comment] 2021-03-12 01:23
Hi @BillowsVan Thanks for writing up this issue.  Are you using the 8.0.23 version of the mySQL driver?  If so, we have a fix planned for Liquibase v4.3.2 which should be coming out shortly.

**Comment by haidiiii** [comment] 2021-03-15 13:41
My MySQL driver version is 8.0.23. Thanks for you replay.

**Comment by matejsp** [comment] 2021-04-08 05:41
We are using latest 4.3.2, but we have the same issue. Wasn't this supposed to be fixed in 4.3.2?

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.LockException: java.lang.ClassCastException: class java.time.LocalDateTime cannot be cast to class java.util.Date (java.time.LocalDateTime and java.util.Date are in module java.base of loader 'bootstrap')
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:769)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1313)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
	at net.iconomi.core.IconomiCoreApplication.main(IconomiCoreApplication.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: liquibase.exception.LockException: java.lang.ClassCastException: class java.time.LocalDateTime cannot be cast to class java.util.Date (java.time.LocalDateTime and java.util.Date are in module java.base of loader 'bootstrap')
	at liquibase.lockservice.StandardLockService.listLocks(StandardLockService.java:404)
	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:225)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:220)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.Liquibase.runInScope(Liquibase.java:2370)
	at liquibase.Liquibase.update(Liquibase.java:217)
	at liquibase.Liquibase.update(Liquibase.java:203)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:321)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:275)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
	... 26 common frames omitted
Caused by: java.lang.ClassCastException: class java.time.LocalDateTime cannot be cast to class java.util.Date (java.time.LocalDateTime and java.util.Date are in module java.base of loader 'bootstrap')
	at liquibase.lockservice.StandardLockService.listLocks(StandardLockService.java:396)
	... 39 common frames omitted
```

**Comment by molivasdat** [comment] 2021-04-08 12:22
Hi @matejsp We did make a change to fix LocalDateTime issues but looks like we missed your testcase, possibly here.

https://github.com/liquibase/liquibase/blob/431b960239de56aea75487628dfc39da54a54c70/liquibase-core/src/main/java/liquibase/lockservice/StandardLockService.java#L396

Here is where we made the original fix.
https://github.com/liquibase/liquibase/pull/1664

**Comment by matejsp** [comment] 2021-04-08 15:49
I see ... you are correct ... can you fix it or should I file another bug report?

**Comment by molivasdat** [comment] 2021-04-08 22:39
@matejsp you can still use this one.  Do you have a simple test case that shows the error so that when we fix this one we can test and verify it is fixed?

**Comment by matejsp** [comment] 2021-04-09 05:54
This occurs after changeloglock timeout. After timeout code displays the list of locks (currently crashes).

**Comment by molivasdat** [comment] 2021-04-12 14:44
Hi @matejsp Are you calling listLocks in your application or is your application running on multiple instances.  Just trying to get a simple testcase that shows the problem because this will typically not happen if there is only one app updating the database at a time.  Do you have a repo that shows the problem?  We are just making sure we validate that the problem is fixed instead of changing the code and guessing that it should be fixed for your issue.

**Comment by matejsp** [comment] 2021-04-12 19:24
Well liquibase is calling listLocks by itself after obtain lock timeout. 

In our case we were having busted upgrades (native sql) in mysql (using percona cluster) that deadlocked due to another microservice updating data in a table that was upgraded. This error left databasechangelog locked.

Other case when this happened was when service was -9 killed in the middle of the liquibase upgrade (since transaction log was getting so big and db cluster couldn't handle it any more).

**Closed** 2021-08-05 20:28 UTC
Labels: TypeBug, StatusDiscovery, Severity3, ImpactMedium, DBMySQL, IntegrationSpringboot

**Comment by moabdi** [comment] 2021-11-17 16:00
I fixed probleme by truncate table DATABASECHANGELOG
