### ISSUE TITLE
autoIncrement="true"  lose efficacy (DUPLICATE #2301)

### ISSUE THREAD

**Issue by FileNotFoundExcetion** [liquibase/liquibase#2703] opened 2022-03-30 14:31 UTC
<column name="id" type="bigint"  remarks="xxx" autoIncrement="true">
<constraints primaryKey="true"/>
</column>
when i add remarks xxx ,autoIncrement="true"  lose efficacy。

But this condition is vaild
<column name="id" type="bigint" autoIncrement="true">
<constraints primaryKey="true"/>
</column>
means there were no  remarks="xxx".

since i used liquid-core after 4.8.0

**Comment by kataggart** [comment] 2022-03-30 18:07
@FileNotFoundExcetion can you confirm what database you are using?

Is what you are are experiencing the same as what is  described here: https://github.com/liquibase/liquibase/issues/2634 or https://github.com/liquibase/liquibase/issues/2301?

Thanks!

**Comment by FileNotFoundExcetion** [comment] 2022-03-30 22:49
I used mysql 。when i upgrade my liquid-core verison. 
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/29888589/160943497-4edf7eb3-d52e-4b31-a356-dad3e94a80a6.png">
the first table "ems_user_01"   didnot generate autoIncrement..

**Comment by FileNotFoundExcetion** [comment] 2022-03-30 22:58
similar to https://github.com/liquibase/liquibase/issues/2634.      but equals to https://github.com/liquibase/liquibase/issues/2301?

**Comment by nvoxland** [comment] 2022-04-13 22:03
This is a duplicate of #2301 and fixed by #2752. 

I'll close this version to centralize tracking

**Closed by nvoxland** 2022-04-13 22:03 UTC
Labels: TypeBug, ver4.8.0
