### ISSUE TITLE
Liquibase potentially not applying changesets in order

### ISSUE THREAD

**Issue by oswaldquek** [liquibase/liquibase#1636] opened 2021-01-18 16:35 UTC
## Environment
**Liquibase Version**: 4.2.x

**Liquibase Integration & Version**: maven 3

**Liquibase Extension(s) & Version**: n/a

**Database Vendor & Version**: postgres 11

**Operating System Type & Version**: MacOS 10.14.6

## Description
We tried to upgrade liquibase [from 4.1.0 to 4.2.2](https://github.com/alphagov/pay-connector/pull/2739) but our build failed. It appears that although [a foreign key constraint was dropped](https://github.com/alphagov/pay-connector/blob/master/src/main/resources/migrations.xml#L1433-L1437), followed by [making the column which had the foreign key constraint non null](https://github.com/alphagov/pay-connector/blob/master/src/main/resources/migrations.xml#L1439-L1443), some tests failed with the error 

```
liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set migrations.xml::drop not null constraint on charge_id on refunds table:::
     Reason: liquibase.exception.DatabaseException: ERROR: column "charge_id" of relation "refunds" is an identity column [Failed SQL: (0) ALTER TABLE public.refunds ALTER COLUMN  charge_id DROP NOT NULL]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:124)
```

I made a [commit](https://github.com/alphagov/pay-connector/pull/2739/commits/0393bbdbd618f8c1b4860cbeff59a7729e39e3f5) to make the [PR](https://github.com/alphagov/pay-connector/pull/2739) pass but I think this might be to do with a bug with liquibase that causes the LiquibaseException to be thrown to begin with.

Is it possible that liquibase tried to apply "make column non null" before "drop foreign key constraint"?

## Steps To Reproduce
* Get source code at https://github.com/alphagov/pay-connector
* Checkout branch dependabot/maven/org.liquibase-liquibase-core-4.2.2
* `git checkout ac2e222cb9c591997f2aed9f05bdfb7e61ae5224`
* `mvn clean verify` to prove some integration tests fail

## Actual Behavior
```
[INFO] Running uk.gov.pay.connector.charge.resource.ChargesFrontendResourceWorldpayJwtIT
[ERROR] WARNING: An illegal reflective access operation has occurred
[ERROR] WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/Users/oswaldquek/.m2/repository/com/google/inject/guice/4.2.3/guice-4.2.3.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
[ERROR] WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
[ERROR] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[ERROR] WARNING: All illegal access operations will be denied in a future release
liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set migrations.xml::drop not null constraint on charge_id on refunds table:::
     Reason: liquibase.exception.DatabaseException: ERROR: column "charge_id" of relation "refunds" is an identity column [Failed SQL: (0) ALTER TABLE public.refunds ALTER COLUMN  charge_id DROP NOT NULL]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:124)
	at liquibase.Liquibase.lambda$null$0(Liquibase.java:275)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.Scope.child(Scope.java:222)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:274)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.Liquibase.runInScope(Liquibase.java:2277)
	at liquibase.Liquibase.update(Liquibase.java:215)
	at liquibase.Liquibase.update(Liquibase.java:201)
	at liquibase.Liquibase.update(Liquibase.java:197)
	at liquibase.Liquibase.update(Liquibase.java:189)
	at io.dropwizard.migrations.DbMigrateCommand.run(DbMigrateCommand.java:65)
	at io.dropwizard.migrations.DbCommand.run(DbCommand.java:55)
	at io.dropwizard.migrations.AbstractLiquibaseCommand.run(AbstractLiquibaseCommand.java:68)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at pay.connector@0.1-SNAPSHOT/uk.gov.pay.connector.junit.DropwizardJUnitRunner.classBlock(DropwizardJUnitRunner.java:91)
```

## Expected/Desired Behavior
All tests should pass

**Comment by molivasdat** [comment] 2021-01-21 00:07
Hi @oswaldquek Thanks for writing this issue.  I will use the repo you provided to try to reproduce the issue.

**Comment by tati-qalified** [comment] 2023-08-10 19:03
I've tested this bug with liquibase version 4.23.0, and I'm not getting the specified error. 
When running the provided tests (thank you!), the changesets seem to be ran in order, and the only errors or failures are related to file paths, which are probably due to the fact that I'm using a different computer and OS.
I will be closing this issue, but feel free to reopen it if the problem persists.

**Closed by tati-qalified** 2023-08-10 19:03 UTC
Labels: TypeBug, Severity3, ImpactLow, DBPostgres, IntegrationMaven
