### ISSUE TITLE
Liquibase 4.19.0 now requires a non-empty author attribute

### ISSUE THREAD

**Issue by pavel-treutner** [liquibase/liquibase#3873] opened 2023-02-28 17:05 UTC
### Search first

- [X] I searched and no similar issues were found

### Description

Feature #1290 released in 4.19.0 newly enforces an author to be set. As we are currently passing empty strings (e.g. &lt;changeSet id="1" author=""&gt;), validation fails - even for change sets already applied to production. This is a backward incompatible change that should have been avoided.
At the moment I can see the only possible way to upgrade to the new version: to add authors everywhere, which violates time-proven rule to never touch applied migrations. And to clear checksums in existing databases which goes against equally proven principle: do not mess about with production data.
Is there a chance the feature will be reverted?

### Steps To Reproduce

Just update the library.

### Expected/Desired Behavior

Do not enforce authors. Or make the validation configurable.

### Liquibase Version

4.19.0

### Liquibase Integration

Spring Boot

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by nvoxland** [comment] 2023-03-02 21:50
Yeah, you can't really be adding new authors because that will change the identifiers of the changesets and cause them to be reran.

The author attribute is there to make the overall unique identifier easier to maintain. If it is just "id", you'd have to coordinate the id generation with everyone on the team which is much harder than each person only having to remember what ids they have used.

But, we did allow authors to be empty because sometimes people can coordinate the "id" fields because they are the only person on the team, or they worry that the author field is being used to track what they're doing or something. Having author empty is not a best practice, but people would do it.

So the reason the validation was added was because people would sometimes forget the author when they were wanting it and then get in trouble because it can't be added back later. The validation keeps people doing the right thing from the "beginning". But that does force you to follow that recommendation, and puts you in a tough spot if you have existing changesets with an empty author.

Maybe best to have a global config of "allowEmptyAuthors" or something? Or that config added to the changelog file itself?

**Comment by pavel-treutner** [comment] 2023-03-04 07:25
Yes, having the validation configurable would solve our issues. What about adding a new Spring Boot property, e.g.: spring.liquibase.validation.strict=false?

**Comment by nvoxland** [comment] 2023-03-07 20:19
We have an existing `liquibase.strict` setting already. The question is how the spring boot integration works with that setting. We introduced a configuration API which spring could plug into so that any of our `liquibase.xyz` settings are automatically settable via `spring.liquibase.xyz` attributes. I don't **_think_** they've taken advantage of that yet, but I should check with them. 

If they've not, they'll need to newly let that setting exposed one way or the other. If not, you'd have to use a `liquibase.strict` system property a `liquibase_strict` env variable to set it.

If you'd rather not wait and/or if you want to enable strict mode in general, you'll need to update your "author" to some placeholder value like "empty" or "x" or whatever you like, then run `update databasechangelog set author='x' where author=''` on each environment before you run the upgraded liquibase for the first time.

**Comment by XDelphiGrl** [comment] 2023-03-15 16:41
This ticket requires manual testing as well as adding an automated regression test for empty author.

**Comment by MalloD12** [comment] 2023-03-15 16:45
> This ticket requires manual testing as well as adding an automated regression test for empty author.

Agree. I'm thinking to add some unit tests for this, plus including some changeset with the empty author as part of our integration tests.

**Comment by MalloD12** [comment] 2023-03-17 15:53
I was trying to implement a fix for this issue by making use of `Strict` global configuration  by setting `strict=TRUE` (or `liquibase.strict`), but I'm getting the below error:

```
Error parsing command line: Liquibase detected the following invalid LIQUIBASE_* environment variables:

- LIQUIBASE_LAUNCHER_DEBUG
- LIQUIBASE_LAUNCHER_PARENT_CLASSLOADER
- LIQUIBASE_PRO_LICENSE_KEY

Please rename them and run your command again, or set liquibase.strict=FALSE or LIQUIBASE_STRICT=FALSE.
``` 

I just found out this is happening because we are throwing an `IlegalArgumentException` in the code (EnviromentValueProvider):
 ```
if (strict) {
                message += "Please rename them and run your command again, or set liquibase.strict=FALSE or LIQUIBASE_STRICT=FALSE." + System.lineSeparator();
            }
            message += "Find the list of valid environment variables at https://docs.liquibase.com/environment-variables" + System.lineSeparator();
            if (!printedInvalidEnvironmentVariablesMessage.getAndSet(true)) {
                Scope.getCurrentScope().getUI().sendMessage("WARNING: " + message);
                Scope.getCurrentScope().getLog(EnvironmentValueProvider.class).warning(message);
            }
            if (strict) {
                throw new IllegalArgumentException(message);
            } 
```
I guess we should remove this piece of code now if we are going to make use of a valid case in case `strict=true`. Is that correct, @nvoxland?

**Closed** 2023-04-06 18:59 UTC
Labels: TypeBug, ManualTest, blocked, needs_response
