### ISSUE TITLE
Table creation fails with H2 v2 when a change set specifies an integer size, e.g. INT(10)

### ISSUE THREAD

**Issue by CynanX** [liquibase/liquibase#3250] opened 2022-09-07 09:27 UTC
## Environment

**Liquibase Version**: 4.9.1

**Liquibase Integration & Version**: SpringBoot v2.7.3

**Database Vendor & Version**: H2 v2.1.214

**Operating System Type & Version**: MacOS v12.5

## Description

Since upgrading to H2 v2 my change set no longer applies.

## Steps To Reproduce

Create a change set such as this:

```xml
 <changeSet author="mark" id="createPersonsTable">
     <createTable tableName="persons">
         <column name="personId" type="INT(10)"/>
         <column name="lastName" type="VARCHAR(255)"/>
         <column name="firstName" type="VARCHAR(255)"/>
         <column name="address" type="VARCHAR(255)"/>
         <column name="city" type="VARCHAR(255)"/>
     </createTable>
 </changeSet>
```

The magic part is the `INT(10)`.

Recreation is [here](https://github.com/CynanX/LiquibaseH2Issue).

## Actual Behavior

An exception is throw: -

```
2022-09-07 10:11:41.855  WARN 23829 --- [           main] o.s.w.c.s.GenericWebApplicationContext   : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set changelog/1.0.0/tables/create_persons_table.xml::createPersonsTable::mark:
     Reason: liquibase.exception.DatabaseException: Syntax error in SQL statement "CREATE TABLE PUBLIC.persons (personId INT[*](10), lastName VARCHAR(255), firstName VARCHAR(255), address VARCHAR(255), city VARCHAR(255))"; expected "ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
CREATE TABLE PUBLIC.persons (personId INT(10), lastName VARCHAR(255), firstName VARCHAR(255), address VARCHAR(255), city VARCHAR(255)) [42001-214] [Failed SQL: (42001) CREATE TABLE PUBLIC.persons (personId INT(10), lastName VARCHAR(255), firstName VARCHAR(255), address VARCHAR(255), city VARCHAR(255))]
```

## Expected/Desired Behavior

The table should be created.

## Additional Context

The above change set works fine when using H2 v1.x.

**Comment by MalloD12** [comment] 2022-09-13 21:21
Hi @CynanX I have started working on a fix for this, but just to be clear with this when specifying a size of an int like in this case (int(10)). Are we trying to generate an integer of max 10 digits, correct?

Thanks,
Daniel.

**Comment by CynanX** [comment] 2022-09-13 21:28
That is the desired effect yeah. Thanks for looking into this.

**Comment by cwrsimon** [comment] 2022-09-22 18:25
Liquibase: 2.16.1
H2: 2.1.214

Sorry that I'm late for the party.
We seem to have the same issue in our project, but with the "smallint" type in H2 2.1.214.
While trying to migrate the schema of a Postgres database, table columns that have the Postgres datatype "int2(5)" are converted to "smallint(5)" in the resulting create table statements. Unfortunately, "smallint(5)" is rejected as wrong syntax by the H2 driver, just "smallint" would be fine.

**Comment by MalloD12** [comment] 2022-09-22 18:32
Hi @cwrsimon thanks for being in contact and sharing that info with us. We have recently developed a fix for this issue which hopefully will be released very soon.

Thanks,
Daniel.

**Comment by cwrsimon** [comment] 2022-09-22 19:14
Hi @MalloD12 , that's great news, thank you! 
I took a quick look at the PR. I'm not very familiar with the liquibase code base, yet, so forgive me for asking: Your fix doesn't cover "smallint", or does it?

**Comment by MalloD12** [comment] 2022-09-23 13:41
Hi @cwrsimon, thanks so much for your feedback. Please let me discuss it today with the team and I'll get back to you afterwards. 

Thanks,
Daniel.

**Comment by MalloD12** [comment] 2022-09-23 14:53
Hey @cwrsimon I can quickly fix this. For example for the case of an `INT` I can make a change to parse something like `INT(5)` to an `SMALLINT`, but I guess what you are referring here is to parse something like: `SMALLINT (xy)` to the corresponding type. Would you mind sharing a changelog/changeset example/s on how you are using this so I can get a better idea on how the fix would be?

Thanks,
Daniel.

**Comment by cwrsimon** [comment] 2022-10-04 21:31
Hi @MalloD12 , I'm sorry for replying to you that late. I must have overseen the notification I got in my e-mails. I'm sorry for that.
In the meantime I was able to figure out a nice little example to reproduce the issue.
Let's say this is our table in Postgresql:
`
CREATE TABLE test.test (
	test_smallint int2 NULL
);
`
When comparing the Postgresql database with an empty H2 database, running "liquibase diff-changelog" will yield a changelog like this:
`<changeSet author="me (generated)" id="1664918405238-1">
        <createTable tableName="test">
            <column name="test_smallint" type="SMALLINT(5)"/>
        </createTable>
    </changeSet>
` 
The problem with this changelog is the type "SMALLINT(5)". When generating H2-specific SQL for this changelog by running "liquibase update-sql", Liquibase will generate a create table statement that looks like this:
`
CREATE TABLE PUBLIC.test (test_smallint SMALLINT(5));
`
Running this statement in H2 will yield a syntax error. 
The correct statement would be:
`
CREATE TABLE PUBLIC.test (test_smallint SMALLINT);
`
I hope, this clears up things.

**Comment by MalloD12** [comment] 2022-10-05 13:50
> 

Hi @cwrsimon, no worries. We have coded a [solution](https://github.com/liquibase/liquibase/pull/3274) for this type of issue for the different data types people are experiencing this type of issue on H2. If you have any feedback, concern, or any other use case about this issue you can think of please don't hesitate to share it with us.

Thanks,
Daniel.

**Closed** 2022-11-08 07:07 UTC
Labels: TypeBug, DBH2, IntegrationSpringboot, ver4.9.1, DBVGuaranteed
